### ISSUE TITLE
Onboard mark for Private and Public cloud products

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1000]
it is not clear if a user has onboarding meeting for public or private cloud

would be helpful for admins to see in a dashboard if a user already has been onboarded to public or private cloud platform

Now we have marks for onboarded and not onboarded users for private cloud in both public and private cloud requests 

**Definition of done/Acceptance Criteria**
- public cloud request users in a dashboard are marked with green check sign if they are onboarded for public cloud
- private cloud request users in a dashboard are marked with green check sign if they are onboarded for private cloud

**Comment by funtigr** [comment]
Now the marks are working separately and if the red mark is removed. On the screenshot the same user already has Products in Private Cloud and doesn't have it for Public Cloud:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalc5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e88f79cb4f6627e2a22a555ee2493545bc617aca/image.png)
