### ISSUE TITLE
Add a Billing Contact email field to Public Cloud provisioning form

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1005]
Some teams working in public cloud would like to have a copy of their quaterly billing report sent to a specific email. Right now only Product Owners listed on the project form receive the quaterly billing reports and have to foward the reports to the team's Financial Advisors or Expense Authority manually. It would be helpful to have a copy of the report sent to another email address of their choise.

Definition of Done:

- [ ] A new field "Billing Contact" added to the provisioning form for public cloud requests that collects a valid government email (not IDIR, as it can be a shared team mailbox that is not associated with an IDIR).

**Comment by mitovskaol** [comment]
This functionality is no longer relevant as we will be managing billing contacts via the user management feature (tracked in a different ticket).
