### ISSUE TITLE
For Gold projects, it should receive two callbacks from both Gold and GoldDR then mark as provisioned

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1008]
Describe the issue
Backend issue

Definition of done/Acceptance Criteria
Our backend handles the situation when one of the clusters failed the Gold and GoldDr provisioning. If any of the Gold or GoldDr namespaces within 1 product fails the provisioning, the whole Gold and GoldDR set should fail the provisioning.

**Comment by funtigr** [comment]
Now if GoldDR is requested and one callback is received, the product has decisionStatus: PARTIALLY_PROVISIONED. 
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjByQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b78068e028c6539d796ec29c30788bfea1f97ca/image.png" alt="image.png" />

And only after the second callback it becomes: PROVISIONED.
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjRyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9a65d172ed0e972f98535801d25f8e8cdd5597d/image.png" alt="image.png" />

If GoldDR is "turned off" then the product is provisioned after one callback.

If GoldDR was "turned off" and the request "turns it on" then it requires two callbacks.

In opposite situation it requires one callback.
