### ISSUE TITLE
Integration between Eventbrite and Platform/Product Registry

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1010]
Describe the issue

The current process of adding OpenShift 201 participants in to the registry as technical leads is completed manually. Cleanup of project sets is also undertaken manually.

Additional context

This ticket is to automate the process of gathering the necessary information from EventBrite, updating the registry and cleaning up OpenShift Objects from the project sets.

The necessary inputs from Eventbrite are:

- Date of 201 Workshop Registered For
- First Name
- Last Name
- Email Address
- Github ID

At a set period prior to the 201 workshops, these inputs should be updated sequentially into the OpenShift 201 Training namespaces. Any previously listed secondary technical lead information should be deleted. New participant details should be entered into the 'secondary technical lead' registry field for each project set.

If it is possible to automate OpenShift object cleanup as part of this same process, it would be helpful to run these tasks prior to adding new participants to the registry:

- delete all OpenShift object for each namespace `delete --all all,secret,configmap,pvc,el,route,svc,netpol,pipelines,tasks, pdb, triggerBindings, triggerTemplates'
- remove-role-from-user admin for each namespace

It would be helpful to include a manual trigger in this process, to confirm that this automation will run. It would be useful to have the ability to exclude specific project sets if needed.

How does this benefit the users of our platform?
Smoother and more reliable training namespace setup

Definition of done

- [ ]  201 participant details can automatically updated from Eventbrite to the Platform/Product Registry ahead of each 201 workshop
- [ ]  201 project set cleanup is automatic

**Comment by Iryna-Kaplun** [comment]
Comment from Matt on Sep 26, 2022: 
Link to the document we discussed Sep 26th with OC commands generated based on participant details: https://docs.google.com/spreadsheets/d/1_6Na5YpqFxFMWEn0SCh5sJeJaE9q-YX-6jgCmeKfTf0/edit#gid=0

**Comment by Iryna-Kaplun** [comment]
Comment from Oamar on Mar 23, 2023: 
Let's go over this again, I know that Mat has some scripts that do something similar, so lets see if the scope has changed for this ticket.

**Comment by mtspn** [comment]
I have scripts I can run manually to do the cleanup work, but I still think it would be valuable to have the integration with the registry and eventbrite for a assigning roles and access to people who have registered.

**Comment by mtspn** [comment]
Closing as most of this functionality is unnecessary on completion of #2790
