### ISSUE TITLE
Email delete product notification for public cloud user

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1035]
after hitting confirm button on the confirm modal a user should get an email, notified about saucerful product deletion 

- create email template
- send template after hitting a confirmation btn by a user on confirmation modal on a product page

**Comment by funtigr** [comment]
After creating a deletion request the email is received by customer:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3psIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f82d5232ae9c11f02526d1d8b9d43bded475152b/image.png)
