### ISSUE TITLE
Rewrite Registry landing page in public cloud 

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#1036]
**Describe the issue**
Rewrite landing page to be inclusive of public cloud.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBby9yIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a9cec8bf9dba939181acde9db5e57c7af2d9ec71/Screenshot%202023-09-28%20at%201.11.51%20PM.png)

**How does this benefit the users of our platform?**
- [x] Makes sure our language makes sense and is unified 

**Definition of done**
- [x] Rewrite content - Alex and/or Pilar. Amritpal will reach out to Pilar while Alex is away
- [x] Add Public Cloud to the landing page as it only speaks about private cloud
- [x] For onboarding contacts: for Private cloud - use Platform Services Team email; for Public Cloud - use Pathfinder's team email (please confirm with the Public Cloud re the proper email for onboarding) 
- [x] Run the final text draft by Sal before implementing 
- [x] Get developers to implement code - Ampritpal

**Comment by Amritpal-Nijjar** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0w5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--03d117cc9f050c4bc595e046702a19894329d7fa/image.png)

**Comment by Pilargit12** [comment]
File of suggested changes can be found: https://docs.google.com/document/d/1pIHVRj2NF0j61wTND9yqJ1pKsY7VqP1BdYxg6e7EZ2s/edit

**Comment by Amritpal-Nijjar** [comment]
Implemented the changes and had them approved by Sal. There are 2 issues I know of:
1) Missing URL for the clickable links
2) The Log in with BC IDR needs work

**Comment by funtigr** [comment]
Looks good except a couple of minor things:

1. The parentheses at the bottom of the page are shown with escape characters in front
2. The gap above "Before you start" looks a bit bigger than above other titles
3.  If you are already logged in and visit the Login page you see the link to Sign Out that is moved out of place and is shown in plane text

I will add screenshots later because adding media doesn't work now.

**Comment by Amritpal-Nijjar** [comment]
Fixed the gap between paragraphs
Fixed the escaped brackets
TODO: Create ticket that addresses the issue where Sign Out button is not rendered properly when Signed In

**Comment by funtigr** [comment]
Points 1 and 2 from the comment above are fixed.
I've created a separate task for point 3:
https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/1113

**Comment by funtigr** [comment]
Points 1 and 2 from the comment above are fixed.
I've created a separate task for point 3:
https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/1113
