### ISSUE TITLE
Provisioner

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1060]
App Dev Team will be taking over Provisioner from Ian Watts (contractor). 
Artem will be the lead on this.

**Definition of done:** 
- [x] Go through basic KT Sessions and Practice  
- [x] Implement 5 simple or 2 serious tasks on Provisioner development side whichever is made first

**Comment by mitovskaol** [comment]
@Iryna-Kaplun  what is the status of this Epic? if it has been complete, please close it
