### ISSUE TITLE
Provisioner: Update and deploy new app-provisioner image

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1061]
**Describe the issue**
The Application Developers need to know how to apply changes to the app-provisioner image, test the changes in a lab cluster, and then apply the change to all clusters.

**Rational/Why**
The Application Developers will soon take over the maintenance of the provisioner.

**Additional Context**

https://github.com/bcgov-c/devops-fulfillment-pipeline
https://github.com/bcgov-c/tenant-gitops-eb6118
https://provisioner.apps.silver.devops.gov.bc.ca

**Dependencies**

app-provisioner image
Argo Events
Argo Workflows
Tests
These steps are described in general terms. We can go through the process together - that is, with Ian.

Clone the app-provisioner repo: https://github.com/bcgov-c/devops-fulfillment-pipeline
Create a new branch, such as "practice_ian"
Make a small change to the Ansible playbook, such as the addition of a debug message
Commit the branch and change back to the repo
Update the app-provisioner BuildConfig to build from your branch
Test the new image in Dev or Test by updating the appropriate lab sensor and submitting a registry request in that environment
Inspect the container logs and verify that your test message is present
Tag the image, using the next logical patch number
Update the sensors for each cluster to use the new version

**Definition of done/Acceptance Criteria**

- [x]  New image has been built
- [x]  Image has been tested in lab
- [ ]  Update has been deployed to all clusters
- [ ]  Test branches have been merged and deleted

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/1061?planning-poker) with Zenhub @okanji @funtigr @Kolezhanchik @alexandralloyd @calbertan @Amritpal-Nijjar

**Comment by funtigr** [comment]
After all the actions the test image is shown in the test provisioner workflows:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbab4535bd444162389ab2643a2902fd96282cda/image.png)

The test message added in the code is shown in the logs:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbad9d553b49e262f690706de7b94cf0db1413db/image.png)

**Comment by funtigr** [comment]
Me, Zhanna and Christopher have finished this practise.
As we were making test changes we did not make a deploy to all clusters. We made for a test one and reverted the changes back.
