### ISSUE TITLE
Add User Access Management for Public Cloud projects

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#1065]
FEEL FREE TO TURN IT INTO AN EPIC AND BREAK INTO SEPARATE TICKETS FOR UI DESIGN AND UI DEVELOPMENT

As a PO or TL of a public cloud project  I would like t[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkxjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4b0b7d6223ecb479d6c7e1ae37ddb36acbdc5f83/Screen%20Shot%202023-09-26%20at%202.26.37%20PM.png)
o be able to add/remote other team members to the following security groups in public cloud myself:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkRjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c9309c0a2a7fb5a33bd5f0f0ed2d61f11825d2ca/image.png)

Acceptance criteria:

 - update the Registry UI to allow to add/remove users to the security groups listed above, add this functionality to the the Public Cloud create and edit pages

**Comment by MaxWardle** [comment]
Additional Context: 

- Admin - AdministratorAccess is an [AWS managed policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#aws-managed-policies) that: Provides full access to AWS services and resources.

- Developer - AdministratorAccess is an [AWS managed policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#aws-managed-policies) that: Provides full access to AWS services and resources.

- Billing Viewer - AWSBillingReadOnlyAccess is an [AWS managed policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#aws-managed-policies) that: Allows users to view bills on the Billing Console.

- Viewers - ViewOnlyAccess is an [AWS managed policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#aws-managed-policies) that: This policy grants permissions to view resources and basic metadata across all AWS services.

- Security Auditor - SecurityAudit is an [AWS managed policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#aws-managed-policies) that: The security audit template grants access to read security configuration metadata. It is useful for software that audits the configuration of an AWS account.

**Comment by MaxWardle** [comment]
NOTE: Billing Viewer and Security Auditor may change in the near future as their use case is slightly different than what the the policy allows.
