### ISSUE TITLE
KT re Provisioner from Ian

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1068]
**DoD:** 

- [x] watch the training video created by Ian re how the provisioner works
link to the video: [click here](https://bcgov-my.sharepoint.com/personal/artem_kravchenko_gov_bc_ca/_layouts/15/onedrive.aspx?sortField=DateShared&isAscending=false&groupBy=&id=%2Fpersonal%2Fian%5F1%5Fwatts%5Fgov%5Fbc%5Fca%2FDocuments%2FRecordings%2FProvisioner%20training%2D20230125%5F130321%2DMeeting%20Recording%2Emp4&listurl=%2Fpersonal%2Fian%5F1%5Fwatts%5Fgov%5Fbc%5Fca%2FDocuments&parentview=3);
we've found a second video: [click here](https://bcgov-my.sharepoint.com/personal/ian_1_watts_gov_bc_ca/_layouts/15/stream.aspx?id=/personal/ian_1_watts_gov_bc_ca/Documents/Recordings/Provisioner+training,+part+2-20230131_134945-Meeting+Recording.mp4&referrer=OneDriveForBusiness&referrerScenario=Recommended&sw=auth)
- [x] read the documentation on Provisioner Management [here](https://github.com/bcgov-c/platform-services-docs/blob/main/provisioner/provisioner_management.md)
- [x] schedule and have a KT session with Ian
- [ ] build a KT plan for other KT sessions and what to cover for the KT

**Comment by funtigr** [comment]
We had two big KT sessions with Ian. I asked him about the further KT plans. He is busy this week but we will proceed with simple real life tasks the next week.
