### ISSUE TITLE
Product Create Page- Public Cloud

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1071]
Create the product create page for a public cloud project.

Note that a lot of the components from the private cloud page can be re used, but also custom components will need to be created. Note that we can and should re use the validation logic from the current UI where possible.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkhyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5e10104ded342e669313eaac782f85e0688c59b2/image.png)

Dod:

The UI for the create page is created and is connected to the API endpoint

**Comment by funtigr** [comment]
Unable to test because for now route leads to 404. Looks like the same bug blocking #1099.

**Comment by Kolezhanchik** [comment]
edited rotes for create button, waiting for review

**Comment by funtigr** [comment]
Now it's blocked by backend failure. Searching for contact doesn't work:
<img width="864" alt="image" src="https://github.com/bcgov/platform-services-registry/assets/43115082/58d784d8-205f-41a8-a268-26fdc5452075">

**Comment by funtigr** [comment]
Now everything works fine. 
Found a small typo - no spaces around the link:
<img width="864" alt="image" src="https://github.com/bcgov/platform-services-registry/assets/43115082/a4d633f9-fe2f-43a2-aa86-7e0faa3d3cbc">
