### ISSUE TITLE
Do a research with Public Cloud to Better Understand all the requirements

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1074]

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/1074?planning-poker) with Zenhub @alexandralloyd @Amritpal-Nijjar @calbertan @funtigr @Kolezhanchik @okanji

**Comment by Kolezhanchik** [comment]
met Public Cloud team to discuss UI and DB changes to implement User Access Management for Public Cloud changes
