### ISSUE TITLE
[new UI]new Public cloud product AWS users page

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1078]
add one more tab for public cloud product page for AWS users dashboard

**Definition of done/Acceptance Criteria**
- [x] tab with AWS roles is added and has separate route

**Comment by Kolezhanchik** [comment]
after a meeting with Public cloud team, we agreed @KhurrumBC  will provide a link to new mock up for Public user roles dashboard, which is going to be a separate page(not section) the ticket should be edited since user roles will not be a section of public cloud product page, but a separate page

**Comment by funtigr** [comment]
<img width="1482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemg2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d5df656b2069e9b964c09e5d47492f68c468be9/image.png" alt="image.png" />
