### ISSUE TITLE
Read Only Admin Role for Public Cloud

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1092]
Describe the issue: 
Comment from Olena from Oct 10, 2023:

> Creating a Ministry admin role in the Registry for private and public projects. This role will allow the user to see and edit all projects belonging to their Ministry. This role will be used by people such as Ryan Louiselle and Justin Hewitt that look after the abandoned apps that belong to their Ministry.

Definition of Done: 
GIVEN a user has been granted read-only admin role
WHEN they login to the Projects home page (public or private)
THEN they should be able to see all ministry projects for public cloud as well

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/1092?planning-poker) with Zenhub @okanji @Kolezhanchik @funtigr @Amritpal-Nijjar @junminahn

**Comment by okanji** [comment]
@funtigr , Amritpal and I went over this ticket and this functionality seems to exist in production already. Can you please re-verify this for us?

**Comment by funtigr** [comment]
@okanji 
Yes, I confirm that on Prod, with read-only-admin role I can see Public Cloud products of my ministry only.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOENhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29cafca1ee02222517ac9f532eb47b6f23bbdc7c/image.png)

At Private Cloud tab i see products of all ministries:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEdhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--416712ee244c6dbab8a63f2722ae67e84af0edd9/image.png)

**Comment by funtigr** [comment]
@okanji 
Actually I remember that when Prabhu gave us the Public Cloud products they all had CITZ ministry.
We have Public Cloud products of different ministries in the Test Env. The Prod Env has older code than the Test one so it cannot have the fix if it's not on Test. 
And on Test Env having read-only-admin role only I see Public Cloud products for different ministries:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFNiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5af930f3b1dab4d8e7741248942ecad4f9db6a3/image.png)
