### ISSUE TITLE
Update text on Public Cloud Create/Update pages

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#1096]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM01wQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a381d934a03d6cdc665e2e0a5cea91e43855b1d9/Screen%20Shot%202023-10-11%20at%202.13.14%20PM.png)

Please update the text next to the budget fields on the public cloud create/edit page as per the screeshot above.

**Comment by Iryna-Kaplun** [comment]
Ticket was completed a while ago.
