### ISSUE TITLE
Profile for New Registry UI

### ISSUE THREAD

**Issue by calbertan** [bcgov/platform-services-registry#1099]
Right now, users with no Profile Picture displays a missing picture

**Definition of done**
Have a default profile picture that shows the initials of the user

**Comment by funtigr** [comment]
Don't see the letters for now. But also projects too, maybe a backend bug:
<img width="862" alt="image" src="https://github.com/bcgov/platform-services-registry/assets/43115082/68dea898-65a7-4526-adb8-03b9af054022">

**Comment by funtigr** [comment]
For now the picture for Platform Services Test Account has 4 letters on the user picture. 
<img width="864" alt="image" src="https://github.com/bcgov/platform-services-registry/assets/43115082/22432ee1-f53a-49d7-b144-a65007c72f0a">

Though in the current registry same account has two letters which is more readable:
<img width="863" alt="image" src="https://github.com/bcgov/platform-services-registry/assets/43115082/0061cb74-447d-4cc9-b41c-4ace0c1dabfb">

**Comment by funtigr** [comment]
Now the letters are shown correctly:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFNGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd20283bb3a27a3b1d6e5b233ded07eb0f4c9789/image.png)
