### ISSUE TITLE
Update landing page with Public Cloud

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1102]
**Describe the issue**
Rewrite landing page to be inclusive of public cloud.

[Uploading... image.png]

Include the information above in the current registry: https://github.com/bcgov/platform-services-registry-web

Note: **There is no need to make this page look like the mock up design above**. The design above has already been implemented in the new UI.

Our objective is to try and include the information above in the current registry.

**Comment by funtigr** [comment]
Found a couple of visual issues here:
<img width="863" alt="image" src="https://github.com/bcgov/platform-services-registry/assets/43115082/87650e0d-6610-4b80-a182-73829026e6ed">

**Comment by Amritpal-Nijjar** [comment]
Addressed the feedback and corrected the visual issues.

**Comment by funtigr** [comment]
Above issues are fixed. The fix is pushed to Prod.
