### ISSUE TITLE
Review the test framework in KLAB

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1118]
**Description**
Review the test framework in KLAB and see if it can be expanded to include the use cases that would catch the storage issues such as the one that happened in Silver.

Silver cluster is very big compared to KLAB. When things are ok in KLAB, it's not exactly the case when this goes into Silver due to the size of the Silver cluster.

This task is a result of the postmortem discussion after the October outage on Silver cluster. 

Discuss this with Steven Barre from DXC

**DoD**

- [x] have a discussion with Steven regarding the test framework in KLAB
- [x] provide the recommendations

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/1118?planning-poker) with Zenhub @Amritpal-Nijjar @funtigr @junminahn @Kolezhanchik @okanji

**Comment by funtigr** [comment]
I had conversations with Steven and Shelly.
After call with Steven:
We have two main types of storage: netapp-file-standard and netapp-block-standard
To find the type of problem we had on Silver we could make a test that makes a pod with these types of storage.
We now have tests for KLAB in N8N and Cerberus.

After call with Shelly:
She is now at the 3-day workshop but:
We have this type of test in Cerberus already. She will grant access and make a tour in Cerberus on Monday. 
She says it would be great to make a test that deploys a sample application from scratch and check it's working. Of course with deleting it in the end.
When I get a tour in Cerberus I will think of whether it's easier to do such test in N8N or Cerberus.

For now I will go through the tests in N8N built around KLAB to observe what they are doing now.

**Comment by funtigr** [comment]
I had a Cerberus walkthrough with Shelly. She showed the current tests regarding the storage. 
The last problem with Trident and storage was too specific to make a test which will cover the case. 
Billy is now working to make a more general test for the storage.
