### ISSUE TITLE
Continuous Integration Pipeline to run build & test script

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#1123]
**Describe the issue**
We want to have a CI pipeline to run build & test script.
So that we are confident to ask peer review after checks passed.

**Definition of done**
New CI pipeline checks run on every changes on the repository.

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/1123?planning-poker) with Zenhub @Amritpal-Nijjar @calbertan @funtigr @junminahn @Kolezhanchik @okanji
