### ISSUE TITLE
Validate resend package works for sending emails created with React

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1124]
We want to use the new resend package to create email templates with React and Tailwind as this is part of our current stack. This should make our email templates more maintainable and better designed. 

We want to use this package to create email templates with React: https://resend.com/docs/send-with-nextjs 

We need to validate that this will work for us. For this ticket, create a simple email template with React and Tailwind Css and use CHES (common hosted email service) to send an email through the registry in your local deployment. If this works, then we can proceed to implement the new email templates with this package. 

Dod:
- Validate that we can use the resend package to create an email template with react 
- Test out a simple email template with CHES (common hosted email service). If this does not work then there is no point in using this package.

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/1124?planning-poker) with Zenhub @Amritpal-Nijjar @funtigr @junminahn @Kolezhanchik @okanji

**Comment by Iryna-Kaplun** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/1124?planning-poker) with Zenhub @calbertan

**Comment by junminahn** [comment]
>> https://github.com/resendlabs/react-email

**Comment by calbertan** [comment]
the resend package `react-email` works fine with CHES. They allow the creation of email templates with components along with a render() function that converts the email into html, allowing it to work with CHES. 

there is also a built in function you can run with `npm run email` which will start a build which show a preview of the email templates
