### ISSUE TITLE
Provisioning completed email template

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1127]
Create the email template for a new project request for both public and private cloud.

See the figma design: https://www.figma.com/file/llP34TwOrBUjUGey9PUu6c/Platform-Registry?type=design&node-id=1392-34439&mode=design&t=Zpv1IdLjIUgxYL38-4

The above design is for public cloud, please adapt it for private cloud as well.

We want to use this package to create email templates with React: https://resend.com/docs/send-with-nextjs 

Dod:
- Use react with tailwind to create an email template for provisioning completed for private and public cloud

**Comment by funtigr** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1lhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bdfff4bfb030e742c776d01c2b10a78e32acbad2/image.png)
