### ISSUE TITLE
Email template - Deletion

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1130]
Create the email template for the deletion of a request.

See the figma design: https://www.figma.com/file/llP34TwOrBUjUGey9PUu6c/Platform-Registry?type=design&node-id=1392-34439&mode=design&t=Zpv1IdLjIUgxYL38-4

Dod:

- [x] Project Deletion confirmation (a user will get)
- [x] Project Deletion completion (user will get once request is approved by an admin)
- [x] Project Deletion rejection (a user will get once request is rejected)

**Comment by funtigr** [comment]
Deletion Request Received:
<img width="1372" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUZOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f48002384cf5df2f325d8791d1b99d8198610d0/image.png" alt="image.png" />

Deletion Request Completed:
<img width="1366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWhOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe496e07e500c5dfda56aa266ebb264b95530ee5/image.png" alt="image.png" />

The Rejection has a common template for any request so there is no necessity to have it.
