### ISSUE TITLE
Messages delivered to NATS should be resilient

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#115]
## Story

As a system owner I would like to make sure messages sent to NATS get delivered to the destination so that I know my request is being processed.

## Description

Right now messages are delivered to NATS. These messages may or may not get delivered to a smart robot. We need to make sure that the messages are tracked in the database temporarily. For example, we can create a nats_messages table and track if the messages was sent to NATS. This should also include a smart robot acknowledging the receipt of said message at which point we can mark it as delivered.

## Done When

We can send a message with NATS down and it gets queued up and retried later. 

We can send a message to NATS when it is down, the retry gets delivered, and an acknowledgement is recieved.

**Comment by yhfreeman** [comment]
This ticket is decided as won't fix as the recent Registry sync feature seems to have resolved the same issue (which is to protect the system / db data integrity).
