### ISSUE TITLE
Create Modal public cloud 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1152]
Create modal public cloud create product page according to mock up

**Definition of done/Acceptance Criteria**
 

- [x] modal window is created appears after submit button click 
- [x] after clicking confirm button one more modal window opens

**Comment by funtigr** [comment]
After clicking the Submit button the modal window about Creation is shown:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGVpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6ad1d6a644d32203b424cb63e620de3be40b6e6/image.png)

After confirming first window the next Modal Window appears:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGlpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae43b41a3a2c9d7177eaabf0c95a854fec0cb8af/image.png)
