### ISSUE TITLE
Improve the usability of the namespace request form

### ISSUE THREAD

**Issue by lukegonis** [bcgov/platform-services-registry#120]
## Story

As a Product Owner, I am not sure what I should put in the some of the Project registry fields
I want an example or naming best practice blurb or description of what should go in project registry fields
So that I can properly submit my namespace request

## Description

-Text describing what the Platform Services team is looking for, i.e. provide an explanation what it means for an app to be a Priority app so that it will be eaiser for a PO to decide whether their app qualifies to be called a Priority app or not.
-note around special characters, abbreviations, description should be something a human can read and have a basic idea about what the project is.

## Done When

Prod registry is updated with text describing what the Platform Services team is looking for

**Comment by yhfreeman** [comment]
@mitovskaol @lukegonis Could I ask for clarifications for this ticke? We currently have a set of placeholders and a set of validations on the form UI for guiding users to submit valid data. If you are looking to just text UI components, do you know what texts need to go where? Thanks.
