### ISSUE TITLE
Test cases for CHES

### ISSUE THREAD

**Issue by calbertan** [bcgov/platform-services-registry#1206]
With the implementation of CHES, it is inconvenient to have to create a request to send an email. Create several test cases to test if CHES is properly sending emails with the React Email

Dod:

- [x] Find a way to set the email CHES sends based on the environment

- [x] Create test cases for CHES that sends out emails to designated emails

- [x] Review the Mockups in Figma matching it with the email flow to find out that every letter type is reflected

**A list of possible emails:**
**Private Cloud**
- [x] 1. Request waiting for approval for Admin. Common for all types of Requests.
- [x] 2. Create Request is received for the User
- [x] 3. Create Request is approved for the User
- [x] 4. Request is Rejected for the User. A common one for all types of Requests.
- [x] 5. Edit Request is received with Current and Requested data for the User
- [x] 6. Edit Request is Provisioned for the User
- [x] 	7. Delete Request is received for the User
- [x] 	8. Delete Request is Provisioned for the User

**Comment by funtigr** [comment]
1. Make a Request, wait for two letters for user and one for approving admin
2. Approve, wait for two letters for user
3. Make an Edit Request changing Name, Description and Ministry no letters
4. Make an Edit Request changing Contacts, wait for one letter for user
5. Make an Edit Request changing Quota, wait for one letter for user and one for approving admin
6. Repeat option 2
7. Make a Delete Request, wait for one letter for user and one for approving admin
8. Approve the Delete Request, wait for one letter for user
9. Repeat the same in Public Cloud except Quota is Account Coding and Budget
10. Check Create, Edit Quota/Account Coding/Budget and Delete request letters reach the TLs

**Comment by funtigr** [comment]
Testing this is waiting for the refactoring of the roots and then merging the changes from #1126

**Comment by funtigr** [comment]
I will make a list of all the emails we can receive and we will check them against Figma mockups. 
After they are ready I will test them during regression testing.

**Comment by funtigr** [comment]
A list of possible emails:
**Private Cloud:**
1. Request waiting for approval for Admin. Common for all types of Requests. - DONE
2. Create Request is received for the User - DONE
3. Create Request is approved for the User - DONE
4. Request is Rejected for the User. A common one for all types of Requests. - DONE
5. Edit Request is received with Current and Requested data for the User - DONE
6. Edit Request is Provisioned for the User - DONE
7. Delete Request is received for the User
8. Delete Request is Provisioned for the User

**Public Cloud:**
1. Request waiting for approval for Admin. Common for all types of Requests.
2. Create Request is received for the User
3. Create Request is approved for the User
4. Request is Rejected for the User. A common one for all types of Requests.
5. Edit Request is received with Current and Requested data for the User
6. Edit Request is Provisioned for the User
7. Delete Request is received for the User
8. Delete Request is Provisioned for the User

Adding this to the Description, continue tracking it there.
