### ISSUE TITLE
Implement nats pub sub for the new registry UI

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1219]
We use nats as a publisher-subscriber service to communicate with the provisioner. This needs to be set up for
- Private cloud
- Public cloud

It has been set up for the current registry, this implementation will be quite similar.

Dod:
- Nats messages are being sent by the registry for 
- It has been tested in our dev namespace and it does trigger the provisioner

**Comment by funtigr** [comment]
After approval of the Private Cloud product in the New Registry, no new workflows show up in the Provisioner:
After approval:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2IrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93124614675267f08d865ec564f2a460eb3264a9/image.png)
The workflows in the Test Provisioner (last one 5 days ago):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3IrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7e625802c515fdf9d9c093a8ed38f0a817d2018/image.png)
The workflows in the Prod Provisioner (last one is the aws and 3 hours ago):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3YrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d64fa0cefa81c1c5a7ab652fb18931ff67fd39a/image.png)

**Comment by funtigr** [comment]
The NATS messages from the new registry are reaching the Provisioner and the NATS message is working good now:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8b110f2acf89645c11e8afd89d7c09e0838b47a/image.png)
