### ISSUE TITLE
Mautic API doesn't add users creating new products via registry

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1240]
When a user creates new product this user is not subscribed to any of Mautic segments

**Expected behaviour**
Every time a new product(private or public) is created PO/TL should be subscribed to correspondent Mautic segment 

**Definition of done:**
After creating a new product PO/TL of this product are  subscribed to correspondent Mautic segment

**Comment by okanji** [comment]
I added mautic in the last sprint. This needs to be tested

**Comment by funtigr** [comment]
The Mautic is subscribing users using API now.
