### ISSUE TITLE
Email template for Edit Request

### ISSUE THREAD

**Issue by calbertan** [bcgov/platform-services-registry#1244]
With the new react-email, we need a new template for Edit Request emails. These emails are different in that they need to provide the edited information and display that they have changed.

examples of what the UI would look like is available at Figma:
https://www.figma.com/file/llP34TwOrBUjUGey9PUu6c/Platform-Registry?type=design&node-id=150-12785&mode=design

Dod:

- [ ] Find a way to check the differences between the old and edited information
- [ ] Turn the above into a function
- [ ] Make an Edit Request template that is able to display the Product Information alongside the changed information

**Comment by funtigr** [comment]
The same thing about the logo: it is not visible.
Also the Quota looks different:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1Q0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b4683570bfe3f58b35cbed808b71b7924bd8155/image.png)
And in Current Registry we show Current Quota in grey. It would be good to make it grey here as well.

**Comment by calbertan** [comment]
Added function that converts the quotas to better syntax, has been merged
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2dUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b78efd6322a30672094da8ec941ede937ba701e/image.png)

**Comment by funtigr** [comment]
Now the quotas are looking right, maybe we'll change the interval between title and quota itself in the future:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0lhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8213619d635ac09c43a8dab1911397ddf39baef9/image.png)
