### ISSUE TITLE
[New Registry] Decimals should be allowed in budget for Public Cloud 

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#1254]
**Description**:
In current version of registry we've added an ability to add decimal numbers in the Budget fields on Create Public Cloud page.
In the New Registry you can't submit the project if Budget fields have decimals:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEdpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d27e8c9a4856cedb153d8fb76361eb3752df9cf/image.png)

**Definition of done**:
The Products which have decimals in Budget field in New Registry are allowed to be submitted and appear in Requests Tab after submission.

**Comment by okanji** [comment]
Yes, we need to update our Prisma schema. Lets do this

**Comment by funtigr** [comment]
The decimals are now going through the validation. But the Request shows the whole numbers (screenshot 2).
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnZWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac764d69b40ece00dbb7fe58319e3a98c0a9bead/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjdWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8171acbe00c22e6cb4e9a72d451857c9fb0224c5/image.png)

**Comment by Kolezhanchik** [comment]
@funtigr it also shows empty name and description and other fields

**Comment by funtigr** [comment]
Works fine on the dev of New Registry:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm5jQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3483b9390b9e5fdbd807752af6f1d42fe1809a9/image.png)
