### ISSUE TITLE
Add additional project/namespace labels

### ISSUE THREAD

**Issue by cvarjao** [bcgov/platform-services-registry#128]
In OCP3,  I normally use labels to filter report on namespaces to IITD executives.
- `name`: This label contains the part before `-` of the namespace name (`project.metadata.name`)
- `environment`: This label contains the part after `-` of the namespace name (`project.metadata.name`)
- `mcio`: This has the org name of the MCIO accountable for the project/product/team. In the case of IITD, it is the same MCIO across all natural resource ministries.

I would consider the `name` and `environment` OpenShift project/namespace metadata that is pretty much immutable, since the actual name of the project/namespace is immutable itself. It does not change over time.

The `mcio` is business metadata, it may change over time.

**Comment by jleach** [comment]
@cvarjao We can look to adding these back. My though is it would be better to create an org administrator role in the registry and use that for reporting. Or even run some SQL agains the db. That way you, for example, could login to the registry and see all the projects and update/edit them as needed. This would include changing the PO or TC. Your thoughts?
