### ISSUE TITLE
Add callback for new registry API

### ISSUE THREAD

**Issue by IanKWatts** [bcgov/platform-services-registry#1282]
**Describe the issue**
Add a second callback from the provisioner to the registry's new API.

**Rational/Why**
The callback is used to inform the registry of the completion of a request.
* Keep the original callback for the old API endpoint
* Test the new API

**Additional Context**
The callbacks are made from GitHub Actions in each cluster's "namespaces" repo, which is where registry updates for private cloud project sets ultimately go.
Update the GitHub Action for a lab cluster (see link below).  After testing is complete, add the callback to the GitHub Action in all remaining repos.

Start with KLAB.  The lab clusters have three different workflows, one for each of the registry instances: dev, test, and prod.  Update the workflow for the environment in which you would like to test.

https://github.com/BC-Gov-PaaS-Platform-Services/platform-gitops-kamloops-klab-namespaces/tree/main/.github/workflows

At the end of the workflow, find where an SSO token is fetched from Keycloak and used to make the API call.  Add another command for the second callback.  I don't think it's necessary to use a GitHub Secret for the registry API URL, since this is a private repo and the URL is not really sensitive.  Also, once created, it's not possible to see the value of a GitHub Secret, so this will simplify future maintenance a little bit.

After successfully testing the first modification, update the other two GitHub Actions for KLAB and test them.  Once it has been verified that all instances of the registry are receiving and processing the callback, update all Actions for all other repos (except GoldDR, which is covered by the Gold cluster).

The other clusters' namespaces repos are in the same GitHub organization.  You can find them under the Repositories tab.

**Dependencies**
n/a

**Tests**
First apply the change in KLAB.  Once verified, proceed with adding the callback to all other clusters.

**Definition of done/Acceptance Criteria**
All GitHub Actions in all namespace repos have been updated, except GoldDR.
- [x] CLAB
- [x] KLAB
- [x] KLAB2
- [x] Silver
- [x] Gold
- [x] Emerald

**Comment by funtigr** [comment]
The callback is added to all the cluster repos and working:
<img width="1477" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0tBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74d02bc46c6c172b281e301acbf6eeedac4320b7/image.png" alt="image.png" />
