### ISSUE TITLE
Users should be able to edit their project profiles

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#133]
As a user of the registry, I would like to edit my project details including assigning a new technical contact and product owner. In addition to basic project edits I would like to be able to requests updates to my namespace quotas.

SEE MEETING NOTES BELOW!

**Comment by jleach** [comment]
This story will require work from Justin. His smart robots for provisioning will need to accept a new NATS message that triggers and update in GitHub (GitOps). This may require an RBAC change as well as updates to namespace metadata (labels).

**Comment by jleach** [comment]
## Meeting Notes

* Request all 3 (MEM / CPU / Storage) separately;
* Requests that are not approved then the are marked as pending; can not request going to L by clicking the button twice.
* Each namespace gets done separately for fine grande control.
* You can edit as many NS as you like, but once you hit submit you must wait for all the initial changes are completed before you can go back and do more edits. Only one open request at a time!
* Justin to outline what the new “Edit” message body;
* We’ll use two different channels for NATS messaging Edit and Request.
* We **may** setup our own NATS system for communicating with the Web clients. Olena suggested using our existing NATS.
* We need to show each option (S, M, L) and what they mean with respect to how much storage, cpu and ram comes with each one.
* Olena would like to see some sort of mockups of what the UI and workflow looks like.
* Justin to schedule some time with Shawn / Yuhan to show them the robots.
* Goal for the sprint is “Edit” for all details including PO, TC and Update the quota.
* The teams should be able to edit everything they originally entered.
* The only one that should not be editable ATM is the project name; it is being used as a unique key at the moment.
* Both the TC and PO will be both give admin access to the cluster; this info as well as product info will be propagated to the cluster.
* Future feature is to ask ppl to get RC ID so that Steven can use that to collect information.

**Comment by sbathgate** [comment]
The ability to Edit Contact Details and Project Descriptions has been merged and proven functional in Prod (Silver).
