### ISSUE TITLE
Update provisioner for Vault access

### ISSUE THREAD

**Issue by IanKWatts** [bcgov/platform-services-registry#1335]
**Describe the issue**
Currently, only technical leads are configured with access to Vault.  Update it so that product owners are also given access.

**Rational/Why**
Although we do try to avoid creating unnecessary user accounts in Vault due to license costs, the actual accounts are not created unless or until a user logs in, so this change will not immediately create a lot of new user accounts that will count towards our license.  Users have requested Vault access for product owners.

**Additional Context**
- Create a branch of the devops-fulfillment-pipeline repo for your work
https://github.com/bcgov-c/devops-fulfillment-pipeline
- Vault access is managed by way of a Terraform file.  The user list is generated from a query here:
https://github.com/bcgov-c/devops-fulfillment-pipeline/blob/master/roles/tenant/defaults/main.yaml#L21
- Change 'vault_editors_query' to be the same as 'admin_query'
- Commit and push changes to the repo
- Update the BuildConfig for the app-provisioner image using your new branch and setting the image tag to `testing`
- After building, update the Test provisioner sensor for a cluster where you have a Test project set that has different contacts for product owner and technical lead.  Change the app-provisioner image tag to `testing`
- Submit a reprovisioning request in the Test registry for your project set
- Verify that the workflow completes successfully and that the resulting Terraform file contains both the product owner and technical lead(s).  You can find that file in this repo:
https://github.com/bcgov-c/terraform-vault-lab
- Once you are satisfied that the updated image is working properly, tag your new image with a new version (increment the minor version).  See this doc for details:
https://github.com/bcgov-c/platform-services-docs/blob/main/provisioner/provisioner_management.md#update-the-app-provisioner-image
- If you modified the main BuildConfig for app-provisioner, update it again and reset the source branch to `master`
- Merge your branch into `master`
- Update the private cloud prod sensor for each cluster to use the new version number.
- Commit and push the change to the provisioner gitops repo and sync the prod app in argocd.
https://gitops-shared.apps.silver.devops.gov.bc.ca/applications/openshift-bcgov-gitops-shared/eb6118-provisioner-prod?view=tree&resource=

**Dependencies**
- Contact Ian if you have any questions or to verify the work.

**Tests**
- Done using a test project set in a lab cluster

**Definition of done/Acceptance Criteria**
- [ ] Updated image has been tested in a lab using the Test provisioner
- [ ] New image has been tagged
- [ ] Prod private cloud sensor has been updated via argocd

**Comment by IanKWatts** [comment]
FYI, @ShellyXueHan

**Comment by IanKWatts** [comment]
@funtigr This task is very similar to the test update we did as a group recently.  The only real change to the image is changing the query that is used to generate the user list.  Let me know if you have any questions.  Please contact Shelly when this has been completed.

**Comment by funtigr** [comment]
After talking to Luke, it was decided to cancel this task, because we try to not increase the number of Vault accounts.
