### ISSUE TITLE
Email Title with Env Prefix

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#1337]
To denote the originating environment for emails sent from the application, we intend to incorporate a prefix in the email titles. For instance:

- [Dev] New Request
- [Test] Request Updated

**Comment by funtigr** [comment]
Now we have the Prefixes for the emails coming from lower instances of New UI:
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1oxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1097ac2edd19508778fbdb38d991334bcf7e4bf6/image.png" alt="image.png" />
