### ISSUE TITLE
[Current Registry] Fix Download of the Products functionality - Check if this is still an issue after the New UI Go-Life

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#1338]
The Download of the .csv files on the Products page doesn't work as expected now. 

1. If user filters out the Products by **cluster** and/or **ministry** and tries to click the download button he gets an error:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNERWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66c708acef1533d973dabd81fddddcc65dc55247/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFRWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd0a233d2c2c66f9e3bb0f0484a892ec690d2ff7/image.png)

2. If user first clicks Download button and then starts unchecking some of the fields to not include them in the downloaded document the download starts on every click. So If he needs to uncheck 5 fields the instant download of 5 versions of documents is made.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGpWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ecd911b687b4f83832a18950ecbc49b7a83ab5c/image.png)

**Definition of Done**:
1. The .csv download is possible when products are filtered out by **cluster** and/or **ministry**
2. If user first clicks Download button and then starts unchecking some of the fields to not include them the download is not started until user clicks Download button again.

**Comment by Iryna-Kaplun** [comment]
The team will wait for the New UI to be released and then check if this bug can be replicated in the New UI.

**Comment by Iryna-Kaplun** [comment]
this bug is fixed the new UI. When the new UI is released, Artem will check if this is fixed and close this ticket as a cancelled one.
