### ISSUE TITLE
Comment modal for Edit Request

### ISSUE THREAD

**Issue by calbertan** [bcgov/platform-services-registry#1346]
When creating an edit request, users should be able to provide a reasoning to why they want to edit the request. This will make it easier for the admins to understand the reasons behind the change. This goes both ways, when admins want to reject a request, and users should know why their request got rejected.

**Dod**
Create a comment modal that pops up upon creating/rejecting an edit request that gets passed to the emails. The comment modal should look like the Figma mock up
https://www.figma.com/file/llP34TwOrBUjUGey9PUu6c/Platform-Registry?type=design&node-id=821-31889&mode=design

**Comment by funtigr** [comment]
The Comment Modal is showing up on Rejection. After leaving a comment it is shown in the Rejection Email:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1FOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79e30ca41ef71bf5be1ed5bb733dfab9c323b82c/image.png)
