### ISSUE TITLE
Deploy the registry to the test environment and validate the documentation is correct

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#135]
## 

As a team member I would like to make sure that the documentation is correct and that at least one other team member is capable of deploying the entire registry.

## Done When

The entire registry is deployed and working in an HA configuration to the test namespace.

**Comment by yhfreeman** [comment]
Registry has been deployed to test environment https://registry-web-test-platform-registry-test.apps.silver.devops.gov.bc.ca/dashboard, and the documentation is working as expected.

Please note the Registry test instance is still connected to SSO dev instance.
