### ISSUE TITLE
Visual bugs in New Registry UI

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#1353]
1. No space on the product page in Quota section:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0hqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5857a2ddf8020217389b65ab8c01ea28553b36c5/image.png)

2. No space on the Public Cloud create page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9d8ffd2c822804060d88dbcb05f5e8adfd8451c/image.png)

3. Missing "in" on Public Cloud Requests page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGJqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea900d0e33778a3b6951facb562fc24ed8331a3b/image.png)

4. "toto" typo on Public Cloud Create page. Also we need to add the persons responsible for the initial meetings for Public Cloud:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTdqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bedde6f1e493a9ef9f6750a4821650657395596b/image.png)

5. "descriptibe" typo on Public Cloud Create page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS9qQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5fac9a7b84671a86c7ec59d25fa2c77a09d4aa6a/image.png)
Moved Public Cloud part of this option to the option 26 in epic #1481

6. The mentioning of GCP. We don't provide it yet, so maybe we shouldn't mention it:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejdqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--428f575b0bed3a94191c82172f6df8a5ca396be7/image.png)

7. Placeholder mentions "project owner" though the writing over the window says "product owner". Olena wanted us to use "product". Screenshot in the next item.

8. Placeholder for TLs says: "Search project owner's IDIR email address". Needs to be "Search technical lead's IDIR email address":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGJqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd9081a57cb8225e1602f0ed7c5aa734d2a30f78/image.png)

9. Options 4-8 are also observed on the Public Cloud Product page.

10. Public Cloud Product page has all the writings about creation which may be confusing. For example the upper one that says to have an alignment meeting.
Moved this option to the option 25 in epic #1481

11. On Private Cloud we mention Sal. Unfortunately the information about meeting with him will soon be non-relevant. So we need to change the wording to more neutral or add new responsible persons.

12. On Private Cloud Create page under the Cluster dropdown we need at least add a comma:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmJqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--671cb2dba95fba749b480936f422d404baebdc24/image.png)
 
13. On Private Cloud Product page above Quotas all four links are pointing nowhere and have suffix "-prod":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2JqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20337732e3b65b32301d3d16d87f25c4cd3e70d0/image.png)

14. In the Products Tabs the names of Technical Leads have comma in the wrong place:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25qQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f802835508ab31191c8b1aa3cf2630cb6fc5ebc9/image.png)

**************************************************************************************************************
25. When the Product is approved, the description on Product Page has wording about onboarding process which in this case is already passed (issue ~moved~ from option 10 #1353).
26. The name field on Public Cloud creation page has no description of allowed/non-allowed symbols (issue ~moved~ from option 5 #1353).

**Comment by Amritpal-Nijjar** [comment]
1) fixed spacing
2) fixed spacing between the hyperlink
3) added "in" to the sentence
4) the email link was commented out, removed the comment, is this email supposed to be updated ? (cloud.pathfinder@gov.bc.ca)
5) corrected spelling of "descriptive"
6) removed info in brackets 
7) project is now "product"
8) corrected placeholders with their correct labels respectively
9) corrected typos and updated email to platformservicesteam@gov.bc.ca
10) not sure of the changes that need to be made here, the page matches the current figma mockups
11) all mentions of Sal now removed, and instead has the respective email listed
12) added a comma for clarity
13) corrected the suffixes, changed link to <span> 
14) table rework negates this issue ?

**Comment by funtigr** [comment]
1. No space on the product page in Quota section: FIXED
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejlOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--937f83a4cb6587a0e3ed8b6eecda1c4a9cbeba2b/image.png" alt="image.png" />

2. No space on the Public Cloud create page: FIXED
<img width="1482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU5PQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea043286109c29a57e976fab48eb4ca3c4b70141/image.png" alt="image.png" />

3. Missing "in" on Public Cloud Requests page: FIXED
<img width="1477" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVJPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2e09321a9cf71b125d29495a9ecf763ce4b907f/image.png" alt="image.png" />

4. "toto" typo on Public Cloud Create page. Also we need to add the persons responsible for the initial meetings for Public Cloud: FIXED
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVZPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff5476ff8f45e953c352421a35b82437fba273ae/image.png" alt="image.png" />

5. "descriptibe" typo on Public Cloud Create page: NO WRITING for Public Cloud can be considered FIXED for Private Cloud
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWxPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01bc7464f4e4ac30315452b170c7bee8bb5167c3/image.png" alt="image.png" />
<img width="1724" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0JUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dee6b55c5cdd4697eb8b5d8a235f0251aac87b50/image.png" alt="image.png" />

6. The mentioning of GCP. We don't provide it yet, so maybe we shouldn't mention it: FIXED
<img width="1481" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXRUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd38150348e9c366663323e270d9a969090e4515/image.png" alt="image.png" />
Private Cloud issue about visibility of Lab clusters for users is discussed in second part of this task: https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/1514

7. Placeholder mentions "project owner" though the writing over the window says "product owner". Olena wanted us to use "product". Screenshot in the next item: FIXED
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTVUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a9b2c3ef1fc8b9644f06869edd7d6d568e690dd/image.png" alt="image.png" />

8. Placeholder for TLs says: "Search project owner's IDIR email address". Needs to be "Search technical lead's IDIR email address": FIXED
<img width="1482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkZUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20530afd394760abb64906cf665662ca70106087/image.png" alt="image.png" />

9. Options 4-8 are also observed on both Public/Private Cloud Product page: FIXED
<img width="1487" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3hUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--043485519f69a5428104251edbb974247b752efc/image.png" alt="image.png" />
Private Cloud issue about visibility of Lab clusters for users is discussed in second part of this task: https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/1514

10. Public Cloud Product page has all the writings about creation which may be confusing. For example the upper one that says to have an alignment meeting:
The products that are approved have a writing about the onboarding meeting.

11. On Private Cloud we mention Sal. Unfortunately the information about meeting with him will soon be non-relevant. So we need to change the wording to more neutral or add new responsible persons: FIXED
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1pUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58e7d754324ea13e4779f82d116631c273b45503/image.png" alt="image.png" />

12. On Private Cloud Create page under the Cluster dropdown we need at least add a comma: FIXED
<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2RUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f12e7a12ad94052d9da985c18dab818c28e610e4/image.png" alt="image.png" />

13. On Private Cloud Product page above Quotas all four links are pointing nowhere and have suffix "-prod": FIXED, no links yet, they are added in terms of this epic, in item 23:
https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/1481
<img width="1481" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8d75b527c0c80c7f6ff26490b4ae7c091d462de/image.png" alt="image.png" />

14. In the Products Tabs the names of Technical Leads have comma in the wrong place: FIXED
<img width="1483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3RUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cbb1de6c547e30fb4e455f1f4536d00508629f3/image.png" alt="image.png" />

**Comment by Amritpal-Nijjar** [comment]
1) The text that references onboarding is now **only** visible on the `create` page
2) The public cloud create page now has clarifying text under the `Enter Product Name` box
