### ISSUE TITLE
Update the uptime sensor for when new UI is launched

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1390]
The current sensor for the current registry is working as intended, although it does not have the best implementation and is prone to breaking.

We can avoid the issue of the sensor breaking with a more robust/appropriate check.

Transactional vs HTTP GET ?

Talk to Billy when updating the sensor

-DOD:

- [ ] Successfully implemented a new sensor for the New UI that is not as prone to breaking
- [ ] Internally document the sensor for future reference

**Comment by funtigr** [comment]
We decided to have a discussion later. Maybe add Terraform script to manage it.
