### ISSUE TITLE
Implement a CSV download for Private Cloud [New UI]

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1397]
We used to have csv download in the current Registry but this feature is not availbale in the new UI and needs to be added for Private and Public Clouds. 

**Technical details:** 
1. name the route to GET `/api/private-cloud/download`
2. acceptable query params are:
- search (optional)
- cluster (array, at least one)
3. add validation with zod
4. add security with user's session

**DoD:**

- [x] csv download is implemented ~without~ with filtering first 
~- [ ] create a new ticket for adding filtering feature for filtering cvs download~

**Comment by funtigr** [comment]
The Download now works for Private Cloud. 
There is an ability to Download the whole list of Products, the list filtered by cluster or/and ministry.
<img width="1287" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUE4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc9ad204060491c1f6f24f463751f812dadec6db/image.png" alt="image.png" />
