### ISSUE TITLE
Add additional detail to the provisioning email message

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#141]
## Story

As a PO or TC, I would like more detail on what happens next after my namespace set is provisioned.

## Description

We're getting some questions about who is granted access to a namespace after its provisioned. It would be good if the final email that is sent, once a namespace set is provisioned, would include:

1) The cluster URL;
2) The list of namespaces that were just created;
3) Who was granted admin access.

## Done When

The email sent out contains 1-3 above.

**Comment by sbathgate** [comment]
Duplicate of Issue #273
