### ISSUE TITLE
[Current Registry][Olena's Request] Implement return to the paginated page on clicking back from the Product Page

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#1416]
**Description**:
Now if user is at non-first page of pagination in Public Cloud and clicks into the Product and then clicks back, he is returned to the first page of pagination.
We need to implement a retain feature: if the user clicks back he must be returned to the same page of pagination with the same number of rows. 

**DoD**: 
**Given** the user is in Public Cloud
**And** the user is at non-first page of pagination
**And** the user is using "Number of Rows" feature
**And** the user clicks into a Product
**When** the user clicks "back" button (on the Screenshot)
**Then** he is returned to the same page of pagination
**And** with the same number of rows

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21cb84a78b0683aec2f052727ac9f535f6085a87/image.png)

**Comment by Iryna-Kaplun** [comment]
Completed in the new UI
