### ISSUE TITLE
Zero projects are downloaded into a csv when zero projects are displayed to the user. [New UI]

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1441]
Wait. Priority: L. Size: L/M

**Describe the bug/ Actual behaviour**
When a user searches a term and nothing matches we are displayed zero projects, and when pressing the download button we get a download for a csv that has zero projects

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to private cloud projects tab
2. Enter a search term that returns zero projects
3. Click the download button
4. Observe that download has taken place, and that the file contains zero projects and only the category labels

**Expected behaviour**
A download should not occur when there are no projects displayed to the user, and instead to show an error.

**Definition of done:**

- [x] Create a check for when no projects are being displayed and prevent download

- [x] Show the user an error as to why the download was prevented

**Comment by funtigr** [comment]
Now if no products are visible for the user the Click of Download button shows the special error:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL09BQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08f9fa18674927dde7d7a5e5cece028fe6369bdb/image.png" alt="image.png" />
