### ISSUE TITLE
Project descriptions are displayed in the "Name" column [New UI]

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1444]
**Description of the bug**
The projects listed show the description in place of the name, and thus no names of the projects are seen. Search terms for something in the name still works.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Private or Public cloud products
2. Observe that project descriptions are in the "Name" section

**Expected behaviour**
The names of the products should be displayed in the "Name" column

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce61461ee08177e06f88214118dd4fe217dd17e3/Screenshot%202023-11-29%20at%2010.24.01%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec29c1864f00f6a220a2c1b657c9c60cc2559b44/Screenshot%202023-11-29%20at%2010.24.15%20PM.png)

**Definition of done:**

- [ ] Project names are correctly displayed in the "Name" column

**Comment by okanji** [comment]
We have removed the description form the table
