### ISSUE TITLE
Correctly interface the download button to the csv export route for Public Cloud [New UI]

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1451]
**Describe the issue**
Once the api route is created and confirmed to be working correctly, we can then connect it to the front end of the application. 

**Rational/Why**
There may be some error handling to deal with, for example we don't want to download a csv if there are currently no projects displayed.

**Tests**
Test that the correct csv is being downloaded, and that errors are being handled properly. (No projects displayed = error cannot download 0 projects)

**Definition of done/Acceptance Criteria**

- [x] - Confirm that the button is downloading the correct csv data for Public cloud
- [x] - Error is being displayed gracefully when there are zero projects being displayed and the users attempts to download a csv

**Comment by funtigr** [comment]
Clicking Export on Public Cloud page leads to a public-cloud url and shows error if no projects are available.
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5616dcf2802a76a0aa7e172dc5e8eadcfa17aab8/image.png" alt="image.png" />
