### ISSUE TITLE
Create delete project ui 

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1452]
Each project should have a button to delete the project. This should open up a modal with some confirmation input and a button to submit a delete request.

See the current registry for an overview of the UI 

**This ticket is not a mandatory one before Go-Life for New UI**

Dod: 

- [x] Public cloud delete is available
- [x] Private cloud delete is available

**Comment by funtigr** [comment]
Now we have the deletion in new UI:
Private Cloud: 
<img width="1470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4ab9d35bf253187f78d1367d4ebfb8d27cc55d5/image.png" alt="image.png" />

Public Cloud:
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1hPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6b5d50095a21ae3fe73f8a11e0811308615bfe6/image.png" alt="image.png" />
