### ISSUE TITLE
The regisry API should ensure that messages are delivered to the NATS

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#146]
## Story

As a user, I want to be sure that my request is picked up by a "smart robot" and processed.

## Description

If NATS is down the registry API may not re-connect or it may not guarantee that a message is delivered to NATS. As part of this story we would like to be sure that message are queued up by the API and only removed from the queue when they are delivered to NATS. Also, the queue mechanics should ensure that failed messages are retried until delivered and, that if a Pod is terminated the message delivery will be retried ones the pod restarts (ensure its not lost when a pod restarts).

## Done When

The API will start and operate normally even when NATS is down;
The API will re-connect to NATS if the service disappears and returns later;
While the API is unable to contact NATS requests are persistently queued for later delivery.

**Comment by jleach** [comment]
@sbathgate Are you able to put an estimate on this issue. Thx.

**Comment by yhfreeman** [comment]
Hi @j-pye @sbathgate do you think the issue which this ticket seems to address is indeed resolved by the recent sync feature? If so, shall we close it? Thanks.

**Comment by sbathgate** [comment]
Hrm, I don't know if this would be entirely the same thing. The sync capability would resolve errors that result from this issue, but I'm not sure if it would make sense to also have this so we don't have to run a sync if there is ever occasions the NATS message doesn't go through? Due to the sync i feel it is a lower priority issue though.

**Comment by j-pye** [comment]
I'd agree on this being a low priority. The sync does cover this. However, the sync has not been put on an automated schedule yet. (One of the tickets I plan to add to the tech debt sprint goal this sprint)

We should revisit this later but for now I'm fine with the NATS message being fire and forget whether the NATS service is up or not. As long as the request is still written to the DB whether NATS is available or not.

**Comment by yhfreeman** [comment]
Sounds good @sbathgate @j-pye - low priority it is.
