### ISSUE TITLE
Find out what clusters should only be able to used by an admin and apply that to the registry

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1460]
There may be a few clusters that should not be accessible to a regular user.

Dod:

- [ ] Find out what these are
- [ ] Make sure these clusters do not get shown in the cluster select component

**Comment by Amritpal-Nijjar** [comment]
@okanji Just need a quick clarification regarding this ticket. The title mentions `admin`, but the description mentions `regular user`. Do we want to confirm what clusters a **regular user should see and access** or confirm what clusters an **admin should see and access ?**
