### ISSUE TITLE
Create go live strategy

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1462]
When we are fully ready to go live, how should we do this? Consider these points

- [x] Data migration
- [x] Down time - ticket #1390 assigned to Amritpal 
- [x] Communication with community - connect with Pilar to work on drafting an announcement/email. In addition, we can message in the RC channels about this. Ticket [#4528](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/4528)
- [x] Network certificate - ask Billy about this
- [x] Possible need to revert back to the current registry
- [x] Env. variables

Dod:

- [ ] Create this plan and use if for going live

**Comment by funtigr** [comment]
About the SSL certificate:
"It should be fine, ssl tied to route/domain.
But I 'd recommand you guys copy the the cert and its key to somewhere else, just in case"
The second sentence is about backup:
"yes, even copy to local would be a good backup stratagy
but we have vault right?"

**Comment by funtigr** [comment]
Checklist itself: https://docs.google.com/document/d/1WVrYN2pGtkrN-afxQMUdXS8cRVfb9w3--t1JEVEF6Nw/edit
