### ISSUE TITLE
Create UI AWS User Roles Dashboard/Admin

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1463]
add dashboard with admin aws-roles + current project PO/TLs to public use roles Tab
Definition of done: 

- [x] dashboard filled admin aws-roles + current project PO/TLs

**Comment by funtigr** [comment]
The dashboard is in place. 
The PO and TLs are admins by default. 
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0dVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc8d521bf7ee92e90894a9c8edbd3a8eae6cbe0e/image.png" alt="image.png" />
