### ISSUE TITLE
New UI user testing

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1464]
When we are ready, we need to test the new registry with internal users and select real users.

Artem will reach out to the team members from the private and public clouds and ask to the end to end testing of the new UI before the go-life. 
Schedule 2 separate sessions for the New UI testing with private and public cloud users (team members). 

Dod:
- Create a strategy for this 
- thorough end to end testing with internal private and public cloud teams
- capture the feedback, bugs and ideas from the users
- 

Feedback from Max:
1. When I navigate to a different page and back my changes are erased. Don’t think this is a big deal, but it becomes an issue when links don’t open in new tabs (like the cost calculator link mentioned below).
2. There is a “tool tip” question mark by the monthly spend input boxes that I would expect to have some sort of pop up when I hover over it or click it, but it doesn’t.
3. There is a note that says “There will be a base charge of CAD 400 to 600 per month for each project set created” however the default billing estimation is 200 (unitless). I think a change here would be adding a USD unit to the billing estimation boxes, or changing the note to be in USD as well. It’s slightly confusing as it is.
4. The arrows on the input boxes don’t make a lot of sense as they increment by cents, and these are estimates.
5. The link to the cost calculator is wrong, should be https://calculator.aws/#/. This should also open in a new tab so that the form entries aren’t erased.
6. I think that when an entry is not accepted the specific box that is wrong would be highlighted. I found entering incorrect account codes it would not tell me specifically what was wrong, only that it was wrong
7. All the modal stuff looks and feels good but at the end I click “back to dashboard” or something and I get a 404 on this page https://dev-pltsvc.apps.silver.devops.gov.bc.ca/public-cloud/requests
8. Just one tidbit here, is that when I have two technical leads the second box is not expanded when I am editing, I have to click “add secondary technical lead” to see the second technical lead. Everything else looks good, other than some of the same stuff mentioned above.
9. I get a 404 on the export button for the public cloud, which doesn’t seem to be an issue on the private cloud side. It’s on a GET request to this endpoint: https://dev-pltsvc.apps.silver.devops.gov.bc.ca/api/public-cloud/allprojects?

Feedback from Prabhu:
1. For the base costs in the new project section we need to specify that the costs taken are in USD 
2. Restricting special characters for some feilds is a necessary requirement
3. Same for the account coding as it should just be numbers and letters but the UI is accepting special characters
4. The inprogress tab is a bit confusing, Admins would see all the requests but PO’s would see the requests associated with just their project set ?
5. Export functionality is doesn’t seem to be working

**Comment by funtigr** [comment]
I contacted Max and Prabhu on Public Cloud side and Jason Leach on general side. 
Max and Prabhu have already provided their feedback and we fixed most of the stuff with Oamar.
The links to the documents:
For Prabhu:
https://docs.google.com/document/d/17G3hC4Mqnu7YmGhIY8fVLFhQNm2r4W6fKpRrWsWD2NM/edit

For Max:
https://docs.google.com/document/d/1wmjXHcdo5MDq202U8fQKlFn6q5SYbw3D2OMa77FEX2I/edit?usp=sharing 

For Iryna:
https://docs.google.com/document/d/1wOa33bNWK_yZlmgpRre5IKoBizoOQpoidu4kzqN66k0/edit?usp=sharing 

For Jason Leach:
https://docs.google.com/document/d/1pEtdkVHDxMB_M3xndWwVOxCUs0epQ1-dE-kx_g5pb8I/edit?usp=sharing

**Comment by funtigr** [comment]
Based on received feedback we've added new bugs to the epic: https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/1481
