### ISSUE TITLE
Add filter toggle to show/hide inactive projects

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1466]
We only show active projects in the registry. It would be nice to add a filter toggle to also show the inactive projects (projects that have been deleted).

This will be especially helpful for our admins that export this data from the registry.

**Comment by funtigr** [comment]
Toggle "Show Pending only" is off:
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5cab54c9625ab9a9fa32f93be994bbd166a4db1e/image.png" alt="image.png" />

Toggle "Show Pending only" is on:
<img width="1477" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEZTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8a67dfd4512e54097ae27b84a8919db77b9e9fa/image.png" alt="image.png" />
