### ISSUE TITLE
Convert All Private Cloud Email Templates to Public Cloud 

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1469]
DoD: 

- [x] review all private cloud email templates and confirm what email templates will be converted to public cloud
- [x] all public cloud email templates are created

**Comment by funtigr** [comment]
Overall this work is done. 
Adding issues from this one to a new Final Touch ticket: https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/1680
