### ISSUE TITLE
3. Logo is leading to the Private Cloud products page even on the Public Cloud tab

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1509]
**Describe the bug/ Actual behaviour**
Logo is leading to the Private Cloud products page even on the Public Cloud tab. - It would be nice to do before go-live. Priority: M. Size: S. Assignee: Zhanna

**Definition of done:**
Bug is fixed and software behaves as expected.

**Comment by funtigr** [comment]
Now we have a back button on the Product Page, Request Page and Edit Page. So the logo wouldn't be clicked that much and the task looses it's priority.
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0p6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8704213dde21deb9dc798ded10cfd4e612849f4b/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Now the logo leads to Private Cloud from any Private Cloud page and to Public Cloud from any Public Cloud page.
