### ISSUE TITLE
Empty List “Request a New Project Set” button in Public Cloud leads to creation of Private Cloud Product

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1510]
**Describe the bug/ Actual behaviour**
Empty List “Request a New Project Set” button in Public Cloud leads to creation of Private Cloud Product. - Urgent. Priority: H. Size: S. Assignee: Oamar

**Definition of done:**
Bug is fixed and software behaves as expected.

**Comment by funtigr** [comment]
Now empty List “Request a New Project Set” button in Public Cloud leads to creation of Public Cloud Product:
[Uploading... image.png]
