### ISSUE TITLE
 Public Cloud Filters have Clusters in them

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1511]
**Describe the bug/ Actual behaviour**
 Public Cloud Filters have Clusters in them. - Urgent. Priority: H. Size: S. Assignee: Zhanna

**Definition of done:**
Bug is fixed and software behaves as expected.

**Comment by funtigr** [comment]
Now we have providers in the filters for Public Cloud:
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkpiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dec62a71b1b8802386e85493cb1c5f114eac9077/image.png" alt="image.png" />
The filter works for filtering out the AWS products. Expectedly, nothing is shown when choosing Google.
