### ISSUE TITLE
Both Modal windows after Submit in Private Cloud show the information about the Public Cloud

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1512]
**Describe the bug/ Actual behaviour**
Both Modal windows after Submit in Private Cloud show the information about the Public Cloud. - Urgent. Priority: H, Size: S. Assignee: Christopher

**Definition of done:**
Bug is fixed and software behaves as expected.

**Comment by funtigr** [comment]
I see Private Cloud info in Modal Window 1:
<img width="1478" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXhCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f94b9ae378ea95f944b69ff1281df5e9de56fe9d/image.png" alt="image.png" />
However, I see wrong email in Modal Window 2:
<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aabe0341c9178d2a8733df762ad8c8b143f80485/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Now second modal window is fixed:
<img width="1487" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelZDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9bf5d1306325c0417ef594b7900847dbc2285542/image.png" alt="image.png" />
The Public Cloud shows Public Cloud info.

**Comment by funtigr** [comment]
@calbertan Sorry, opening it again. I found that info about Public Cloud is shown on Submit of Edit Request as well.
