### ISSUE TITLE
The filter on Requests and Product tabs lacks two clusters. & As a User I see KLAB cluster.

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1514]
**Describe the bug/ Actual behaviour**
epic bug #8: As a User I see KLAB, KLAB2 and CLAB cluster. - Urgent. Priority: H, Size: S.Assignee: Zhanna 

Zhanna to clarify with Shelly if the users should these those lab clusters. 

**Definition of done:**
Bug is fixed and software behaves as expected.

**Comment by Kolezhanchik** [comment]
I can see full lists of clusters' names for "user" role in current registry:
<img width="863" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2a77315f77d88b6107abaf12edc048e08ddc1c1/image.png" alt="image.png" />
besides, there is phrase in Figma mockup and new UI  "Select your cluster, select CLAB or KLAB for testing purposes" which mean KLAB and CLAB are available for a "user" role
<img width="1155" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHRPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--492c92d7c03a38b0635c3e0de929acfc28cd0f9d/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
blocked, since can't get an answer if we need to keep it as it is in current registry or not

**Comment by funtigr** [comment]
Now the clusters visible for user are only non-lab clusters:
<img width="1473" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzJBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6279f61b7a27adff2d77f24a12b2d35f0ae5eefc/image.png" alt="image.png" />
No mention of LAB clusters is visible under clusters dropdown:
<img width="1483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKytBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f708a1be55a4ee802f374f34496d300559332ae/image.png" alt="image.png" />
