### ISSUE TITLE
Add info into the footer

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1515]
**Describe the bug/ Actual behaviour**
We have a footer but none of the links go anywhere. We need to put info into the footer. Find what should go into the footer and add it there - Urgent. Priority: H. Size: S/M. Assignee: Amritpal 

**Definition of done:**
Bug is fixed and software behaves as expected.

**Comment by funtigr** [comment]
Now we have 6 links in the footer:
Disclaimer,
Privacy,
Accessibility,
Copyright,
Contact Us,
Report a bug/Request a feature
<img width="1478" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmxTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bcbdeb05a8fbae54cdafefd1c3b86f76ab030633/image.png" alt="image.png" />
