### ISSUE TITLE
Project Registry Extract Improvements

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#152]
As a Platform Product Owner, I need to be able to extract a list of projects in the Silver Cluster via the Project Registry UI in an Excel format.

the report should include
- only provisioned projects (no archived or pending)
- all the fields present on the project request submission form + created date and last updated date  as DD-MM-YYYY HH:MM + last updated by user (user IDIR)

**Comment by yhfreeman** [comment]
**released on the registry-web-platform-registry-prod silver cluster: November 25, 2020
