### ISSUE TITLE
Filtering Projects on the Dashboard

### ISSUE THREAD

**Issue by juhewitt** [bcgov/platform-services-registry#155]
**Describe the issue**
As a user, if I have many projects to view on the dashboard, I need to be able to filter down to view a smaller amount.

**Additional context**
The tiles view can be quite engaging and useful, however if a user has many projects, for example an administrator or CIO that requires to see all of the projects for a sector, they need to be able to filter by types of metadata.  This could be the project owner, sector/ministry, technical contact, or project title.  Possible solutions to consider, include React search filter & filtering by dropdown of metadata, such as project owner, technical lead etc. 

Code references for ideas:
[Search Filter with React js - Medium.com](https://medium.com/crobyer/search-filter-with-react-js-88986c644ed5)
[React For Everyone #14 - Building A Search Filter](https://youtu.be/OlVkYnVXPl0)

Design comp for example
![filter ideas.png](https://images.zenhubusercontent.com/5d658f800f25370001090f16/2734adcf-c48b-4975-a30d-fb6a740c54b0)

Gov Design System Usage
[Text Input](https://developer.gov.bc.ca/Design-System/Text-Input)
[Dropdown](https://developer.gov.bc.ca/Design-System/Dropdown)

**Definition of done**
A user is able to filter the dashboard to only return projects they are interested in.

**Comment by sbathgate** [comment]
This can be achieved on the new Table view using: https://react-table.tanstack.com/docs/examples/filtering
