### ISSUE TITLE
Tab Title Image (favicon)

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1553]
**Describe the issue**
Currently the tab image is showing the default black circle with a white triangle inside it. We want to instead have the logo that represents the registry properly.

**Rational/Why**
Before launching the new UI this needs to be done 

**Definition of done/Acceptance Criteria**

- [x] A logo image is properly displayed in the browser tab right next to the title before the launch of the new UI

**Comment by Amritpal-Nijjar** [comment]
<img width="32" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--427d0ee8cbbcd520c6d989f499b0f5e4e1509c2f/favicon-32x32.png" alt="favicon-32x32.png" />

**Comment by Amritpal-Nijjar** [comment]
<img width="32" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUZPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e944cddf8d91a2a6571b41353c006fddfda8abcb/favicon-32x32.png" alt="favicon-32x32.png" />

**Comment by funtigr** [comment]
<img width="1411" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTlTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b324aa42ff81b704255ae0da8a6f367763b2e726/image.png" alt="image.png" />
