### ISSUE TITLE
22. If Admin rejects the Request he sees a Modal Window for the Request Creation submitted successfully 

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1623]

**Comment by Amritpal-Nijjar** [comment]
Rejecting a private cloud project: <img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlYvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9cf3475f713491b5c5e780bbf584df8894aa995/Screenshot%202023-12-21%20at%2010.42.40%20AM.png" alt="Screenshot 2023-12-21 at 10.42.40 AM.png" />

**Comment by Amritpal-Nijjar** [comment]
Rejecting a public cloud project: <img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0YvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85c508a69df2734419734e6e7de13a8c369fe095/Screenshot%202023-12-21%20at%2010.47.21%20AM.png" alt="Screenshot 2023-12-21 at 10.47.21 AM.png" />
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ovQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--caf0e7ceb35e999f10fe36e83830380083e0fa79/Screenshot%202023-12-21%20at%2010.48.31%20AM.png" alt="Screenshot 2023-12-21 at 10.48.31 AM.png" />

**Comment by Amritpal-Nijjar** [comment]
Corrected:
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd21BQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da95b930109021ac3796240746d731eab5508a19/Screenshot%202023-12-21%20at%201.25.58%20PM.png" alt="Screenshot 2023-12-21 at 1.25.58 PM.png" />

**Comment by Amritpal-Nijjar** [comment]
Note: @funtigr I think that the emails are not correctly capturing whatever was inputted into the text box, something worth double checking. As the emails I received when testing did not have my input that I provided in the box.

**Comment by funtigr** [comment]
Now Rejection has its own modal window:
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63cc08d3b5110de9731d8342fe7ff3873f472c1a/image.png" alt="image.png" />
