### ISSUE TITLE
24. If user Edits anything but not touches the quota the Modal Window wording says to describe why they changed the quota. Below it says that user needs the onboarding session though it's an Edit request. The second Modal Window says that the new project set has been received. 

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1626]

**Comment by Amritpal-Nijjar** [comment]
Current:
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW1BQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7804ca55dd619838538f5e5f956f5e905b7c5ef5/Screenshot%202023-12-21%20at%202.25.13%20PM.png" alt="Screenshot 2023-12-21 at 2.25.13 PM.png" />
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXFBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72e712c9b5c62681b319a227134f86864b21e04e/Screenshot%202023-12-21%20at%202.26.37%20PM.png" alt="Screenshot 2023-12-21 at 2.26.37 PM.png" />

**Comment by Amritpal-Nijjar** [comment]
Upon sending the edit request, seems like the confirmation email is broken currently ?
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVNBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c334493a7e62cf6e54c8787d546d55ec0ecb52b0/Screenshot%202023-12-21%20at%203.39.56%20PM.png" alt="Screenshot 2023-12-21 at 3.39.56 PM.png" />

**Comment by Amritpal-Nijjar** [comment]
Updated
<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f822e06533dea69644c888f3a57a1f606a1e99b/Screenshot%202023-12-21%20at%203.50.12%20PM.png" alt="Screenshot 2023-12-21 at 3.50.12 PM.png" />

**Comment by funtigr** [comment]
When the new change without changing Quota is requested, no info about Quota and onboarding is shown:
<img width="1401" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTZKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12a386b0fd9199639c952f9e929b0b1e70b14984/image.png" alt="image.png" />
