### ISSUE TITLE
27. If Admin clicks Approve in Public Cloud, they see the modal window with wording for successful project creation for Private Cloud.

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1634]

**Comment by Amritpal-Nijjar** [comment]
Current:
<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXFEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e65b950e34720dc7e7bbb606ad5f0ddc57cb99c6/Screenshot%202023-12-22%20at%2010.11.52%20AM.png" alt="Screenshot 2023-12-22 at 10.11.52 AM.png" />
<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29e4a772431900d4631cefaea4b5c8995c1443fc/Screenshot%202023-12-22%20at%2010.17.45%20AM.png" alt="Screenshot 2023-12-22 at 10.17.45 AM.png" />

**Comment by Amritpal-Nijjar** [comment]
Updated:<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK21EQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7ae0aee426f4a0085fd9e57bfbf5007352e4578/Screenshot%202023-12-22%20at%202.09.31%20PM.png" alt="Screenshot 2023-12-22 at 2.09.31 PM.png" />
<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5621d93becc0b28627e5b26006e6cd845ae1fe22/Screenshot%202023-12-22%20at%202.10.35%20PM.png" alt="Screenshot 2023-12-22 at 2.10.35 PM.png" />

**Comment by Amritpal-Nijjar** [comment]
@funtigr note that the emails being sent in public cloud decision page are for private cloud

**Comment by funtigr** [comment]
@Amritpal-Nijjar 
In Private Cloud we still have the same modal window as for user creation request:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1dPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08fc76bae45e450d090166c0bba8abf050ead1cb/image.png" alt="image.png" />

**Comment by Amritpal-Nijjar** [comment]
Before:<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUNTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4811104e1060e08157fe7b79668343857c72f2c8/Screenshot%202024-01-02%20at%2010.43.12%20AM.png" alt="Screenshot 2024-01-02 at 10.43.12 AM.png" />
Updated:<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVNTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91d2d910748b6d529d47ae43306d50679b0258a1/Screenshot%202024-01-02%20at%2010.21.50%20AM.png" alt="Screenshot 2024-01-02 at 10.21.50 AM.png" />
