### ISSUE TITLE
Create UI AWS User Roles Dashboard/Developers, Billing Viewers, Viewers, Security Auditors

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1652]
add dashboards with admin aws-roles Developers, Billing Viewers, Viewers, Security Auditors to public use roles Tab
Definition of done: 

- [x] dashboard filled with current product Developers, Billing Viewers, Viewers, Security Auditors roles

**Comment by funtigr** [comment]
UI has corresponding roles. The backend for them is KeyCloak instance itself.
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzZUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36ee4111268e51574fe94f92d9f1da16569214d9/image.png" alt="image.png" />
