### ISSUE TITLE
dashboard "pages" pagination

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1653]
add next/previous/pagination functionality to aws-roles dashboard

**Comment by funtigr** [comment]
The pagination works as expected:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71ff7ffb01fff2320157b1177502470a85f6f9d2/image.png" alt="image.png" />
