### ISSUE TITLE
add user functionality to one of aws-roles 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1654]
add functionality to add user to one of aws-roles via modal winnow according to provided Figma mock up
https://www.figma.com/file/llP34TwOrBUjUGey9PUu6c/Platform-Registry?type=design&node-id=2128-9380&mode=design&t=9xM4LTrJxVgrydxT-4

**Comment by funtigr** [comment]
The users can be added to the Public Cloud products. 
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0MrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79d3519f857e65bc35ee24ac613640d9ada50856/image.png" alt="image.png" />

<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjYrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a6cd25d9c60acae52fc0bd28bf497f3a385621f/image.png" alt="image.png" />

**Comment by funtigr** [comment]
@Kolezhanchik I have a concern:
If a regular user (non-admin) is added to one of the roles, the product doesn't become visible on their side.
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0srQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a341c5189e99beda03fcb56f9483d326f1db80f/image.png" alt="image.png" />
View from the added User side:
<img width="1470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN08rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--566f039c44044fc325f350a72833b3b98e90f196/image.png" alt="image.png" />
