### ISSUE TITLE
Design JSON message for new provisioning functionality

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#167]
## Story

As a developer, I need the JSON message refactored so it can be extended for additional functionality.

## Description

Refactor the JSON message so that it can be better used for requesting a new project set be provisioned, as well as accommodate new edit functionality. This can be done as one message for both with a `type` or as two separate messages.

## Done When

The message format supports both new requests as well as edits to both project and quota data.

**Comment by j-pye** [comment]
I decided to avoid a complete refactor of the message and instead just added what would provide the same functionality. 

YAML Version: (With some comments)
https://gist.github.com/j-pye/02c3bb929db4f49afc6f66571b00941c

JSON Version:
https://gist.github.com/j-pye/c63934e389f0b3378fd5edc770630ac4

@jleach  thoughts?

**Comment by jleach** [comment]
@j-pye Looks great. Maybe in the future change the contacts from items to an array like:

```
contacts: [
   {
      role: 1,
      name: 'Jane Doe',
      ...
   }
]
```

**Comment by jleach** [comment]
Justin to make one change later. Will be edit name.

**Comment by j-pye** [comment]
Just to add to Jason's comment. The edit DisplayName feature will be an update in a future sprint. I believe this should work for our initial edit feature. The NATS message sent from the Registry should be updated to use this format for both Create/Update(Edit).
