### ISSUE TITLE
Update the favicon, currently squished

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1679]
Observe that the logo is currently squished in the new UI
<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenlkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f95b8c7c5e41e803176a53a59d2bcd70004d9230/image.png" alt="image.png" />

Current registry has the correct logo (not squished from being a square image):
<img width="470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--983825cb182458696f7ec40325897fce996f1974/image.png" alt="image.png" />

**Comment by Amritpal-Nijjar** [comment]
Updated the favicon to use the current registries logo into the new one, as converting a rectangular logo into a square will squish the artwork.
<img width="92" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9kQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d23e3e596971db5d4ee4e2065bf9e9f1939d4e1/Screenshot%202024-01-04%20at%2011.37.53%20AM.png" alt="Screenshot 2024-01-04 at 11.37.53 AM.png" />

**Comment by funtigr** [comment]
<img width="330" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2VvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0433dd39590c800fb347b3927177240bb864ff7d/image.png" alt="image.png" />
