### ISSUE TITLE
67. Final touch on Email templates

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#1680]
**Description**:
The email templates need some fixes to be ready for the go live:
- [ ] 1. Decide if we will have separate emails for Create Request and any other Requests for Admin or it will be a universal one. Add corresponding points below for data fulfillment in the emails.
Now we have Create and Universal (PrivateCloudAdminCreateRequest and PrivateCloudAdminRequest) for Private Cloud and Universal for Public Cloud (PublicCloudAdminRequest).

- [x] 2. Fix the spacing between name and email in the Contacts section to correspond to the figma mockup. Same for Product details:
<img width="1066" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdytlQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d3e15ec748a98da45e0319ad4c5981fe5d9e2a8/image.png" alt="image.png" />
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEtlQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--beb8d7374fea30c1b8d08da90b4051d3bcd835e0/image.png" alt="image.png" />

- [x] 3. In the email template for the Admins (PrivateCloudAdminCreateRequest, PrivateCloudAdminRequest, PublicCloudAdminRequest), delete the call to contact Admins at PlatformServicesTeam@gov.bc.ca as they will contact themselves:
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFNlQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--942de8440ea11ced80229a95455e95f1b50ad6ce/image.png" alt="image.png" />

- [ ] 4. Fill the details of the namespaces in the Admin and User Creation templates for Private Cloud (PrivateCloudAdminCreateRequest, PrivateCloudAdminRequest). Now they show only the Cluster:
<img width="1444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGVlQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e06c6b0dd7ffc6c8700faeb4cc6ff0e8b297089/image.png" alt="image.png" />

- [x] 5. Rename Namespace Details to Landing Zone Details in the Public Cloud email templates.

- [x] 6. Fill the details of the Landing Zone (Account Coding and Budget) in the Admin and User Creation templates for Public Cloud (PublicCloudAdminRequest, PublicCloudCreateRequest). Now they show only the Provider.
 
- [x] 7. Fill the data (Current and Requested) for Contacts, Account Coding and Budget in PublicCloudEditRequest and rename the section from Quota Changes to Project Budget Changes.

- [ ] 8. PrivateCloudRequestProvisioned and PrivateCloudRequestApproved emails have wording for the Create request provisioned only. We need to add another universal email template for other types of requests.

- [ ] 9. PublicCloudRequestProvisioned and PublicCloudRequestApproved emails have a lot of Private Cloud wording and the wording only for Creation. We need to add another universal email template for other types of requests. And remove mentions of Private Cloud. 
 
- [x] 10. Change the email in the footer of all Public Cloud templates to Cloud.Pathfinder@gov.bc.ca.

- [x] 11. In the PublicCloudRequestRejection remove mentioning of Private Cloud.

- [x] 12. Change the URLs of the Review buttons in PublicCloudAdminRequest, PublicCloudCreateRequest, PublicCloudEditRequest and PublicCloudRequestRejection to lead to {ENV}/public-cloud/products/active-requests

- [x] 13. Change the URL of the PublicCloudRequestApproval template to {ENV}/public-cloud/products/all

- [x] 14. Remove namespace information from Delete Requests templates for Public Cloud.

- [ ] 15. Check that comments of Admins are coming to the user. If the comments are not for the user, than store them and create a ticket for their display for the Admins somewhere in the Product Page.

**DoD**:
The points above are done

**Comment by Amritpal-Nijjar** [comment]
1. Unsure of what to do with point 1
2. Spacing has been fixed
3. footer containing contact info removed
4. unsure of what details need to be filled in here, as I don't think we would have namespace details on a create request, as the product has not been provisioned yet ?
5. namespace details is now landing zone details (public cloud)
6. landing zone details have been filled (provider, budget, account coding)
7. edit request now has proper data for when requesting a change (public cloud) 
8. not sure of what template needs to be created here (perhaps a new ticket for this work ?)
9. not sure of what template needs to be created here (perhaps a new ticket for this work ?)
10. new prop for public cloud emails 
11. did my best to remove mentions of private cloud, but now the paragraphs are a little awkward, needs to be proofread
12. changed the urls to what will be the correct path 
13. changed the urls to what will be the correct path for public cloud here as well
14. removed the namespace details and instead inserted the landing zone details for a delete request public cloud
15. this needs to be tested...(perhaps a new ticket for this work ?)

**Comment by funtigr** [comment]
1. Keep Admin Request for not Creation and add data about changes like in Edit Request
4. Delete the header Namespace Details but leave the cluster data
8. Delete the text that signifies Edit or Create request to make text universal in Completed Request emails
9. Same as point 8 (Universal wording) and delete “admin” in the text
15. Add comment from Admin to Rejection and Approved templates (will require creation of the new component)

**Comment by funtigr** [comment]
Continuing in task #1811. Closing this one for now.
