### ISSUE TITLE
Implement automatic merges for trivial edits

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#169]

**Comment by jleach** [comment]
## Story

As a P.S. admin, I would like trivial edits to the project data to be automatically merged without review.

## Description

Trivial edits, such as those to project details, metadata, TC and PO should be implemented (merged) without the need for approval.

## Done When

The smart robots can detect a specific change type and determine if the edit can be immediately applied or not.

**Comment by j-pye** [comment]
@yhfreeman @sbathgate would either of you like to take this? This doesn't seem like a provisioner task anymore and more a feature of the Approval dashboard within the registry frontend/api.

**Comment by yhfreeman** [comment]
It's confirmed in [RC registry channel](https://chat.developer.gov.bc.ca/channel/devops-registry?msg=KSYZmWXmPDgp4o26S) that the following would still need to go through manual approval:
- provisioning new project set on a cluster
- quota size upgrade for the provisioned project set

**Comment by sbathgate** [comment]
Currently blocked until Multi-cluster support has been merged, tested and released.
