### ISSUE TITLE
add empty aws-roles empty list 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1696]
add empty aws-roles empty list same style as products empty list

**Comment by funtigr** [comment]
Now the Public Cloud Users Tab has a message if no users are added to the User Group. 
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMExkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a265ba71e1fd7a823a83e75036ca717d74315066/image.png" alt="image.png" />
The button allows to add a new User to the User Group.
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFBkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--693daece1c3a221db413de44c62eb0d30af37947/image.png" alt="image.png" />
