### ISSUE TITLE
 45. Allowing decimal in Budget for Public Cloud

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1699]
45. Allowing decimal in Budget for Public Cloud was a requirement from Olena and Public Cloud team when we implemented it

**Comment by Amritpal-Nijjar** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem0yQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f9b4baa1f58dd43ce52ff2683e19cdcb85f82bc/Screenshot%202024-01-09%20at%206.14.14%20PM.png" alt="Screenshot 2024-01-09 at 6.14.14 PM.png" />
