### ISSUE TITLE
Add TC as admin when provisioning a namespace

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#170]
## Story

As a project set requestor, I would like both the PO and TC to be granted admin access to a namespace.

## Description

If the PO and TC have a GitHub ID provided (see form validation to determine if both are mandatory) then both should be granted admin access to a namespace.

## Done When

A request is processed by a smart robot and one or both (if provided) the TC and PO are given admin access to a namespace set.

**Comment by jleach** [comment]
This will not be done to retroactively.

**Comment by j-pye** [comment]
This has been completed and is currently active in Prod. Closing
