### ISSUE TITLE
Refactor NATS messaging to accommodate new format

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#171]
## Story

As a developer, the NATS message should be updated to support the new message format (see dependency).

## Description

The NATS message will be refactored for both requesting new namespaces (existing functionality) and to allow for extension for edit. For this story, we just need to make the **existing** functionality work with the new format - not the new edit functionality.

## Done When

A new namespace request can be made with and the new message format is sent.

**Comment by yhfreeman** [comment]
**released on the registry-web-platform-registry-prod silver cluster: Dec 03, 2020
