### ISSUE TITLE
Implement new NATS message for edit functionality

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#172]
## Story

As a developer, I would like the new "edit" message to be sent as needed

## Description

The NATS message redesigned as part of this ticket (see dependencies) will require either two separate message or one message with a `type` to indicate if it's for an "edit" or "new project set". This story is to implement the message sent when "edit".

## Done When

A properly formated message is sent to NATS when a project "edit" is being requested.

**Comment by jleach** [comment]
If we want to include audit we can include the ID in the NATS message and it will get recorded in the PR.

**Comment by yhfreeman** [comment]
**released on the registry-web-platform-registry-prod silver cluster: Dec 03, 2020
