### ISSUE TITLE
[CURRENT UI]  update the project details page in Registry with the link 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1720]
Update the project details page in Registry with the link to the quota increase documentation; https://docs.developer.gov.bc.ca/openshift-project-resource-quotas/ 

<img width="1592" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODIxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fe2054f1f411669456a3c504c484bc1b87a4d2e/image.png" alt="image.png" />

**Comment by funtigr** [comment]
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjY5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5008320fb43c2551f83e2079ca5a7395c72938b2/image.png" alt="image.png" />
