### ISSUE TITLE
 61. The wording in the Edit Quota Request lacks connecting words and says: "All quota increase requests require Platform Services Team’s approval must have supporting information as per the Quota Increase Request Process." Let's change it to "All requests to increase quotas must have supporting information and approved by the Platform Services Team in accordance with the Quota Increase Request Process."

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1721]
<img width="1459" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNSsyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b992f612a0c53cddff0d336e5b14c46cfc00c03/image.png" alt="image.png" />

**Comment by Amritpal-Nijjar** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUsyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad64a1042761a9c630bbda9876367e9b06e630bb/Screenshot%202024-01-10%20at%2012.15.33%20PM.png" alt="Screenshot 2024-01-10 at 12.15.33 PM.png" />

**Comment by Amritpal-Nijjar** [comment]
- Added link to the Quota Increase Request Process documentation page
- Bolding now includes "not" for better clarity
- Addition of a Comma and Conjunction:

Original: 
> "All quota increase requests require Platform Services Team's approval must have supporting information as per the Quota Increase Request Process."

Changed: 

> "All quota increase requests require Platform Services Team’s approval, and must have supporting information as per the Quota Increase Request Process."

Change Explained: A comma and the conjunction "and" were added after "approval". This change improves the sentence structure, making it clearer and grammatically correct.

- Change in the Structure of the Second Sentence:

Original: 

> "The Quota Requests without supporting information will not be processed."

Changed: 

> "Any Quota Requests without supporting information will not be processed."

Change Explained: The phrase "The Quota Requests" was changed to "Any Quota Requests". This change shifts the tone slightly, making it more general and inclusive.

**Comment by funtigr** [comment]
👍
