### ISSUE TITLE
Add search functionality to aws roles list 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1731]
Add search functionality to aws roles list according to figma mockup https://www.figma.com/file/llP34TwOrBUjUGey9PUu6c/Platform-Registry?type=design&node-id=2259-9107&mode=design&t=VhK9XJybT8kLYe8y-0

**Comment by funtigr** [comment]
The search works by name and email:
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmpyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16a9f448b30e71648173f70b93342a0ae4596cc4/image.png" alt="image.png" />
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3JyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf1b190bf77741b59dd13ae6106e16df541fa8e6/image.png" alt="image.png" />
On all User tabs:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzNyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8060e9cc0149238b0ade9d90a50832eb295a4156/image.png" alt="image.png" />
