### ISSUE TITLE
Set up E2E tests - Login Test

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1732]
**Description**:
This task is to set up E2E testing in the registry repo. This is the initial work to configure and get it working.
This will include integrating the local key cloak env that was implemented earlier.

DoD: 
- produce a simple e2e test that requires Keycloak integration

**Comment by okanji** [comment]
This task is to set up E2E testing in the registry repo. This is the initial work to configure and get it working. 
This will include integrating the local key cloak env that was implemented earielr.

**Comment by funtigr** [comment]
The PR for the task: https://github.com/bcgov/platform-services-registry/pull/2017
