### ISSUE TITLE
SSO - turn off direct access grant for all Registry clients

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1735]
**Describe the issue**
SSO team has reached out asking to turn off `direct access grant` for Registry clients in the realm.

**Definition of done**
- [ ] discuss changes, update SSO team on timeline
- [ ] test out in lower environment
- [ ] push in changes

**Comment by Iryna-Kaplun** [comment]
Shelly asked Oamar to create this ticket. For more information we can reach out to Shelly.
