### ISSUE TITLE
Implement request tracking so that edits are clear and concise

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#174]
## Description

Ref. See meeting notes in associated EPIC.

When an edit is requested, similar type of data should be packaged into a single request. For example, if the PO is changed, then the TC is changed, it would be good if both can be packaged so that only one request is sent to the robots for implementation. In addition to this, some requests must be processed sequentially and **must bock** subsequent requests. For example, a user can only progress through CPU request from S to M then to L; they cannot go directly from S to L. If a request to go from S to M is pending, then subsequent quota edits must be blocked. However, it would be possible for the user to edit project metadata (that only exists in the database) or project details like description or TC.

For simplicity, v1 of this feature can treat any edit as the same and block all subsequent edits until said request is made. If implemented this way crate additional tickets to improve later.

The smart robots processing request must apply them in order (FIFO).

## Done When

A user can request edits to quota, and is blocked from making additional requests until the first request is made;
A user can request edits to project details, these requests do not block additional requests to project details.

**Comment by yhfreeman** [comment]
**released on the registry-web-platform-registry-prod silver cluster: Dec 03, 2020
