### ISSUE TITLE
64. AWS Roles mentions Projects instead of Products

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1744]

**Comment by funtigr** [comment]
Now it doesn't: 
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0xXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c70854afad14b3a1dbe9a69d7bfa4a89c9e7800d/image.png" alt="image.png" />
