### ISSUE TITLE
66. When page is refreshed in the products page, the user is moved to the Products tab

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1746]

**Comment by funtigr** [comment]
Now if the user refreshes the page on the Roles Tab in Public Cloud product, he is not redirected from the Tab.
There is one visual issue though. When the User is on the Roles Tab in Public Cloud product and on any of sub-tabs except "Admins", the "ROLES" tab is not highlighted:
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDdYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db2770f6852ed6c69a1a4f71577149f90300acc0/image.png" alt="image.png" />

How it used to be:
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUhYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6240ab36093929dc38ba2cc221d51b936fc50ad3/image.png" alt="image.png" />

I've added it as an non-urgent bug in the Bugs Epic.
