### ISSUE TITLE
Refactor the database so that it can track requests and quotas

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#177]
## Story

As a developer, I would like the database to be able to track namespace quotas and requests.

## Description

As part of the EPIC this story belongs to, we need to be able to track the requests that are made (new project set, edit project data, edit quota, and others in the future) as well as the quota for CPU / Mem / Storage for each namespace. Refactor the database so that it is ready for feature implementation. Once refactored it should be able to track the new information as well as work with the current requirements (new project).

## Done When

The database can track requests made along with the status of said request, as well as the quotas for each namespace for all three components.

**Comment by jleach** [comment]
Meeting Notes (JP, SB, YF, and JL):

* We'll need at least two additional tables the `audit` table and `request` table to track requests that are in-flight and what changed during an "edit".
* We also decided that it will be possible to make multiple requests and have multiple requests are in-flight **as long as** they only have **one** request in-flight that changes quotas.

**Comment by yhfreeman** [comment]
**released on the registry-web-platform-registry-prod silver cluster: Dec 03, 2020
