### ISSUE TITLE
Display App version in footer

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#1790]
In order to identify the deployed the version of the app in the specific environment, let's display the application version/tag on footer.

**Comment by funtigr** [comment]
In Test and Prod the version is displayed in regular version notation:
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeERkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0f1cbaafcac73f7fbcf13d78713151c17c3f5a0/image.png" alt="image.png" />
In Dev it is displayed as a deploy Tag from the Repository:
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGJkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aac623756ec1b030a793fdec531bc29c36c0ddaf/image.png" alt="image.png" />
