### ISSUE TITLE
Implement the UI and API to allow project quota updates

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#181]
## Story

As a user, I would like to request adjustments to my quota for each namespace. These adjustments should be independent for CPU, memory, and storage.

## Description

At the heart of the associated EPIC, users should be able to edit the quotas for each namespace. They are permitted to request updates for CPU, memory and storage; each should can be changed independently and packaged into a single request. Once a request is made any subsequent requests should be blocked (probably at the API) until the previous request is implemented.

## Done When

The user has a web UI they can use to request project quota increases which blocks them if a request is currently in-flight.

**Comment by yhfreeman** [comment]
**released on the registry-web-platform-registry-prod silver cluster: Dec 03, 2020
