### ISSUE TITLE
67.2 Email Templates New Iteration

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#1811]
Follow up of #1680
Fixes left to do in Email Templates:
1. Keep Admin Request for non-Create requests template (PrivateCloudAdminRequest) and add Current and Requested data like in Edit Request
2. (old 4) In PrivateCloudAdminCreateRequest and PrivateCloudAdminRequest templates delete the header "Namespace Details" but leave the cluster data
3. (old 8) Delete the text that signifies Edit or Create request to make text universal in Completed Request emails (PrivateCloudRequestProvisioned and PrivateCloudRequestApproved)
4. (old 9) Same as point 8 (Universal wording) and delete “admin” in the text for Public Cloud Completed Request templates (PublicCloudRequestProvisioned and PublicCloudRequestApproved)
5. (old 15) Add comment from Admin (mandatory to Submit Approval) to Rejection and Approved templates for both Public and Private cloud (will require creation of the new component)
6. If user creates an Edit Request they receive an email with the header that it's Approved while it's not:
<img width="1443" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL240QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efbe7d5f7dcc456743ef551f669ae9d92183c8b6/image.png" alt="image.png" />

**Comment by Amritpal-Nijjar** [comment]
Emails w/ comments

PrivateCloudEditRequest 	-User- -working-
PrivateCloudRequestApproval 	-Admin -not working-
PrivateCloudRequestRejection 	-Admin- -not working-
PubliCloudEditRequest 		-User- -not working-
PublicCloudRequestApproval 	-Admin- -not working-
PublicCloudRequestRejection 	-Admin- -not working-

**Comment by funtigr** [comment]
@Amritpal-Nijjar @okanji 
Added a new point in the task:
If user creates an Edit Request they receive an email with the header that it's Approved while it's not:
<img width="1443" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL240QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efbe7d5f7dcc456743ef551f669ae9d92183c8b6/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Don't see the changes yet:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--489cc378f0aafc5dd8c52acb252b840b3adac0a8/image.png" alt="image.png" />
<img width="1463" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMElFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5dd910a3b3af9db7fdc406b3ed94fc76dd8caf0/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Everything is tested out and works good except these:
3. Approval Request is mutual for Create and Edit Request but it has wording about the new project set and about level of access (which is usually only mentioned when the new product is created).
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWM5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48ab0ebec3a9273ffcf36d0730bf3e0329979e43/image.png" alt="image.png" />
4. The Public Cloud has mention of the Admin access which is not true in Public Cloud. Also it is information that is only suitable for creation approval and not for edit approval.
<img width="1461" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWs5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b1a6fb05a018edfeb81273196a077c0a14b8103/image.png" alt="image.png" />
