### ISSUE TITLE
aws roles dashboard row email should be clickable 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1823]
aws roles dashboard row email should be clickable

**Comment by funtigr** [comment]
The emails in the AWS Roles Dashboard are clickable:
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzdyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66f2cbc3a61af14e60d9dc24b81ac17c6e884dd3/image.png" alt="image.png" />
