### ISSUE TITLE
Private User Testing of the New Registry before Go-Life

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1829]
The team will reach to the following users for the final testing: 

- [x] - Ryan Loiselle
- [x] - Luke Gonis
- [x] - Abibat Adesina
- [x] - Olena Mitovska
- [x] - Jason Leach

DoD:

- testing is completed
- feedback is collected and added to the New UI Bugs epic and triaged into urgent/can wait until after go-live

**Comment by funtigr** [comment]
A draft of the Testing Script:
https://docs.google.com/document/d/1735rYsWsNJDcYQXKQsSg7nbZCson_9hkNwp7SXq_u0s/edit?usp=sharing

**Comment by Amritpal-Nijjar** [comment]
Building on the draft that Artem created, this will be the script for the user testing, WIP: https://docs.google.com/document/d/1edTTdvVvqbwVb1j99rzYsJnTsDOgkk0nQ-5LXDlQ5hQ/edit?usp=sharing

**Comment by Amritpal-Nijjar** [comment]
https://app.mural.co/t/test95393/m/test95393/1706221961647/7ee730e10b80b136bb1ecfdfe5ecb22c9b045632?sender=uadcf5245d45ca3e72a096820
