### ISSUE TITLE
Create mocks for new quota edit functionality

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#183]
Create mockups of the UI to edit quotas for later discussion.

**Comment by mitovskaol** [comment]
**Describe the issue**
As a PO/Tech Lead I want to be able to request project quota increase when I open the project record for editing in the Project Registry UI.  

**Additional context**
when a project record is open for editing , it should display the following information at the bottom of the form:
 - license plates for the openshift namespaces. Next to the namespaces there will be a message: This namespace is currently provisioned with:  SMALL size quota for CPU ( 4 cores as request, 8 cores as limit), SMALL size quota for RAM  16GBs as request, 32GBs as limit ), SMALL size quota for storage: 20 PVC count , 50Gbs overall storage with 25 GBs for backup storage
Next to these messages will be 3 buttons: REQUEST CPU QUOTA INCREASE, REQUEST RAM QUOTA INCREASE, REQUEST STORAGE QUOTA INCREASE.
Also display a message: "All quota increase requests require Platform Services Team's approval. Please contact the Platform Admins (@cailey.jones, @patrick.simonian or @shelly.han) in RocketChat BEFORE submitting the request to provide justification for the increased need of Platform resources (i.e. historic data showing increased CPU/RAM consumption). ".


**Definition of done**
All necessary code components to support this feature will be implemented in the UI and in the GitOps provisioner.

**Comment by yhfreeman** [comment]
![Screen Shot 2020-11-26 at 7.05.23 AM.png](https://images.zenhubusercontent.com/5f614eb4d71a0b4769478336/b39e12aa-a34e-4338-9cb3-ce797f0305da)

**Comment by yhfreeman** [comment]
To reflect the following decision made on Nov 26, 2020 and described in [this ticket](https://app.zenhub.com/workspaces/openshift-4-build-out-5db73142897668000144f22b/issues/bcdevops/openshift4-rollout/254), the quota-edit UI will have 1 request button that applies to all cpu, memory and storage update.

> The quotas have been discussed and approved by the PS team and representatives of the Developer Community. It was decided that going with a more granular approach when teams can request quota increases in each category for a specific namespace in a project set, will generate too much administrative overhead to manage it while no creating any particular positive impact on overall system capacity/utilization. Therefore, we will be going with one size for all 3 resource categories ("pre-packaged" solution) that will apply to the entire project set (dev, test, prod and tools).
