### ISSUE TITLE
Create a delete request email for Public Cloud

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1890]
To create an email template that alerts the admins of the Public Cloud team that a delete request has been submitted and needs their attention. This email is triggered by the delete request button currently being worked on by Oamar.

**Comment by funtigr** [comment]
The email template is visible but it is not triggered after the delete request is submitted.
@Amritpal-Nijjar Was sending it a part of the task?

**Comment by Amritpal-Nijjar** [comment]
I added adminDelete emails to the route

**Comment by funtigr** [comment]
Now admins receive the Deletion request email: 
<img width="1409" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWhKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5169e9adaf0b4aecfa59b0b7dd615123d935d8b/image.png" alt="image.png" />
