### ISSUE TITLE
Update links provided in registry emails 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1904]
Update links provided in registry emails 

1. You can read more about these tools [here]( https://docs.developer.gov.bc.ca/)
Then the rest of the links highlighted in red should be:
2. https://docs.developer.gov.bc.ca/image-artifact-management-with-artifactory/
3. https://docs.developer.gov.bc.ca/prebuilt-images/
4. https://docs.developer.gov.bc.ca/vault-secrets-management-service/
5. https://docs.developer.gov.bc.ca/vault-getting-started-guide/

<img width="841" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c79acd8beb60d2b61c986d8dd4533350823ed71d/image.png" alt="image.png" />

<img width="635" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90a27868181eed147ded1d712d4b71aa32c8fada/image.png" alt="image.png" />

**Comment by funtigr** [comment]
The links are changed:
<img width="1007" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNndNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6596affa2e3b0494190df33a768b73cd075d23c/image.png" alt="image.png" />
<img width="1003" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--330903547248feaedd489cedf938cbc6c997507e/image.png" alt="image.png" />
<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f3625ee6851266ac5d2d5132dc085aea6f57b00/image.png" alt="image.png" />
<img width="1008" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29NQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb5611cbd1176db45a7d7fa1259016de9952d8ff/image.png" alt="image.png" />
<img width="1005" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3NNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--948839d65f37e8bfa568f93c6b38510b18ee5d5e/image.png" alt="image.png" />
