### ISSUE TITLE
Implement promotion pipeline for the Project Registry

### ISSUE THREAD

**Issue by sbathgate** [bcgov/platform-services-registry#192]
**Describe the issue**
Currently the registry requires a varying amount of manual interaction to promote changes through the environment stages. In order to automate the process, there will be a variety of foundational steps necessary to ensure data integrity and consistency throughout the pipeline. 

**Additional context**
To achieve this objective, the following must occur:
- [x] Ability to apply SQL scripts within automated deployment
- [x] Improve the image build and tagging process (addressed in ticket #336)
- [ ] Implement GitHub Actions that will promote to the Test and Prod environments in a controlled way, as determined by the team.

New GitHub Actions are in place for each of the DB, API, and WEB components to build new images and tag them for Dev, which causes the new image to be deployed to the Dev environment (see ticket #336).

Additional GitHub Actions are to be implemented for the promotion of each of the three components to Test and Prod.  Promotion to Test will be based on the images tagged with "dev".  Promotion to Prod will be based on the images tagged with "test".

Based on discussion with the team, promotion to Test:
- will be triggered upon merging of updates into the master branch, but only if there are updates to files in the api, db, and web directories
- may be triggered manually
- will apply the "test" tag to each image that is already tagged with "dev"

Promotion to Prod...
- will be triggered upon the creation of a 'release' in GitHub
- may be triggered manually
- will apply the "prod" tag to each image that is already tagged with "test"

**Definition of done**
This issue will be complete when GitHub Actions are in place for the promotion to Test and the promotion to Prod.

**Comment by jleach** [comment]
@j-pye @yhfreeman To touch base on where this will integrate into the database migration.

**Comment by jleach** [comment]
@yhfreeman Has done some work on Flyaway DB for updating the schema. We need to touch base again as a team and figure out how to integrate her work in such a way that it "deploys" a release that includes the Web and API image as well as the schema updates for the database.

**Comment by IanKWatts** [comment]
GitHub Action is in place for promotion to Test.  It has been used (once, so far) and looks good.

The promotion to Prod has not been enabled yet.  This will be done when the team is ready to test it.

**Comment by IanKWatts** [comment]
A number of promotions to Test have occurred without issue.  Promotion to Prod uses the same process and this has now been enabled.  Closing this ticket.
