### ISSUE TITLE
Add an email template with links to ACS, Vault and Artifactory in the New UI

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#1929]
Add an email template with links to ACS, Vault and Artifactory.

- Should be links to the documentation and if possible also links to the actual service. 
- Add links to the platform about how to use security tools in the emails

We have a email with all the link in the current registry that is sent to the PO and TL only AFTER the confirmation email. 
We need to clarify with Cailey and Olena when this email should be sent: 1) when a product is newly created or 2)after the quote change like we have it now int he current registry.

Zhanna to check with Cailey if the email that we currently have with the links is a good one to use in the New UI.

Dod:

The above is completed and signed off by Cailey?

**Comment by mitovskaol** [comment]
@Kolezhanchik  Please add the  following message to the provisioning confirmation  email that gets sent when a new product is finished provisioning:  Please check the Technical Documentation website for Private Cloud Openshift platform at to learn about tools and services available for product teams  as well as about application security best practices.

**Comment by funtigr** [comment]
@Kolezhanchik 
The email looks good but there are a couple of issues:
1. The Sysdig section has ACS info and link:
<img width="969" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1UxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acc246c415362da308a9ee66c60c301af161f394/image.png" alt="image.png" />

2. A suggestion about word "container" which is recognized as a keyword. As we use Unicode for our project we could substitute a usual latin symbol by Cyrillic symbol. The word would not be recognized as a keyword and the users will not notice visual difference.

3. The email doesn't have a phrase suggested in the previous comment by Olena.

**Comment by Kolezhanchik** [comment]
create common wrapper component like 
`<Html>
      <Tailwind config={TailwindConfig}>
//head is required by tailwind
<Head/>
`

**Comment by Amritpal-Nijjar** [comment]
I moved the content of this from PrivateCloudRequestApproval template to the PrivateCloudRequestProvisioned template
