### ISSUE TITLE
[Refactoring] Client & Server base components

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#1954]
We want to create client & server base components to provide similar benefits of `API Handler`.
https://github.com/bcgov/platform-services-registry/blob/main/core/api-handler.ts

- [ ] 1. Role and permissions checking with redirection to a specified URL as a fallback.
- [ ] 2. Validation of path parameters.
- [ ] 3. Validation of search parameters.
- [ ] 4. Provision/provide of parsed parameter data and session information.
- [ ] 5. Mitigation of confusion between Next.js client and server components.('use client')

**Comment by Kolezhanchik** [comment]
https://nextjs.org/docs/app/building-your-application/rendering/client-components
