### ISSUE TITLE
Create a Low FI mockup for the improved/ simplified version of the Platform status dashboard

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1967]
prep work on a mockup for the improved/ simplified version of the Platform status dashboard at  https://status.developer.gov.bc.ca 

There is a channel in the RC for further discussion (Uptime.com status page improvement)

**Comment by Amritpal-Nijjar** [comment]
**V1**
<img width="1118" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXFiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e11f675cac8f80b68b399ece45c3367f0beec03/Screenshot%202024-02-28%20at%201.36.20%20PM.png" alt="Screenshot 2024-02-28 at 1.36.20 PM.png" />
<img width="1403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXliQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--777f6067ec3a20c5afe8744c81118fc0ffef3a63/status-redesign.png" alt="status-redesign.png" />

**Comment by Amritpal-Nijjar** [comment]
**LoFi**
<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKytiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e5c06713c12e6933a828d8cdb8ae10d0cb92b08/Screenshot%202024-02-28%20at%205.15.44%20PM.png" alt="Screenshot 2024-02-28 at 5.15.44 PM.png" />

<img width="1403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzJiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c39c8856b115c27247832e89d8d4234de126d2ca/status-redesign.png" alt="status-redesign.png" />
