### ISSUE TITLE
87. Spell ministries instead of Acronyms (e.g. Citizen Services instead CITZ) in the dropdown.

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1976]

**Comment by funtigr** [comment]
Now the ministries have full names. And the list has all the ministries we have in the current Registry:
<img width="1458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7cbf6dae4419f2a5d1fe29e9b9902a7ee5ce1f8/image.png" alt="image.png" />
