### ISSUE TITLE
91. Return old look of the Contacts on the Products and In Progress tabs.

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1977]

**Comment by funtigr** [comment]
Now we have all three contact names visible in full representation:
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1k3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01358d651be8ea43ecbafb0f7feab38b6c49ce2c/image.png" alt="image.png" />

Even on a squished screen:
<img width="844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2M3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16bd50dbaf4babcafb7c5d39314afbef99063baa/image.png" alt="image.png" />
