### ISSUE TITLE
 106. Search on Prod shows "1 of 2 results" on UI though two products in the downloaded .csv. in Public Cloud

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1979]

**Comment by funtigr** [comment]
Now the Search works as expected and shows all the found results.
Both in Products Tab:
<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUk4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--207993f08c6599e1db35bf09b873624394adfbda/image.png" alt="image.png" />

And in In Progress Tab:
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVk4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e29dcf71e0fa2b92d439eaa05d10c2ad6e5721b4/image.png" alt="image.png" />
