### ISSUE TITLE
Improve Registry dashboard desktop view for viewing projects

### ISSUE THREAD

**Issue by yhfreeman** [bcgov/platform-services-registry#198]
**Describe the issue**
While the cards layout is really good for mobile devices, as a PO / Platform director I'd like to use BC Services Card Self Service as a reference and see similar view on Registry dashboard.

**Additional context**
![image](https://user-images.githubusercontent.com/42105264/99777480-328ea600-2ac7-11eb-8364-f43c60cf2da3.png)

**Definition of done**
Users see the list of projects when they are on Registry dashboard desktop view.

**Comment by yhfreeman** [comment]
As per your request, I've created this ticket in the backlog based on our convo @juhewitt, but please feel free to modify it. I've also communicated with @sbathgate about the similar concepts for the edit feature so we can be on the right track. Thanks.

**Comment by juhewitt** [comment]
Looks great! Spot on!

**Comment by sbathgate** [comment]
This will likely be resolved while making adjustments for Multi-cluster support

**Comment by sbathgate** [comment]
This table view was implemented in the following PR:
https://github.com/bcgov/platform-services-registry/pull/323

Filtering capability remains to be completed as detailed in ticket #155
