### ISSUE TITLE
112. Search doesn't work in Public Cloud on Prod. "Test" and "Website" don't display expected result.

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#1981]

**Comment by funtigr** [comment]
Now the search works as expected:
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzFFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a1ee5175791a2e4d84fadbb4bdaf3e1ed44f1b5/image.png" alt="image.png" />
