### ISSUE TITLE
Create Project documentation for the registry 

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1995]
Get in contact with Pilar for more information. Create a document with the following information for the Registry:

**Project Overview**
A brief description of the project, its purpose, and the problems it aims to solve. (Two to three short paragraphs can suffice)
 
**Key Technologies Used**
Highlight the main technologies, frameworks, or programming languages that powered your project. If you are using any common components from the community (such as backup-containers), or platform shared services (such as Artifactory and Vault), please also let us know!
 
**Challenges and Solutions / Lessons Learned**
Share any hurdles your team faced during development and how you overcame them. Alternatively, if there are valuable lessons learned in the process, those would be fantastic to include.
 
**Code snippets or links to your repository**
It’s always easier for teams to adopt good practices when they can see how the others do it. It’ll be very helpful if you can share your GitHub repo and documentations on how things are configured/setup.

**Architecture overview:**
Very Nice-to-Haves but not required.

**Comment by Pilargit12** [comment]
Hi @junminahn ! Please send us work to review by end of day February 14 please in order to have it ready for Feb 21 

Kindly contact @ShellyXueHan and myself if you have any questions, thank you kindly!
