### ISSUE TITLE
Visual Bugs in the New UI

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2003]
- [x] 88. Create and Product Page in Private Cloud: a. change "Cluster" to "Private Cloud OpenShift platform hosting tier". b. Under the cluster dropdown: "Please read more about tiers here" where "here" is a link to https://digital.gov.bc.ca/cloud/services/private/products-tools/hosting-tiers/
- [x] 89. Login Page: change "product resource quota increases and downgrades (including CPU/RAM/Storage.)" to "product resource changes."
- [x]  90. Create Page. Add "Provisioning request from new teams that haven't had an onboarding meeting won't be approved."
- [x]  92. Change the description on the In Progress tab to: "These products have pending requests and admins are approving them."
- [x] 105. Both on Private and Public Cloud Product Tab: a. change "There are no requests" to "There are no products", b. delete "You currently have no provisioning requests for the Private Cloud Openshift Platform" completely, c. change in link text: "PROJECT SET" to "PRODUCT".
- [x] 111. On Products and Requests Tab change Deployed in Public Cloud to Created (as it is now in Private Cloud).
- [x] 113. In Deletion Popup change "Project" to "Product" and change "product set" to just "product".
- [x]  114. If the Product is not ready to be deleted add a sentence: "Please remove all pods and PVCs from all four namespaces before trying to delete again."
- [x]  115. Second modal on Approval: change product set or project set to just product (-s).
- [x]  116. On Public Cloud Create, Request and Product pages under Provider dropdown add text "Read more about Public Cloud Service Providers here", where "here" is a link to https://digital.gov.bc.ca/cloud/services/public/providers/
- [x]  117. Delete "- Project Set Provisioning Request" in the header of Product Page.

**Comment by funtigr** [comment]
88. The changes are made for Admins only. Add the phrase with link to documentation for the Users as well:
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkZkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6eace1113ee4c873e233389caf3f89ea51cdb6a1/image.png" alt="image.png" />
105. c. In the empty list there a phrase "PRODUCT SET". Olena said we need "PRODUCT" without "SET" here. 

And can we, please, squeeze in one more urgent fix?
112. The confirmation Deletion modal window is the same as for New Project Set. Needs to be changed to Deletion relevant content:
<img width="1477" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVJkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cee98ed16195b8c154c72d016459f9bfbd37a2cf/image.png" alt="image.png" />

**Comment by funtigr** [comment]
88. Fixed, now User has link to Hosting Tiers documentation too:
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUYzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aeb203e3700837114c12d1a450b488b8474ae70b/image.png" alt="image.png" />
89. Fixed. Now we have "PRODUCT" in the empty list notification.
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVIzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--116f6bf479c755638e5d23f2f70084b4e969d401/image.png" alt="image.png" />
119. Fixed. Now we have the proper Delete message on the modal window for deletion. Both in Private and Public Cloud.
<img width="1458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXAzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83149a34e30d86b69e7e70bb655c21c6e0e8bf50/image.png" alt="image.png" />
<img width="1458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTEzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--469914110940a461fb00a161070f99ccff41d794/image.png" alt="image.png" />
