### ISSUE TITLE
97. Email Templates - Change the signage box

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2036]
97. Email Templates. Change the signage in the bottom to Platform Services Team for Private Cloud and to Cloud Pathfinder Team for Public Cloud templates.

**Comment by funtigr** [comment]
Now the signage is split for Public and Private cloud email templates:
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzlXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9eeed42236bffa2b1553c8b7f5d5fe128f67999/image.png" alt="image.png" />

<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--974ec5d86fef576f818e36071a15b2a0368caa1d/image.png" alt="image.png" />
