### ISSUE TITLE
79. The users added to the Public Cloud Product in New UI shows it has no UPN in the Current Registry. 

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2056]
79. The users added to the Public Cloud Product in New UI shows it has no UPN in the Current Registry. Those users have UPN in AD.

**Comment by funtigr** [comment]
Now Users added in the New UI have UPN and IDIR shown both in New and Current UIs:
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDUzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f222f6a0c214f55f0f8495a22207e414496a7685/image.png" alt="image.png" />

<img width="1458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDkzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc8b795cb0f4a9f5faae8ee981658c72db4cf818/image.png" alt="image.png" />
