### ISSUE TITLE
Missing Context for Design Patterns

### ISSUE THREAD

**Issue by juhewitt** [bcgov/platform-services-registry#207]
**Describe the issue**
When registering a new project, the list of design patterns have no context as to what the design pattern is, though they can be assumed.

**Additional context**
As a user, I want to be able to find additional information on a design pattern, so as to know whether I'm currently using it, or it can reference me to an existing common component.

**Definition of done**
As a user, I click on a design pattern link, which launches a new window for the resource on the design pattern hosted on developer.gov.bc.ca.

![image.png](https://images.zenhubusercontent.com/5d658f800f25370001090f16/b921cef3-9005-4926-96cb-eaea9b601897)

**Comment by juhewitt** [comment]
For the backlog, and future efforts.  This is based upon feedback from some community members that came to me with the suggestion.

**Comment by w8896699** [comment]
Hi @juhewitt , is there any more specific requirement on this ticket, like which option need more explanation?

**Comment by ShovelHand** [comment]
I don't understand; are there documentation resources for these currently on developer.gov.bc.ca, or is creating that part of the task?

**Comment by ShovelHand** [comment]
With Theresa's help, I was able to find articles on most of these components from https://digital.gov.bc.ca/common-components.
I am still looking for documentation we have on Bambora, MS Teams notiications, file storage, and scheduling.

**Comment by lukegonis** [comment]
Majority of components are completed, will merge what is complete to prod and complete the rest in a future sprint.
