### ISSUE TITLE
Add Application Portfolio per Ministry pie charts to Registry Analystics Dashboards

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#2110]
As a Director for Private and Public Cloud, it is important for me to understand to which extend each Ministry uses Private and Public cloud platforms. I would like to see a pie chart with the application breakdown per Ministry. 

Definition of Done:
- Add 4 pie charts to the [Analytics page for Private Cloud](https://pltsvc.apps.silver.devops.gov.bc.ca/private-cloud/analytics) - applications per Ministry in Silver, applications per Ministry in Gold, applications per Ministry in Emerald and applications per Ministry across all production clusters
- Add one pie chart to the [Analytics page for Public Cloud](https://pltsvc.apps.silver.devops.gov.bc.ca/public-cloud/analytics) - applications per Ministry in AWS

**Comment by junminahn** [comment]
@mitovskaol I've just completed updating the production environment for the charts. Please take a moment to review and provide your feedback.
