### ISSUE TITLE
Add an "Expense Authority" field to the Public Cloud

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2128]
Describe the issue
As a platform administrator, I want project sets to have a mandatory "Expense Authority" contact field, so that billing emails and cost recovery billing reports can automatically include that contact information.

Rational/Why
This will help automate quarterly billing reports - the current state involves a manual contact retrieval which takes a lot of time and allows for errors - as well as communicate billing information to that contact.

Additional Context

Link to the code repositories
List of technologies that may be expected to be known in order to work on the task
Clear description of where the code change is going, e.g "add the text input to the create request form in components/request.js"
Clearly identify which products are being updated ("Platform Services Registry")
Dependencies

Internal, external, who to talk to if more information is needed
Tests

Definition of done/Acceptance Criteria

When creating a new project set, an "Expense Authority" field must be filled out, similarly to the Product Owner and Technical Lead fields.
That contact can't view nor log into the registry.
That contact is connected to an IDIR.
That contact can't be deleted, only edited (in case the person changed).
Billing emails are NOT sent to that contact (edited to "Not sent).
That field and contact information must be retrievable for automated reporting purposes (Quarterly billing report). Contact info are: First Name, Last Name, Email.

**Comment by funtigr** [comment]
Now the Create page of the Public Cloud has the Expense Authority field. It accepts only the emails which have IDIR.
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2ZJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00e0eceb87930b083378ea1f3a539c81f1a9228f/image.png" alt="image.png" />
The field is grayed out if it is in the Active Request. And it is saved in the Product after provisioning.
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2pJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bbb9dceebfc36986e964769b11713e1aacf0424/image.png" alt="image.png" />
