### ISSUE TITLE
The description can not have unescaped quote in it

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#213]
## Description

The Web and API/DB can store messages as users enter them, however, when sending the JSON message via NATS the API should:

1. Escape double quotes with `"` -> `\"`.

## Done When

If the description or project name contain single quotes in the Web/DB they are escaped before sending the message to NATS.

**Comment by yhfreeman** [comment]
**Bugfix updated on the registry-web-platform-registry-prod silver cluster: December 16, 2020

**Comment by yhfreeman** [comment]
Updated ticket content:

**Description**
The Web and API/DB can store messages as users enter them, however, when sending the JSON message via NATS the API should:

~Escape double quotes with " -> \".~
Replace double quote -> space in the JSON message but leave it as-is in the db.

**Done When**
~If the description or project name contain single quotes in the Web/DB they are escaped before sending the message to NATS.~
Double quotes should be removed when JSON message is sent to bot in nats / related api sync endpoints
