### ISSUE TITLE
Refactor the NATS message so that quotas reside in the registry database and not with the bot.

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#216]
## Description

The user will see t-shirt sizes for quotas along with the actual values they represent (2 cores, 3 G men, etc). When requesting quota increases they will continue to use t-shirt sizes, however, the Api needs to translate t-shirt sizes into actual values an pass them in the NATS message to the bots.
Ref. https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/254

## Done When

The database contains actual quota values and they are passed in the JSON message to NATS for implementation.

**Comment by jleach** [comment]
@j-pye To design the new JSON message for implementation then @yhfreeman to implement.

**Comment by j-pye** [comment]
https://gist.github.com/j-pye/c63934e389f0b3378fd5edc770630ac4
https://gist.github.com/j-pye/02c3bb929db4f49afc6f66571b00941c
YAML and JSON versions

I've asked Steven to confirm the use of `capacity` for storage incase there's a better word to describe what that field is used for.

**Comment by j-pye** [comment]
Confirmed with Steven that capacity is fine although storage_capacity might be a better DB field.

**Comment by yhfreeman** [comment]
The ticket is carried from the last sprint as the wrapping-up process becomes more time-consuming than previously expected.
Some factors:
- resolving conflicts and integration tests to integrate new feature (PO/TC associated to a project via web portal) while the quota refactor is being wrapped up
- coordinating between provisioner and registry api in terms of PR reviews, testing and release strategy

**Comment by yhfreeman** [comment]
> https://gist.github.com/j-pye/c63934e389f0b3378fd5edc770630ac4
> https://gist.github.com/j-pye/02c3bb929db4f49afc6f66571b00941c
> YAML and JSON versions
> 
> I've asked Steven to confirm the use of `capacity` for storage incase there's a better word to describe what that field is used for.

@j-pye With quota-related key-values moved to the first depth, is it correct to understand that the tshirt size will apply to all namespaces in all applicable clusters? Was referring to [this ticket](https://app.zenhub.com/workspaces/openshift-4-build-out-5db73142897668000144f22b/issues/bcdevops/openshift4-rollout/254) but couldn't find anything explicit. Thanks.

**Comment by yhfreeman** [comment]
**Updated on the platform-registry-prod silver cluster: Feb 18, 2021
