### ISSUE TITLE
The user should be able to edit the project description

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#218]
## Story
Currently the project description is not able to be updated from the registry. 

## Description
As the provisioning system requires notifications of updates to a project's description. Adjustments to the provisioning logic is necessary to send profile changes and receive callback notifications.

## Done When
A user is able to update their profile description and this is reflected within OpenShift

**Comment by sbathgate** [comment]
Pushed and tested in TEST on silver Jan 20, 2021
Pushed to PROD on silver Jan 20, 2021
