### ISSUE TITLE
Initialize and setup RESTful api for comments

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#2181]
We want to construct backend API endpoints for the entity `PrivateComment`, adhering to the RESTful specification. Each endpoint will be encapsulated within the `api handler` for streamlined access management and data parsing.

Link to the `api handler`: [https://github.com/bcgov/platform-services-registry/blob/main/core/api-handler.ts](https://github.com/bcgov/platform-services-registry/blob/main/core/api-handler.ts)

1. **Create a Comment**
   - **Method:** POST
   - **Endpoint:** `/api/private-cloud/products/[licencePlate]/comments`
   - **Description:** The operation function will create a new private comment using the provided `licencePlate` as the first argument and `data` as the second argument, returning the created comment.

2. **List Comments**
   - **Method:** GET
   - **Endpoint:** `/api/private-cloud/products/[licencePlate]/comments`
   - **Description:** The operation function will retrieve all private comments associated with the provided `licencePlate`.

3. **Read a Comment**
   - **Method:** GET
   - **Endpoint:** `/api/private-cloud/products/[licencePlate]/comments/[commentId]`
   - **Description:** The operation function will fetch the private comment identified by both `licencePlate` and `commentId`, returning the comment data.

4. **Update Comment**
   - **Method:** PUT
   - **Endpoint:** `/api/private-cloud/products/[licencePlate]/comments/[commentId]`
   - **Description:** The operation function will update a private comment using the provided `licencePlate`, `commentId`, and `data`, returning the updated data.

5. **Delete Comment**
   - **Method:** DELETE
   - **Endpoint:** `/api/private-cloud/products/[licencePlate]/comments/[commentId]`
   - **Description:** The operation function will delete the private comment identified by `licencePlate` and `commentId`, returning `true` or `false` to indicate the status.

**Comment by Amritpal-Nijjar** [comment]
POST
To create a comment
http://localhost:3000/api/private-cloud/products/[licencePlate]/comments

GET
To list comments
http://localhost:3000/api/private-cloud/products/[licencePlate]comments

GET
To read a comment
http://localhost:3000/api/private-cloud/products/[licencePlate]/comments/[commentId]

PUT
To update comment
http://localhost:3000/api/private-cloud/products/[licencePlate]/comments/[commentId]

DELETE
To delete comment
http://localhost:3000/api/private-cloud/products/[licencePlate]/comments/[commentId]

**Comment by funtigr** [comment]
The endpoints work and allow making the functions.
After the comment is edited (method PUT) the "Created" timestamp is left the same and there is now "Updated" field. But it's a rear case so we'll implement it later if we want.
