### ISSUE TITLE
Document the design of the registry and bot components

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#220]
## Story

As a team member or end user I would like to better understand how the system works.

## Description

There is a lack of understanding as to how the current provisioning and edit workflows work. We would like to resolve this by documenting these two workflows. This documentation will be added to 

## Done When

This will be done when documentation each component. This documentation should be as visual as possible to convey complex information as quickly as possible.

- [ ] Web - Shaun
- [ ] API - Jason
- [ ] Database Schema - Yuhan
- [ ] Bot - Justin
- [ ] Repository - Justin
- [ ] ArgoCD - Justin

**Comment by ll911** [comment]
#237 edit should include both displayName and projectDescription

**Comment by mitovskaol** [comment]
@j-pye Can you please check off boxes for the parts that you've already documented and include the links to those breathtaking diagrams in the Miro boards that you showed to me.
