### ISSUE TITLE
Public cloud emails improvements

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2211]
- [x] Licence plate info on the product details page
- [x] Rocket chat channel name change 
- [x] Delete request wording, work to be done on that on our side

**Comment by prabhukiran9999** [comment]
- The channel for Rocket chat is #aws-tenant-requests
- The wording for the email PublicCloudDeleteCompletion is as below 
Subject: Your deletion request has been sent to our platform administrators!

Message:

Hi Product Team,

We acknowledge the receipt of your deletion request for the Sample Project's project set. This request has been communicated to our platform administrators, who will take the necessary actions to delete the specified project set.

Please be informed that until the deletion process is completed, the project set will continue to incur charges for the utilized resources. We are committed to processing your request promptly to minimize any additional expenses.

**Comment by funtigr** [comment]
The text about deletion from the above comment is added to the Delete Completion template:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3JJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33a96cc9ff892f0fe3764f87c161270b0645b659/image.png" alt="image.png" />

@Kolezhanchik 
One of the templates still has the link to another Rocket.Chat channel:
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c30b1090b2b0985eb677c5e812d7b10da976a81/image.png" alt="image.png" />
