### ISSUE TITLE
Hide Expense Authority on prod 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2212]
Hide Expense Authority component and make optional form field for prod

**Comment by funtigr** [comment]
After Prod is deployed the Expense Authority is not shown on Prod:
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL25JQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c63e2381c9d0fe158c61d7fc6496c726dc10e3a8/image.png" alt="image.png" />
