### ISSUE TITLE
Private cloud provisioner callback authentication

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2213]
**Description**  
- Secure the provisioner callback endpoint by validating the token provided by the registry.

**Technical Details**  
- Since we have an admin page to manage `team tokens`, create a dedicated token for the private cloud team to include in their requests and invite private cloud team members into the team token.
- Establish new API endpoints under `/api` to move the existing logic, with authorization checks.

**Definition of Done (DOD)**  
- The private cloud team can successfully send requests to the callback URL without issues.

**Comment by junminahn** [comment]
We added a new callback URL `POST /api/v1/private-cloud/products/<idOrLicencePlate>/provision`, which requires Team account's access token in the Authorization header.
I reached out to `Ian`, so that he can test it on test environment.

**Comment by Iryna-Kaplun** [comment]
Testing will be done by Ian

**Comment by funtigr** [comment]
Here is Ian's ticket for updating the Provisioner side on that on Platform Experience board:
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5285

**Comment by IanKWatts** [comment]
This has been completed on the Provisioner side.
