### ISSUE TITLE
#39. Public Cloud Account Coding - Add Info Icon. Limit Input Value to Numbers only for 4 fields

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2215]
There are 5 fields to enter financial coding and when a user made a mistake in any part of the financial coding, it doesn't show where the mistake is made, only a message that in the Account Coding line that something is wrong.

The only error that a user can make is to enter to short line for any of those 5 lines. A user can't enter more characters than necessary as there is a restrictions for each line.  

<img width="520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDI3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d9c71474e2ecfc6164581008c20b5ff085b5090/MicrosoftTeams-image%20%285%29.png" alt="MicrosoftTeams-image (5).png" />

To do: 

- [ ] add information icon besides every financial line about the requirements for each line (e.g. the length of each line)
- [ ] confirm what we include in the information box
- [ ]  Limit Input Value to Numbers only for 4 fields - CC, SL, RC and STOB

**Comment by Kolezhanchik** [comment]
﻿
Client Code
RC
SL
STOB
Project Code
112
32102
34805
6309
3200000
CC - Client Code
RC - Responsibility Centre
SL Service Line
STOB - Standard Object Of Expense
PC - Project Code
Client Code
• 3 Characters
• Can contain only numbers. No special characters (e.g. !@#$%^&*)
Responsibility Centre (RC)
• 5 Characters
• Can contain only numbers. No special characters (e.g. !@#$%^&*)
Service Line (SL)
• 5 Characters
• Can contain only numbers. No special characters (e.g. !@#$%^&*)
Standard Object of Expense (STOB)
• 4 Characters
• Can contain only numbers. No special characters (e.g. !@#$%^&*)
Project Code
• 7 Characters
• Can contain only numbers and letters. No special characters (e.g. !@#$%^&*)
• Only Uppercase

**Comment by funtigr** [comment]
The information icons are present at the Create Page of Public Cloud and information is displayed on hover: <img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL01zQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2fdf9ea006d2f5c1fa1bb7b6e9466bcc9f05fee/image.png" alt="image.png" />
