### ISSUE TITLE
44. Restricting special characters for the Product Name field. 

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2216]
44. Restricting special characters for some fields is a necessary requirement. Edition - this is only about the Product Name. We need to clarify with Olena if this is also required for the private cloud. Also, we need to clarify what special characters can be allowed (e.g. "-" ) as users often use "-" in the product names. 

Requirement: there is a special character restriction for the product name only after a user submits a request. We need to change it so when a user creates a product and types in any restricted special character it shows right away that that character is not allowed. 

<img width="1611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU83QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--162d8c08f277f7820823972fcc05076765eca9d7/MicrosoftTeams-image%20%286%29.png" alt="MicrosoftTeams-image (6).png" />
<img width="1639" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVM3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3d82173f82577503e397ac52fe1f78714344aeb/MicrosoftTeams-image%20%287%29.png" alt="MicrosoftTeams-image (7).png" />

**Comment by junminahn** [comment]
- Letters (both uppercase and lowercase)
- Numbers (0-9)
- Spaces
- Hyphens (-)
- Underscores (_)
- Periods (.)
- Parentheses (())
- Ampersands (&)
- Plus signs (+)
- Exclamation marks (!)
- At symbols (@)
- Pound signs (#)
- Dollar signs ($)
- Percent signs (%)
- Carets (^)
- Asterisks (*)
- Question marks (?)
- Forward slashes (/)
- Backslashes ()
- Colons (:)
- Semicolons (;)
- Quotation marks (' and ")
- Square brackets ([])

**Comment by funtigr** [comment]
Now the special characters that are not allowed in the name cannot be typed in the Product Name field. The info about restriction is now permanently displayed under the Product Name field.
