### ISSUE TITLE
Current quote edit feature will work well with future profile edits.

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#222]
## Story

As a developer, I want to make sure current quota edit feature will work well with other edit features, including profile description and contacts under a profile so there's no conflicts.

## Description

The Registry api code should have necessary and some reusable components that support all edit features in a way that all other edit requests should be blocked when there's an ongoing request for a given profile.

## Done When

There is enough groundwork so we are confident quota edit feature will work well with other edit features.

**Comment by jleach** [comment]
@yhfreeman Please fill in deeds when you have time. Thx.

**Comment by jleach** [comment]
@yhfreeman Please fill in the description. Thx.

**Comment by yhfreeman** [comment]
**released on the platform-registry-prod silver cluster: December 16, 2020
