### ISSUE TITLE
Separate Provisioning of GoldDR Projects in the Registry

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2229]
As the mandatory use of the geographic failover capability was removed for the Gold Hosting Tier, we need to change the Registry to allow Ministry teams to provision project sets in Gold without having to provisioning a matching project set in Gold DR.  Right now, it does not cost anything for a team to have a project set in Gold DR, but this situation changes when the cost recovery model is introduced.  

Definition of Done:
- Automatic provisioning of a project set in Gold DR is removed from the Registry. Instead, Gold DR cluster appears in the cluster dropdown. If the Gold DR cluster is selected in the dropdown, a mandatory field *Enter the license plate for your project set in Gold" appears on the form with a description: "All project sets in Gold DR must be matched to project sets in Gold. If you do not have a project set in Gold, provision it first, and then submit a provisioning request for the project set in Gold DR".  The Gold license plate field has a validation check to confirm that there is indeed an existing project set in Gold with the matching license plate. When the form is submitted, the provisioner create a project set in DR with the license plate to match the project set in Gold.

**Comment by funtigr** [comment]
@junminahn 
If the User checks the GoldDR checkbox, the Approval Admin sees it unchecked in the Request.
If Approval Admin checks and approves it, the message for Gold cluster is sent, but not for the GoldDR. 
If you visit the product after it is approved the checkbox is unchecked again. 
So looks like checkbox doesn't take any action and it's state is not saved.

**Comment by funtigr** [comment]
Now works as expected. 
Above the Create calls, below the deletion calls:
<img width="1488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3V4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f01e2fd18d44465394b85abfd1c7188e56aab524/image.png" alt="image.png" />
