### ISSUE TITLE
The status message should let teams know what is pending

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#224]
## Story

As a user, I would like to know what is pending in the Web UI.

## Description

Right now the Web UI just says "pending" when an edit request is in-flight. We would like to to say "Update Pending"

## Done When

The user sees "Update Pending" in the web UI.

**Comment by yhfreeman** [comment]
**Bugfix updated on the platform-registry-prod silver cluster: Jan 12, 2021
