### ISSUE TITLE
Deletion Feature doesn't work in the Dev Env

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2241]

**Comment by funtigr** [comment]
Now the Registry Accepts the Deletion of the Product and creates the Delete Request:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1RPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50f8093297803fcf5b68a3b0a51620b8a455e323/image.png" alt="image.png" />
