### ISSUE TITLE
add Expense Authority to product emails 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2245]
add Expense Authority to product emails

**Comment by funtigr** [comment]
Now we have the Expense Authority contact in the Product Emails:
<img width="918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXpWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--969a09a1be5e20df5897c7bc01218aca714187f6/image.png" alt="image.png" />
<img width="909" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNS9WQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--638ea7dc334bf35a439acb87eece3d7d503271d2/image.png" alt="image.png" />
<img width="907" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkRWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e726e6d2d5cd431d361cf1cbf9d05bc3c8d5fa5/image.png" alt="image.png" />
