### ISSUE TITLE
remove PROD checks for AWS roles and Expense Authority 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2246]
remove PROD checks for AWS roles and Expense Authority

**Comment by funtigr** [comment]
Expense Authority and AWS Roles are now displayed on Prod instance:
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGZjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d22472c1b578294d86a1c696607def135bc6872/image.png" alt="image.png" />
<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGpjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b182ed48a6e106bcd1b9dbcd999fffd2b333d135/image.png" alt="image.png" />
