### ISSUE TITLE
send email to expense authority 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2263]
send email to expense authority once a person become the expanse authority (created or edited product request) 

"Some thing that can be just as simple as Hello, You were are added as the expense authority to a sample AWS project, and may be include product details."

**Comment by funtigr** [comment]
New Expense Authority letter looks like this:
<img width="728" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c50ebb19205d9a94ce97f0eb7827d49d785e44f6/image.png" alt="image.png" />
