### ISSUE TITLE
Both PO and TC user names should be passed to NATS in lower case

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#227]
## Story

As a bot developer, I need the username for both the PO and TC to be in lower case.

## Description

The API should convert the PO and TC usernames to lower case in the NATS message.

## Done When

All messages sent to NATS have the usernames in lower case.

**Comment by yhfreeman** [comment]
**Updated on the platform-registry-prod silver cluster: Jan 28, 2021
