### ISSUE TITLE
hide history tab, fix prod create AWS-role user issue

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2278]
hide history tab, fix prod create AWS-role user issue

**Comment by funtigr** [comment]
History Tab is now hidden on Prod:
<img width="1439" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHJjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73d2c1a41fb476b53b1872ac97ee942a598c7f4e/image.png" alt="image.png" />
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHZjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96a4f473f9c56814b53030bfd39adefbd6efe30f/image.png" alt="image.png" />
AWS Roles are displayed:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHpjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc36c353cd124d4cd0c660179f77b4029de00b99/image.png" alt="image.png" />
