### ISSUE TITLE
The user should get notifications for quota change requests

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#228]
## Story

As a user, I would like to get notifications as my quota increase request progresses through the system.

## Description

When a user submits a quota change it works fine but they don't get any feedback as that it is accepted and when it is completed. It would be great to send an email to both the TC and PO when the request is accepted (started) and when the bots are complete.

## Done When

The PO and TC get email notification when request is received and then again when it completes.

**Comment by yhfreeman** [comment]
Still a relevant feature requested by PO.

**Comment by sbathgate** [comment]
In addition to users being notified of pending quota change requests, the Registry PO will now receive notifications of pending provisioning and edit requests to review in the registry dashboard.

**Comment by sbathgate** [comment]
This ticket has be completed as per PR #400
