### ISSUE TITLE
142. Products and Request Pages: Add Sort field

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2288]
Products and Request Pages: Add Sort field near by the filtering fields with a drop down list of sorting column names and order.

**Comment by funtigr** [comment]
Sorting works as expected. Lowercase names are sorted after the last of Uppercase but two types for one user is a rear case. It works good in intersection with filters. If you click into product sorted by (e.g.) description and then click back the by default is displayed (Last updated (A-Z)).
 <img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--427bf9e47d34ad1278b74aa50943a165e9edbb47/image.png" alt="image.png" />
