### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2309]
DoD:
Move the Login button to the top right corner instead of an avatar.
After the user logs in, the Home page/aka login page remains the same as a Home page. We add the Home tab. 

- [ ] 134). UI: Ryan L.: Login Page: Avatar makes User think they are logged in.

**Comment by funtigr** [comment]
After Users log out, they continue seeing the tabs of Public and Private clouds. 
If they click on Public/Private Cloud, they are redirected to previous version of login page, which after login redirects them to the Home Page again. And they need to repeat the action of clicking on Public/Private Cloud, which just now redirected them to login page (they may think it is a loop). 
<img width="1482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEFDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a9a37d584d68b10860b42e3f7f27c6107ca494f/image.png" alt="image.png" />

**Comment by junminahn** [comment]
@funtigr hm. is it consistent? I cannot reproduce it in any environments.
