### ISSUE TITLE
Frontend Implementation for the comments field for admins

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2312]
- [x] Add new tab to Product page called comments
- [x] Display all comments associated with that project
- [x] Create a text box that allows for creating comments

**Comment by funtigr** [comment]
@Amritpal-Nijjar 
1. The Comments tab content shows 401 error for private-admin role:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemRpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ea731455914bbc713f318307d69a2982de6d92c/image.png" alt="image.png" />

2. License plate and name of the tab are switched places. Other tabs have another order:
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemhpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65fe505e2a588ab74ac59ac2a4bd82f9396c3364/image.png" alt="image.png" />

Example on another tab:
<img width="1473" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenBpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fa9888b2c7d513753adac9988abc6b0c1e8349e/image.png" alt="image.png" />
