### ISSUE TITLE
110. Make Delete button instead of Options -> Delete.

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2314]
The new suggestion from Olena:
<img width="1278" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEFTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--221a73460fe7fd3edd3c1a7fcd0fefde4fca6c50/image.png" alt="image.png" />

I think the best option for now would be to show the Reprovision option/button only to Admins.
And add a task about retrial mechanism to implement later.

DoD:

- [ ] "Delete" button - for all users
- [ ] "Options" button > "Delete", "Reprovision" buttons for the Admins (admin, private-admin, public-admin)

**Comment by funtigr** [comment]
All roles except Global Admin can now see only Delete button:
<img width="1483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEJQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d60f186dd10821f9a97656dc3ac871a015b83c6c/image.png" alt="image.png" />

Global Admin sees Options-Menu:
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE5QQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e20aa1012da9ab02d099ae4939e1155bc901cbf4/image.png" alt="image.png" />
