### ISSUE TITLE
Excel Export Revision

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2322]
Add 3 columns into the Export CSV file for Private Cloud
- Total App Compute Quota (Cores)
- Total App Memory Quota (Gb)
- Total App Storage Quota (Gb). 
The columns would contain the sum of resource quota for all 4 namespaces within a project set. For example, for an X-Small project Set, the number in the Total App Compute Quota (Cores) column will be 2.

**Comment by funtigr** [comment]
The new Quota columns are present in the .csv document with all the lister parameters:
<img width="1286" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7f38ed9382b71af08a07b3dfdf864da38db1fd3/image.png" alt="image.png" />
