### ISSUE TITLE
Add Re-Provision feature (from Ian)

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#2326]
In Old Registry we had a Re-Provision feature. 
It was really convenient to "unstuck" the requests if they fail for some reason.
Ian asks to add this feature to the New Registry.

**Comment by IanKWatts** [comment]
Thanks, Artem.  It should be available only to registry administrators.  I imagine it would go well in the Options dropdown on the product detail page.  It should send the same JSON message to the NATS service as when an update is made.

**Comment by junminahn** [comment]
please move to prod once Ian's testing is done.

**Comment by IanKWatts** [comment]
I've tested this in the Test environment.  It can go to Prod now.  Thanks

**Comment by funtigr** [comment]
I asked Olena about the Deletion button and the "Options" menu.
She says she wants to not show Re-Provision option/button to the users. I will move to Prod this version of the code but my suggestion would be that in the future we could show this option/button to admins only. 
<img width="1278" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e0e461fbf344d84ecca6c48ae6e8e06950bbb57/image.png" alt="image.png" />

**Comment by IanKWatts** [comment]
Agreed - the reprovision option should only be available to administrators.

**Comment by funtigr** [comment]
Actually, my bad. It is displayed to Admins only, I've just checked.
An it's in Prod now.
