### ISSUE TITLE
For a create request, get rid of the comments field

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#2367]
Feedback indicates that there aren't many situations in which they need to share comments on approval of a creation request.

Current testing indicates that these comments are not being shared at all (for a creation approval).

DoD:

- [x] no comments field for a creation approval

**Comment by funtigr** [comment]
No need to comment on approval of Create Request now:
<img width="1296" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0tHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45f1552f988d46304edf2bdc99e38f61271c8b12/image.png" alt="image.png" />
