### ISSUE TITLE
Fix the ministry Editor Role permissions

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#2386]
Now if the User is a ministry-specific Editor he can change Contacts but can't change Quota.

**Comment by Kolezhanchik** [comment]
@funtigr  checked ministry admin role can edit quota

**Comment by funtigr** [comment]
> @funtigr checked ministry admin role can edit quota

Not on Dev. I have created a product which didn't have an Editor in the contacts but this Product had his ministry (PSSG). Then from Editor account confirmed that I can see the Product. When I tried to change the Quota I got error 500 from the server. 
If change contacts adding Editor to the Contacts it works. After Editor added himself to the contact only then he can change the Quotas.
