### ISSUE TITLE
Discuss the way to implement request page/route

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2391]
We have request page which is not available to users now. 
- Should it be available from history tab?
- Should we have unfolding component to show request details(changed quota or product info)

**Comment by Kolezhanchik** [comment]
discussed w/Alex request and history page, link to mockup https://www.figma.com/file/jsrhMxnmN4awqlbU8LuyuK/Quota-Redesign?type=design&node-id=66-1272&mode=design&t=yY2BkvkL8Wv9MYOU-0
