### ISSUE TITLE
77. UI: Products Page: Filtering by ministries and clusters - add option "All" after choosing one of them.

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2392]
77. UI: Products Page: Filtering by ministries doesn't provide option "All" after choosing one of them. (No live search by Ministry, though it is available for Cluster).

AND

Change visual sorting from A to Z to Z to A. 

AND

Highlight the "Clear Filters" button in blue for better visibility.

**Comment by funtigr** [comment]
All three fixes are implemented:
<img width="1475" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTlpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2011645b58b2cf78063dd5d52d5fc68943110e3/image.png" alt="image.png" />
