### ISSUE TITLE
Public API Endpoint

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2404]
Nick asked for possibility "to pull registry details out (like the csv export(the product name, description, PO, TL and license plate)) with an API call. Some other groups are asking. i think more for pulling details into larger asset management systems for ministries or corporately."

To clarify with Nick:

-  do they need filtering options? If so, what kind of filters they need? 
- who are the users for the API end point? (admin role?)

after clarification with Nick: 
Any authenticated user (idir) with any user role would be able to download (.CSV) whole list of products we have in registry with limited info, like:

- product name
- product description
- PO first name last name
- TL/s first name last name
- cluster
- ministry
- namespace ID (license plate)

**Comment by junminahn** [comment]
I just confirmed with Nick that this involves an API endpoint for `machine-to-machine` communication. We will need a process to create a service account in Keycloak for each user who wants to access the API endpoints.

**Comment by funtigr** [comment]
The API endpoints are created and provide the data about products:
<img width="1118" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHdnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed130fd0de8821df4f40b7f05b9fc7bb8d921469/image.png" alt="image.png" />

To get the Service Account, the user needs to use the web-interface, located in Profile icon menu:
<img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUVnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7987460a9516835edc56505b584fa83991b50390/image.png" alt="image.png" />

To delete Service Account user can use Delete button. Click on the Delete button deletes the Service account.

The account works for fetching public-cloud products info as well:
<img width="1167" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88f54cf2c9354c2b0bd26031241bfe91b562ed89/image.png" alt="image.png" />
