### ISSUE TITLE
Implement API Endpoint to GET Provisioned Projects (SPIKE)

### ISSUE THREAD

**Issue by j-pye** [bcgov/platform-services-registry#241]
**Describe the issue**
As a bot, I would like to be able to synchronize the data between the database and the github repository. 

**Additional context**
GET Requests

> This is required to fix the current ArgoCD issue. (Link coming soon)

**Definition of done**
- [x] API Endpoint created to get the ids of all of the provisioned projects in the Registry Database
- [x] API Endpoint created to get the JSON/NATS message for the provisioned project profile id without any pending changes
- [ ] PR Reviewed
- [ ] Promoted to Test
- [ ] Promoted to Prod

**Comment by yhfreeman** [comment]
"API Endpoint created to get the JSON/NATS message for the provisioned project profile id without any pending changes"
has been updated to
"API Endpoint created to get the JSON/NATS message for the provisioned project profile id with pending EDIT changes if there are any" to reflect:

> yuhan.freeman
5:17 PM
So does it work for you justin.pye if all provisioned profiles will indeed include those that are under pending EDIT, but when you query those, the registry api will serve you the bot json with requested version? This way, we just need to manually take care of all the CREATE pending ones.

> justin.pye
admin user
5:22 PM
Yes.

**Comment by yhfreeman** [comment]
**released on the platform-registry-prod silver cluster: December 16, 2020
