### ISSUE TITLE
Build a check for an existing license plate when generating a new one

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#243]
In avoid to avoid a collision when the same license plate name is created in multiple clusters in the OCP 4 platform , build an API lookup function to perform a duplicate check to avoid a namespace collision and have the  project provisioner call the function to check for an existing license plate when it generates a new license plate for a new project.

This feature becomes critical when we start using the Project Registry to provision namespaces in multiple clusters in the OCP 4 Platform.

**Comment by mitovskaol** [comment]
@sbathgate I believe this feature has already been implemented in another ticket. If so, please free to close the ticket.

**Comment by sbathgate** [comment]
Good catch, yes this ticket was achieved with PR #409
