### ISSUE TITLE
Scenario 1 for Email refactoring/improving according to docs (Private Cloud)

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2431]
- [x] Scenario 1, Provisioning request email sent to admins is missing a period for the second sentence.

- [x] Scenario 1, UI has a comment field for approving a create request, these comments do not show in the provisioned email. Comments for the email are not in the documentation either. In conclusion we get rid of the comments box for approving a create request

- [x] Scenario 1, Update the emails documentation for a create request rejection, we will add the product name to the subject, and not have product details in the email body. This is to be consistent with the previous emails of the registry.

- [x] Scenario 1, For the provisioned email that gets sent to the users add this link: https://developer.gov.bc.ca/docs/default/component/chefs-techdocs/About/SoAR-and-Compliance/#advanced-cluster-security-acs

**Comment by funtigr** [comment]
Now the point 3 is fixed: 
<img width="1252" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f0478490b5326bc2cd8273f236aad1741af9331/image.png" alt="image.png" />
