### ISSUE TITLE
Scenario #2 for Email refactoring/improving according to docs (Private Cloud)

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2432]
- [x] Scenario 2, "Edit request received" is the subject line for both emails received by user and admin, change the subject for the email admins

- [x] Scenario 2, The second sentence for an edit request email needs a period

- [x] Scenario 2, Comments do not appear for the admins for an edit request

- [x] Scenario 2, Admins do not currently see the current and requests quotas for the edit request

- [x] Scenario 2, Edit request approval is sending a product provisioned email, this is the wrong email. We might have to create a new template for the scenario of approving a edit request with resource quota increase.

- [x] Scenario 2, Edit request approved with resource increase documentation seems to be wrong, and needs to be updated. Update the documentation to get rid of: Security Tools Info, Artifactory Info, Vault Info, ACS Info, Sysdig Info.

- [x] Scenario 2, Rejecting a resource quota increase documentation should have the current and requested quotas. The email needs to be updated to reflect this documentation change.

**Comment by funtigr** [comment]
Subject for Admins fixed:
<img width="792" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0dJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cdbef8fc8bf3769d5a9e8459de21ed27ab8641d/image.png" alt="image.png" />

Period in second sentence fixed.
<img width="795" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1dJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cddd7ef28ee3cfcf2bbe4eb2688306a8e2902d7/image.png" alt="image.png" />

User comment in Admin email: fixed:
<img width="729" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e7a4bb076d47a1cba21ef406380d7e516f5b6a2/image.png" alt="image.png" />

Admins don't see quotas: fixed:
<img width="739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3FJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2370d3c7559cb9d68f5baf65c5198a5eac99706/image.png" alt="image.png" />

New email for Approved Edit Request with Quota and without excessive info is implemented:
<img width="725" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeCtJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--794466677ec422bca83c123a1bdfecd4c769e9d0/image.png" alt="image.png" />

New email for Rejected Edit Request with Quota: implemented:
<img width="730" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1JQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26b38bf5c6f2cbd83192b7c0e24cbda9ce820957/image.png" alt="image.png" />
