### ISSUE TITLE
Add documentation that handles the scenario of a mixed request (Private Cloud)

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2433]
- [ ] 1. Add documentation that handles the scenario of a mixed request (quota increase, plus something else changed like contacts)
- [ ] 2. Add a section to the email template about a change request "this request/change was made by [insert a name of the person who made a request]". We can even add this section to the email about creating a product stating who created this product.

**Comment by funtigr** [comment]
Pull Request link: https://github.com/bcgov/platform-services-registry/pull/2546
