### ISSUE TITLE
Scenario #3 - Emails refactoring/improving according to docs (Private Cloud)

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2434]
- [x] 13). Scenario 3, needs to be updated, as resource changes (upgrades and downgrades) go through an approval process
- [x] 14). Talk to Luke about auto approve for quota downgrades -related to point 13)
- [x] 15). Scenario 3. Edit Request: No Resource Quota Increase: is sending emails to admins, this should not be the case. The wording for the email needs to be revisited.
- [x] 16). Scenario 3, update documentation, should send "request received email" to users (mention a follow up email will be sent once changes have been provisioned), and then after provisioning, a summary of the changes email is sent.

**Comment by funtigr** [comment]
Automatic approve of downgrade quota - implemented.
Approval admin receive email if non-quota changes are made: fixed, now they don't.
Wording: fixed:
<img width="731" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW1KQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ee576915cdee223158997a53413ab4416d69066/image.png" alt="image.png" />
The "Request Submitted" email is received. It has new wording and all the changed data:
<img width="728" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXVKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67eb967ab22689ddeb8c50db24b0e6cbbc068fc2/image.png" alt="image.png" />

The second email after provisioning is removed.
