### ISSUE TITLE
Scenario #4 - Emails refactoring/improving according to docs (Private Cloud)

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2435]
- [x] 17). Scenario 4, admin did not receive email.
- [x] 18). Scenario 4, Namespace details is in the email but not in the documentation. Update the documentation
- [x] 19). Scenario 4, the email is good, update the documentation to not have product details
- [x] 20). Scenario 4, approving a delete request has comments box, get rid of this comments box entirely.
- [x] 21). Scenario 4, Approving a delete request sends a new product provisioned email, instead have Product Details (Name, Description, Ministry, Contacts of PO/TL(s)) and Namespace details, so we must update the documentation.

**Comment by funtigr** [comment]
Approval Admin received the email:
<img width="731" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGFKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf9f9372d0d54b74111abe2298ffc9612b414b19/image.png" alt="image.png" />

Approval of Deletion doesn't need a comment:
<img width="1354" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFdKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c8be7760545d25ef27172c702743163ef12a4f6/image.png" alt="image.png" />
