### ISSUE TITLE
Add project quota size field to the project report

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#244]
As a Platform Product Owner I would like to see what quota sizes the projects in the OCP 4 platform have. Currently this information is missing from the extract report.

DoD:
 - [x] The quota size field added to the project extract report to indicate whether a project has small, medium or large quota sizes.

**Comment by yhfreeman** [comment]
**Updated on the platform-registry-prod silver cluster: Jan 28, 2021
