### ISSUE TITLE
The products Updated field has 3 or more hours difference in timezone with Pacific Time

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#2459]
**Description**:
The products Updated field has 3 or more hours difference in timezone with Pacific Time.
Example screenshot shows that it's 9:42pm, Apr 9 in Victoria but freshly updated Product shows it's edited on Apr 10:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemRLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6f5fe4ef113d2a94cb444c1461f30f507f86790/image.png" alt="image.png" />

**Comment by Iryna-Kaplun** [comment]
Artem will check if this is still a relevant issue.

**Comment by funtigr** [comment]
This issue is fixed.
