### ISSUE TITLE
let Responsibility Centre (RC) (Account Coding) filed contain letters 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2501]
change RegExp
change info message

**Comment by funtigr** [comment]
<img width="1484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1o1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d5c7b899f5ac92481a6959d05e8867933aac8c6/image.png" alt="image.png" />
