### ISSUE TITLE
Create Analyzer, public-analyzer and private-analyzer roles

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2516]
Create Analyzer, public-analyzer and private-analyzer roles 

make sure these roles are permitted to view analytics dashboards and  remove permission to view analytics dashboard  according to roles spreadsheet 
 https://docs.google.com/spreadsheets/d/1XgjCgXGJ46qZs-dBRs6EnDtG4UC3jPsbB-QQ0Dl4ihQ/edit#gid=377111090,

**Comment by funtigr** [comment]
Now people with analyzer roles have access to analytics:
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf7e4c8a37de8a1d8b9b096d1e0107571107e201/image.png" alt="image.png" />

Private analyzers have this:
<img width="1483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzZHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9444bf8e543c073e4ed3800637fba06070f0c6c/image.png" alt="image.png" />

And Public Analyzers this: 
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKytHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--282017cfb365cc2ee0ca931427d84ea67bd587d3/image.png" alt="image.png" />
