### ISSUE TITLE
Comment bubble UI implementation

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#2530]
**Purpose**
To create a component that can display user comments that looks like the mockup

<img width="1640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeENDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a334983a776c8808bef850b5f32a811feed2cece/Screenshot%202024-04-22%20at%202.58.15%20PM.png" alt="Screenshot 2024-04-22 at 2.58.15 PM.png" />

<img width="1640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEtDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c96f541ed24110c8718787aa2b73b2ad53e9088/Screenshot%202024-04-22%20at%203.00.14%20PM.png" alt="Screenshot 2024-04-22 at 3.00.14 PM.png" />

**DoD:**

- [ ] Comments are displayed like the one in the mockup

**Comment by Amritpal-Nijjar** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL21nQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--497d1d678eb482f90abce1b8babee503649ca231/Screenshot%202024-04-29%20at%201.03.36%20PM.png" alt="Screenshot 2024-04-29 at 1.03.36 PM.png" />

**Comment by funtigr** [comment]
Now looks like this:
<img width="1473" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2FuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--858aa831f5af956cb45a66d6818f6530c475360e/image.png" alt="image.png" />
