### ISSUE TITLE
History Tab - public cloud product

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2538]
After a meeting with Prabhu, we decided to impalement the same way as it is for private and continue from there

**Comment by funtigr** [comment]
The History tab looks like this:
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUtVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd4039592473e0064d2abd60306bd1796beb1430/image.png" alt="image.png" />

When you click "See request page" the fields are not interactable to show that it is immutable:
<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVdVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6caf15bf1df35ff07db600e6d6f29b6f72e5d03e/image.png" alt="image.png" />
