### ISSUE TITLE
store user image into DB

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2556]

**Comment by funtigr** [comment]
Works as expected:
<img width="1485" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNks1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e63957e411b5c294c4532f8ba11f37d4f1b7d5a/image.png" alt="image.png" />
