### ISSUE TITLE
[Refactoring] Convert list pages to client components (Public Product Dashboard)

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2557]
We want to transform list pages into client components to enhance page loading and eliminate inconsistencies with query parameters.
- Public Product Dashboard: https://dev-pltsvc.apps.silver.devops.gov.bc.ca/public-cloud/products/all

**Comment by funtigr** [comment]
Works great except same issues as in #2528 which will be fixed in that one.
