### ISSUE TITLE
[Refactoring] Convert list pages to client components (Private Request Dashboard)

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2559]
We want to transform list pages into client components to enhance page loading and eliminate inconsistencies with query parameters.
- Private Request Dashboard: https://dev-pltsvc.apps.silver.devops.gov.bc.ca/private-cloud/requests/active

**Comment by funtigr** [comment]
Works great except same issues as in #2528 which will be fixed in that one.
