### ISSUE TITLE
[Refactoring] Convert list pages to client components (Public Request Dashboard)

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2561]
We want to transform list pages into client components to enhance page loading and eliminate inconsistencies with query parameters.
- Public Request Dashboard: https://dev-pltsvc.apps.silver.devops.gov.bc.ca/public-cloud/requests/active

**Comment by funtigr** [comment]
@junminahn 
On Dev I can't visit page 4 with 5 products per page and page 2 with 10 or more products per page. 
Looks like some request is in conflict with new routes:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77698f06dd919dcbc6a597c82a1397d6f9672131/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Fixed:
[Uploading... image.png]
