### ISSUE TITLE
User session timeouts

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2565]
We want to implement a feature where user sessions automatically expire after a specified period of inactivity within the app. Achieving this requires delving into the functionality of `next-auth` and configuring session expiry settings accordingly. Ideally, we'd like to extend user sessions while they actively engage with the app, ensuring that sessions expire only when users cease app usage.

**Comment by funtigr** [comment]
Checked on test account. The session was 24 hours.
