### ISSUE TITLE
Request schema updates

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2566]
We want to enhance the maintainability of the app by updating the `Request` schema. This task involves the following steps:
1. Introducing a new field, `originalDataId`, to preserve product data during request creation.
2. Renaming existing fields: `userRequestedProjectId` to `requestDataId` and `requestedProjectId` to `decisionDataId`.
3. Modifying the codebase to accommodate the new field names.
4. Crafting a data migration script to transfer values from the old fields to the new ones.

**Comment by funtigr** [comment]
For now it was decided to make field not required, so it is ok that current products don't have it. 
The population will not be done for new products for now as well.
