### ISSUE TITLE
Edit Functionality for Admin Comments

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2568]

**Comment by Amritpal-Nijjar** [comment]
<img width="1034" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekMvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc91a63449bdfe4c13a8b912bd1b584b4935edcd/Screenshot%202024-05-06%20at%2011.00.12%20AM.png" alt="Screenshot 2024-05-06 at 11.00.12 AM.png" />
<img width="1342" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekcvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f96617b7fb307156ab0074c109e6f8f0c0dc0f6d/Screenshot%202024-05-06%20at%2011.00.37%20AM.png" alt="Screenshot 2024-05-06 at 11.00.37 AM.png" />

<img width="1141" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeksvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a888acd6c843664dbc91fd94dc45fc35bddbcdd6/Screenshot%202024-05-06%20at%2011.01.41%20AM.png" alt="Screenshot 2024-05-06 at 11.01.41 AM.png" />
