### ISSUE TITLE
Delete Functionality for Admin Comments

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2569]
DoD:
- a comment can be deleted by an author of the comment

**Comment by Amritpal-Nijjar** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHFxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50dffc58dd9bf1be9cac9fb66bbf25809c892cbb/Screenshot%202024-04-30%20at%204.03.14%20PM.png" alt="Screenshot 2024-04-30 at 4.03.14 PM.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHVxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--798cbf7bd40c5577b6930599ed5ddba5eccb944d/Screenshot%202024-04-30%20at%204.03.23%20PM.png" alt="Screenshot 2024-04-30 at 4.03.23 PM.png" />
<img width="1674" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b6c82dc6d2378f48b3241e7e9cb5d2cb2655800/Screenshot%202024-04-30%20at%204.03.56%20PM.png" alt="Screenshot 2024-04-30 at 4.03.56 PM.png" />

**Comment by funtigr** [comment]
The Delete Functionality works as expected.
The Admin that left a comment can delete their comments.
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0NyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4baf55641c949b995faaa7545fb3f32af296811a/image.png" alt="image.png" />
