### ISSUE TITLE
Public Cloud - Email Scenarios #1

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2571]
**Public Cloud**

- [x] Update Public Cloud email documentation for the email scenario of expense authority
- [x] Scenario 1, admin receives email for a create request that says Namespace details, instead of Landing Zone Details, also is missing Budget, and account coding, also the footer needs to be removed
- [x] Scenario 1, user receives email that has a weird footer info, needs to be updated.
- [x] Scenario 1, related to point 1, add documentation that mentions that the expense authority gets an email upon product approval
- [x] Check all emails for a double mention of Cloud Pathfinder team in the footers
- [x] Get rid of the comments box for when approving a create request

**Comment by funtigr** [comment]
1. Landing Zone details instead Namespace: Fixed:
<img width="971" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzJuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1aa3e4827c4ed90080eafd885a4c8ab25a318d00/image.png" alt="image.png" />

2. Weird info in footer: Fixed:
<img width="968" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzZuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b6cfc4bf33317a5211160ad374988ec2572d71e/image.png" alt="image.png" />

3. Approval without comment: implemented: 
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKytuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb5a2f5756ad8aafb27ce7de04410bc485571cfc/image.png" alt="image.png" />

Documentation updated, but Expense Authority email is not received.
