### ISSUE TITLE
private email visual bug 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2573]
add a line break between the Product Description text and the License Plate header

<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzZWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa2989ab78170bc2dcd0cf6efa03e8e06fef0e70/image.png" alt="image.png" />

**Comment by funtigr** [comment]
We don't show License Plate in Private Cloud emails. But we do in the Public Cloud emails. 
It is fixed for Public Cloud emails. 
<img width="974" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK09uQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8263a828c8f97a52c402621feb2f8247198066e/image.png" alt="image.png" />

I added two tasks: one about adding license plate to the Private Cloud emails as it is the most universal ID of the product throughout the whole system; second about adding the gap between Product Name and Product Description, in case a product has a long name.
