### ISSUE TITLE
Review email scenarios live session [Public Cloud]

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2575]

**Comment by Amritpal-Nijjar** [comment]
Scenario 1) Admin email does not mention who actioned the request
Scenario 1) Admin email has footer (wrong footer) remove this footer
When a public cloud user edits their product, they get wording that asks "why are you making these changes" we don't need this wording, as the edit changes are not reviewed by an admin.
Scenario 3) User should receive email with their product name in the email subject.
Scenario 3) Admin email does not have the sentence on who actioned the request, include this in the email.
Scenario 3) Change the approve email subject to say "acknowledged" not approved. This makes it consistent with the email body wording.
All Scenarios, make sure that the product name is in the email subject AND the email body.
e.g "Delete request for [product name]"
