### ISSUE TITLE
127. Add a section to the email template about who made a change request or created a product

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2576]
Add a section to the email template about a change request "this request/change was made by [insert a name of the person who made a request]". We can even add this section to the email about creating a product stating who created this product.

DoD:

- [x] show the name of person who created a product only in the initial email when product was created (emails for provision, submission and approval admin) 
- [x]  show the name of person who made a request in the email confirmation of that request

**Comment by Amritpal-Nijjar** [comment]
edit, create, and delete request emails now have a "Actioned by..." line by grabbing the the user name from the current session.

**Comment by funtigr** [comment]
Now the listed above email have this field:
<img width="973" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ZZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e7e346e85e7e3335405422de6dd169ffd8c3364/image.png" alt="image.png" />

On an email check session we decided to add this thing also to Approval Admins email which is mentioned in a separate task:
https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/2572
