### ISSUE TITLE
Show Rejected Edit/Delete requests in the History Tab

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#2579]
**Description**:
Show Rejected Edit/Delete requests in the History Tab

Update:
I see the comment about the Edit so we are good on that front.

About the Delete Request: My expectation is to show it while it's in Reviewing or Pending state. Because it can be reviewed for a while.

**Comment by Kolezhanchik** [comment]
Rejected Edit/Delete requests in the History Tab are shown 
<img width="1478" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHFWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3aeb5bd4c1e3ac5e8478f617ebe1980f7cb8e58e/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Updated the description after a comment above.
