### ISSUE TITLE
Lighter AWS project set (1 to 4 accounts)

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/platform-services-registry#2597]
As a Ministry Team, I want lighter project set options, so that I don't have to pay for 4 accounts for a simpler usage need.

_Context: We have noticed the 4 project set single option could be a cost deterrent to starting a project set for teams willing to leverage public cloud for only a storage instance that would may cost under $50. The idea of having a $300 CAD minimum baseline fee prevents certain teams to leverage public cloud._

**Acceptance Criteria:**

1. In the Product Registry, under Public Cloud Landing Zones > "+ Request a new product" > Below Ministry & Cloud Service Provider fields, add another field titled "Accounts to create".
2. That field should offer 4 checkboxes in the following order: "Production Account"; " Development Account"; "Test Account"; "Tools Account".
3. Only "Production Account" Should be toggled selected by default, the other 3 are unselected.
4. There is a "Select/Unselect All" Checkbox besides or below the field title that allows to select all (select 4 accounts) or unselect all (Unselects all accounts except for Production Account).
5. It is possible to unselect "Production Account" only if another account is also selected.
6. An explanation text should display the following information "Select how many accounts you want for your project set. ⚠️ Important note: It is not possible to remove accounts once created in your project set. You are free to add account later, after your project set creation, but you will not have the ability to remove created accounts."
7. When reopening an existing project set, it is possible to select accounts that were previously not created.
8. When reopening an existing project set, already created accounts are checked in a manner that can't be unchecked, and marked as grey or similar visual clue to indicate they are not modifiable.
9. When an account is not selected, it should show in Section 4. Project Budget, in grey, not modifiable, and as $0, both in the creation phase of the project set, and when reopening a project set page. This field evolves dynamically as the account is selected (becomes modifiable and normal colour) or unselected (non-modifiable and grey).
10. That information is dynamically updated and relayed to the Public Cloud provisioner.

**Comment by junminahn** [comment]
```
        "current_environments": {
            "development": true,
            "test": true,
            "production": true,
            "tools": true
        },
        "requested_environments": {
            "development": true,
            "test": true,
            "production": true,
            "tools": true
        }, 
```

**Comment by funtigr** [comment]
- Now Public Cloud Create Page and Products have a section called 'Account to create'.
- It has four checkboxes each for one environment.
- Prod is checked by default. 
- Buttons 'Select All' and 'Select None' have respected functions.
- If one or more checkboxes are set and provisioned, they become immutable and buttons can't change them as well.
- There is a disclaimer displayed saying about above.
<img width="1508" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWdkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66aaea0312fdcc31c7d92b737140a4b5cc43b852/image.png" alt="image.png" />

If nothing is checked, the 'Project Budget' session is greyed out and has 50$ in every field except for Total Estimated average, which is 0:
<img width="1515" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b9b422830ccd01e32675854bd0da28ceb5f4afc/image.png" alt="image.png" />
