### ISSUE TITLE
Add an Expense Authority Notification email (Scenario 1 in docs)

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#2639]
**Description**:
Add an Expense Authority Notification email (Scenario 1 in docs) which would be sent to the Expense Authority contact after approval.

**Comment by Kolezhanchik** [comment]
tested it out and got email as EA 
<img width="791" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2VxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--490ce7ff60b05dc262e37bda6ffae7fc35a37fd7/image.png" alt="image.png" />
test with @funtigr on dev, also EA person got email as expected
