### ISSUE TITLE
Resolve web portal unauth 401 issue after token gets refreshed

### ISSUE THREAD

**Issue by yhfreeman** [bcgov/platform-services-registry#266]
**Describe the issue**
For those authenticated users that idle around the website >= 5mins long, any requests made after the idle will be marked as unauthorized, which is the issue we have. Instead of suggesting users to log out and log in, the bugfix should be to fix the behaviours of the react app so it uses / tracks the refreshed token.

**Definition of done**
When the unauth 401 issue after token gets refreshed is resolved.

**Comment by rloisell** [comment]
![Screen Shot 2021-01-12 at 2.26.20 AM.png](https://images.zenhubusercontent.com/5ffde8bd79760cb965381db0/a0146299-6c6c-48d1-bac1-80de22e68512)

This issue (even when aware of it) is a major time waste. Fighting constant time outs it took over an hour to submit 7 requests that were mostly copy and past from an XLS with some minor edits to meet the form validation. 

For those that are not technical in nature and whom are completing the form will be perplexed by the error as there is no indication as to the cause (as all forms validation has been met).

**Comment by yhfreeman** [comment]
Thanks for reaffirming this issue @rloisell - please note the bug fix under PR #272 will be available in production soon.
There is some level of indication as we currently do print the error message to users upon this issue.

**Comment by yhfreeman** [comment]
**Bugfix updated on the platform-registry-prod silver cluster: Jan 12, 2021

**Comment by yhfreeman** [comment]
@mitovskaol ^ thanks

**Comment by rloisell** [comment]
Thanks for resolving this issue @yhfreeman - yes, you do report a 401 error, but to a non-technical person (such as a product owner) this error means almost nothing. Thankfully a resolution has been applied and I can test with more submissions this evening.
