### ISSUE TITLE
[Email Sandbox] Deploy Mail service to view emails in dev environment

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2700]
### Description
We are aiming to integrate MailPit into both the local development and live development environments. This email sandbox will allow developers to safely view and inspect emails sent from the application without the risk of sending them to actual recipients. It will also enable the evaluation of HTML content within emails and facilitate testing through API endpoints.

### Technical Details
- MailPit Setup
- Website: [MailPit](https://mailpit.axllent.org/)
- GitHub Repository: [MailPit GitHub](https://github.com/axllent/mailpit)
 
### Notes
- Integrate MailPit’s API to programmatically retrieve emails for automated testing

### Definition of Done (DOD)
- [x] MailPit is successfully integrated into the local and live development environments.
- [x] Application emails are captured in MailPit’s inbox.
- [x] MailPit API is available for testing.

**Comment by funtigr** [comment]
The MailPit is deployed to Dev and receives the emails:
<img width="1467" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhtQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ee58bc6436c20ed7b083405aae33c81cf6017d7/image.png" alt="image.png" />
