### ISSUE TITLE
Rename the In Progress tab into Request + Remove the Arrow Icon in all the Dashboards + Fix the Table Alignment for PO and TL Names 

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2712]
- In Progress tab has both active and resolved requests so it doesn't make sense to call this tab In Progress as it doesn't cover the resolved requests.
- The arrow icon in the tables beside the "copy license" icon doesn't have any useful functionality and confuses users. 
- Table is not aligned when there are different lengths of Product, PO and TL names. See the screenshot: 
<img width="741" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmJGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba3d365a06bded5e1f0238f0d29ab51ea8db1a8a/image%20%2832%29.png" alt="image (32).png" />

DoD:
- The tab is renamed from In Progress to Request 
- The arrow icon is removed
- The table stays aligned regardless of the length of Product, PO and TL names

**Comment by funtigr** [comment]
All three fixed/implemented:
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenZZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c906e0e8d0211c239e2c1ce25555c53ba072b22/image.png" alt="image.png" />
