### ISSUE TITLE
Update the CSV downloaded file format

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2713]
CSV downloaded file:

145). CSV: Luke: Acronyms in .csv downloaded file instead of full ministry names. The request is to replace the acronym with the full Ministry name.

146). CSV: Luke: Make column names readable.

**Comment by funtigr** [comment]
Both feature implemented:
<img width="1394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEhZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba1a615672ecfa44d0575f349bf5468d09b39f1f/image.png" alt="image.png" />

@junminahn 
The column with Secondary TL name is still appearing in Pascal Case (without spaces), visible on the screenshot above.
