### ISSUE TITLE
Display User Role in UI (QOL)

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#2721]
**Describe the issue**
Currently there is no way for a user to know what role they currently have assigned to them. Without doing some experimentation/tests to deduce what role they have, they would have to use the inspect element tool to look at the session and read the code directly.

**Rational/Why**
We want to have a user friendly action to display to the user what role they currently have. As it leads to easier communication regarding roles.

**Definition of done/Acceptance Criteria**

- [x] Add a drop down menu option where the user profile currently exists to view "Profile"
- [x] Display in a dialog box information about the user: Name, Email, Role, and Permissions

**Comment by Amritpal-Nijjar** [comment]
<img width="1075" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de5b12f99c09be306e9eee215350237102aff19e/Screenshot%202024-05-08%20at%205.51.04%20PM.png" alt="Screenshot 2024-05-08 at 5.51.04 PM.png" />

**Comment by Amritpal-Nijjar** [comment]
<img width="617" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccc8cf156261a0765ae4344c2a14821dbd4c3b76/Screenshot%202024-05-09%20at%204.02.31%20PM.png" alt="Screenshot 2024-05-09 at 4.02.31 PM.png" />

**Comment by funtigr** [comment]
Works as expected:
Note: maybe we should show that public-admin can Create Private Cloud products and private-admin can Create Public Clout products.
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFhZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e9ef86e13fff7976ac67def3d594212a51041a3/image.png" alt="image.png" />

<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFRZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9305dcb39fe6a530de068317d0dd2834d8153aa9/image.png" alt="image.png" />
