### ISSUE TITLE
Show a UI error if users try to submit a request not mentioning themselves

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#2726]
**Description**:
Now if users try to submit a Create or Edit request not mentioning themselves the Submit button would not work, but no errors would be displayed.
We need to add error to let users know that they need to leave themselves in the product in order to submit.

**Comment by junminahn** [comment]
Great, I was planning to draft a similar ticket for this issue. Let's broaden the scope of this ticket to encompass displaying all errors encountered in responses from API endpoints. Utilizing the `tanstack-query` library, we can consolidate the logic in one central location.

**Comment by junminahn** [comment]
@Amritpal-Nijjar I did review this PR, but does it cover all `useMutation` API calls in the codebase?

**Comment by Amritpal-Nijjar** [comment]
I just checked and there are quite a few `useMutation` API calls that do not have error handling or notification, I will create a separate ticket for it. Each use will need to be evaluated to see what notification we want to show. For example, a success toast on product create is redundant as we have modals for that action. Do you recommend creating a common component for this as much of will look like this: <img width="870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEE5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01e1e564651fe3e7d4e150cdb2499c0f7dc5fce0/Screenshot%202024-06-05%20at%2011.42.22%20AM.png" alt="Screenshot 2024-06-05 at 11.42.22 AM.png" />

**Comment by funtigr** [comment]
<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjQ5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af01f04c2e74f31aa10b9c9efc8b746a56a5df78/image.png" alt="image.png" />
