### ISSUE TITLE
wording for public cloud budget

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2734]
Prabhu asked - "I just have a small request in the registry, In the Budget sections we say that there is a base charge of USD 400-600 per month for each project set created, Can we change that to 200-300 $ USD ?"

<img width="1847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnJMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97a1ea4840c724e5e7443ce78335098af574468e/image.png" alt="image.png" />

**Comment by funtigr** [comment]
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03e0e839d1e4aa7628925006c625e6b03b2d42d0/image.png" alt="image.png" />
