### ISSUE TITLE
Submit Edit Request Fails

### ISSUE THREAD

**Issue by NereidLake** [bcgov/platform-services-registry#2748]
![image](https://github.com/bcgov/platform-services-registry/assets/34045298/9b49d18c-2a8c-47c4-ac54-d0cb9c083a1e)

**Comment by Kolezhanchik** [comment]
send an email(and MSTeams msg) to nereid.lake@gov.bc.ca asking for online meeting to identify the issue

**Comment by Iryna-Kaplun** [comment]
This error couldn't be replicated. It's hard to determine what kind of edit request this contact was trying to do. The ticket will be closed.
