### ISSUE TITLE
Generic button component

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2759]
1. Step 1: research all button types used in the application.
2. Step 2: create `Maintine theme` to support various colors that required for our application.
3. Step 3: create a example page to display all possible button types.

- References
  - https://mantine.dev/core/button/?t=styles-api
  - https://mantine.dev/styles/styles-api/
  - https://getbootstrap.com/docs/5.3/components/buttons/
 
<img width="756" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM09mQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8213f3398926ebd008def9026ba64193f356a3c8/image.png" alt="image.png" />

Size: `2xs, xs, sm, base, lg, xl, 2xl, 3xl, 4xl`

- Code snippet
`mantine-theme.ts`
```
'use client';

import {
  Button,
  virtualColor,
  createTheme,
  Group,
  MantineProvider,
  defaultVariantColorsResolver,
  VariantColorsResolver,
  parseThemeColor,
  rem,
  rgba,
  darken,
} from '@mantine/core';

console.log(virtualColor({ name: 'primary', light: 'blue', dark: 'red' }));

// See https://mantine.dev/styles/styles-api/#styles-api-selectors
// See https://mantine.dev/styles/variants-sizes/#adding-custom-variants
export const theme = createTheme({
  colors: {
    primary: [
      '#FFBF3E',
      '#FFBF3E',
      '#FFBF3E',
      '#FFBF3E',
      '#FFBF3E',
      '#FFBF3E',
      '#FFBF3E',
      '#FFBF3E',
      '#FFBF3E',
      '#FFBF3E',
    ],
  },
  components: {
    Button: Button.extend({
      vars: (_theme, props) => {
        console.log('props', _theme, props);
        if (props.variant === 'light222') {
          return {
            root: {
              '--button-height': rem(120),
              '--button-padding-x': rem(30),
              '--button-fz': rem(24),
            },
          };
        }

        if (props.size === 'xxl') {
          return {
            root: {
              '--button-height': rem(60),
              '--button-padding-x': rem(30),
              '--button-fz': rem(24),
            },
          };
        }

        if (props.size === 'xxs') {
          return {
            root: {
              '--button-height': rem(24),
              '--button-padding-x': rem(10),
              '--button-fz': rem(10),
            },
          };
        }

        return { root: {} };
      },
      classNames: {
        // root: 'my-root-class',
        // label: 'my-label-class',
        // inner: 'my-inner-class',
      },
      styles: {
        // root: { backgroundColor: 'red' },
        // label: { color: 'blue' },
        // inner: { fontSize: 20 },
      },
    }),
  },
});
```

```
<MantineProvider withGlobalClasses={false} withCssVariables theme={{}}>
```

**Comment by Amritpal-Nijjar** [comment]
https://www.figma.com/file/jsrhMxnmN4awqlbU8LuyuK/Quota-Redesign?type=design&node-id=31-846&mode=design&t=ws2pL0CvTG4X2Bpi-0

**Comment by Amritpal-Nijjar** [comment]
https://www.npmjs.com/package/@bcgov/design-system-react-components

**Comment by funtigr** [comment]
I have made a page with examples of most buttons. Working on theme now:
<img width="1473" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzNUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--348ea8136e77a0754f2aaf68074e6130b3649b14/image.png" alt="image.png" />

Below are the screenshots of all buttons to rewrite them with the theme in the future:
1. Login button:
<img width="123" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy9UQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--541567ccdb9235469be89ca02cfa93b81adb676c/image.png" alt="image.png" />

2. Close roles popup button:
<img width="703" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEhUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49ddce169bf0f6c3646b8d53b18b2e09eb585d19/image.png" alt="image.png" />

3. Request a Service Account button:
<img width="504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFBUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ce966479d7794cf89f147dd57a71267b0d2ffbd/image.png" alt="image.png" />

4. Delete the Service Account button:
<img width="285" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFRUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bae757b2ac8575083801a364ab741a37efab77d3/image.png" alt="image.png" />

5. Confirm Service Account deletion buttons: Cancel and Confirm:
<img width="468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f25bae6e35b2151e13308a503b8d3a70d467bac9/image.png" alt="image.png" />

6. Request a New Product button:
<img width="364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5UQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bafcb6b9f07b503232732c0914836a530373c9bf/image.png" alt="image.png" />

7. Export button:
<img width="160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHJUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1992a5b868aa7c0fbc4de695f5fb706c7ba6b700/image.png" alt="image.png" />

8. Filter button:
<img width="144" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHZUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9629f9884c413c7b60f9c167355706f8df55a0bf/image.png" alt="image.png" />

9. Clear filters button:
<img width="309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHpUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce3940dd69aed173b89de17ecfbf30d2e59ca0a6/image.png" alt="image.png" />

10. Pagination: Previous and Next buttons:
<img width="223" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec745ff471990e86f0ba3a4f763f7256504ea3b8/image.png" alt="image.png" />

11. Back to Products button:
<img width="234" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC9UQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e3789adbc5239e91d0f5b820e06acdc8258262e/image.png" alt="image.png" />

12. Add a Secondary Technical Lead button:
<img width="505" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVRUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b407c08dc119ca22255d2fbba4bbfca29977bb28/image.png" alt="image.png" />

13. Remove Secondary Technical Lead button: 
<img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56e9b85c1c95e54d6d3e21b6a84c15f9d820c969/image.png" alt="image.png" />

14. Confirm Gold DR: Yes and No buttons: 
<img width="573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWJUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46767e9b5bfdd696bd39ad37c0d10b29c1ade214/image.png" alt="image.png" />

15. Create Request: Submit Request and Previous buttons:
<img width="469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWpUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e3c7e478ba5a7051ad3ec5a5325a497a34db090/image.png" alt="image.png" />

16. All Set modal: Submit Request and Previous buttons:
<img width="897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d42fb8adf14c8ca70f5a432c4dad121488466ccb/image.png" alt="image.png" />

17. Thank you modal: Return to Dashboard button:
<img width="315" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXpUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--291baaf3c2dc77128e82deb39312555eddabbdb2/image.png" alt="image.png" />

18. Admin Comments: Add Comment button:
<img width="280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTdUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d4ffc0a8bbb583aeca0831a770f44026b020dbd/image.png" alt="image.png" />

19. Admin Comments: Post Comment button:
<img width="219" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNS9UQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4147f7dc26a37e355e88281e426851f52a91bd17/image.png" alt="image.png" />

20. Request: Go to Product button:
<img width="250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkhUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1325de5d16c2b9cbebd0f7f40f6c5dfc998a5b59/image.png" alt="image.png" />

21. Request: Back to Requests button:
<img width="229" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkxUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4b2a7633191a9c972a4aaf86a8758486e77815d/image.png" alt="image.png" />

22. Decision: Reject Request and Approve Request buttons:
<img width="454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlhUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ddcf14691a851ac36fd9d5687f5f047d741c83d/image.png" alt="image.png" />

23. Rejection modal: Cancel and Confirm Rejection buttons:
<img width="892" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmJUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62bb758ebb3f71de6af72cbcb70611c50f8ea047/image.png" alt="image.png" />

24. Confirmation modal: Cancel and Confirm Approval buttons:
<img width="885" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjNUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83730dcf7e98042a78dd72989e453f3094a91487/image.png" alt="image.png" />

25. Public Cloud: Accounts to Create: Select All and Select None buttons:
<img width="249" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9UQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--675a21044ed438c0ce90782be42a939b72ddbcd7/image.png" alt="image.png" />

26. Submit Edit Request: 
<img width="276" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0RUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50a7d3bb0be4678b37e4b4838829110bb0f68491/image.png" alt="image.png" />

27. Edit Request modal: Submit Edit Request:
<img width="453" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0hUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a71f97d60f3d94277d1222f7033d98a1c745e495/image.png" alt="image.png" />

28. Delete button for users:
<img width="187" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0xUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--828615845f1dbecb311c339991b3b4fc97e299f4/image.png" alt="image.png" />

29. Public Cloud User Roles: Add a User:
<img width="187" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1BUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3b72cd091eb798298ca6a0f0b9a43b09b6d4985/image.png" alt="image.png" />

30. Public Cloud User Roles: adding User modal: Add a User and Cancel buttons:
<img width="394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72271a85894344b0e4aa21c840ad0d79148cfd22/image.png" alt="image.png" />

31. Public Cloud User Roles: empty list: Add a User button:
<img width="481" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1hUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f69a2a3993690d947d304d7c9c1f08bda617f1a7/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Also have made a Theme Variant called 'bc-orange' and tried it out on the 'Request a New Product button'.
It will suit to a lot of our buttons listed in the previous comment.
The lower button on the screenshot is made with new Mantine Theme Variant:
<img width="877" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ZVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c3eb7cd666d9ce1186a48d60ced5b7e34e24663/image.png" alt="image.png" />

<img width="567" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2pVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15cebc0b0a0d0b1d198f89cd60f2cc6df0d93781/image.png" alt="image.png" />

**Comment by Amritpal-Nijjar** [comment]
😍
