### ISSUE TITLE
Create a link on the web portal to direct users to creating a new issue

### ISSUE THREAD

**Issue by yhfreeman** [bcgov/platform-services-registry#277]
**Describe the issue**
As a PO, I would like to collect more community feedback whether it's bug reporting or enhancement / new feature recommendation. So I would like to see a link somewhere on the web portal that will direct users to creating a new issue on our public repo.

**Additional context**
New issues created by the community will be marked with `community` label.

**Definition of done**
When the above is done.

**Comment by yhfreeman** [comment]
@mitovskaol I've created this ticket as per your request - please modify as you see fit. Thanks.

**Comment by w8896699** [comment]
https://github.com/bcgov/platform-services-registry/pull/461

**Comment by w8896699** [comment]
Martha suggest that : Can it be in both places? Up top is best on this page because it’s really easy to find, but it would be nice to have something in the footer too, since that is on every page.
