### ISSUE TITLE
Fix web form so that it works in Safari

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#278]
## Story

As a user, I would like to use Safari to fill out the project request form.

## Description

The project request form does not work in Safari. Since many gov worker get Macs and the default browser on the Mac (and iOS) is Safari we should make sure it works with said browser.

## Done When

The form can be filled out equally well in Safari and Chrome.

**Comment by sbathgate** [comment]
This bug was determined to be a result of a REGEX incompatibility applied to the registry form validation.
