### ISSUE TITLE
failed add a user to a role for the public cloud 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#2811]
<img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFBqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77dfaeb67f5356f341509539e18f76fc5d673481/image.png" alt="image.png" />

t appears there is a bug when setting URLs by roles. If you are configuring developers, please use the link below:
https://registry.developer.gov.bc.ca/public-cloud/products/orkz18/aws-roles/developers
developers: https://registry.developer.gov.bc.ca/public-cloud/products/orkz18/aws-roles/developers
viewers: https://registry.developer.gov.bc.ca/public-cloud/products/orkz18/aws-roles/viewers
admins: https://registry.developer.gov.bc.ca/public-cloud/products/orkz18/aws-roles/admins
billing-viewers: https://registry.developer.gov.bc.ca/public-cloud/products/orkz18/aws-roles/billing-viewers
security-auditors: https://registry.developer.gov.bc.ca/public-cloud/products/orkz18/aws-roles/security-auditors

- [x] create a new branch from the tag that is currently deployed to the prod.
- [x] make hotfix onto the new branch.
- [x] create a new tag from the hotfix branch for testing on test environment.
- [x] once resolved, deploy to the prod.

**Comment by funtigr** [comment]
Deployed to Prod in version 0.23.10.
<img width="1452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26e1d335da96b325467c4df5c346eae729885892/image.png" alt="image.png" />
