### ISSUE TITLE
Generic Input component

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2827]
### Description
Create a generic `Input` component to ensure consistent UI and behavior for form input elements across the pages.

### Technical Details
The following components will be required:
1. **FormTextInput**: A generic input component that handles both active and disabled states with different logic.
2. **HookFormTextInput**: A wrapper around `FormTextInput` that integrates with `react-hook-form` using `useFormContext` for data binding.

### Definition of Done (DOD)
- Display all possible input variations on the example page at `/examples/textinputs`.

**Comment by junminahn** [comment]
@funtigr https://dev-pltsvc.apps.silver.devops.gov.bc.ca/examples/ui/text-input

**Comment by funtigr** [comment]
Now we have a common component for input fields:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUFWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b972acb12d2bc7cbd26d7c08f1a8713075cebb6e/image.png" alt="image.png" />
