### ISSUE TITLE
Generic Textarea component

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2828]
### Description
Create a generic `Textarea` component to ensure consistent UI and behavior for form input elements across the pages.

### Technical Details
The following components will be required:
1. **FormTextarea**: A generic input component that handles both active and disabled states with different logic.
2. **HookFormTextarea**: A wrapper around `FormTextarea` that integrates with `react-hook-form` using `useFormContext` for data binding.

### Definition of Done (DOD)
- Display all possible textarea variations on the example page at `/examples/textareas`.

**Comment by junminahn** [comment]
@funtigr https://dev-pltsvc.apps.silver.devops.gov.bc.ca/examples/ui/textarea

**Comment by funtigr** [comment]
Now we have the common component for text areas:
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGdWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5110c8ad08347f94dad42825276ed17dca4460f/image.png" alt="image.png" />
