### ISSUE TITLE
Reword gold dr checkbox text

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#2835]

**Comment by funtigr** [comment]
Now if user checks the checkbox "Include Gold DR" the message looks like this:
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTM4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8659f65be41ee02c4cfd6a88aff820e967f77beb/image.png" alt="image.png" />

If user unchecks the checkbox the message looks like this:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3Y4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--260c720caaba40a74c5c248f204f6c011776212e/image.png" alt="image.png" />
