### ISSUE TITLE
Add Test label for products created for temporary purpose (e.g. training)

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2841]
Cailey will provide the language for the checkbox. 

Checkbox language:

> Temporary product set: this product set will be automatically deleted after 30 days. 

Let's maybe also have a pop-up when they submit that says:

> You have selected a temporary product set. Please be aware that everything in the provisioned namespaces will be deleted after 30 days, including all data and deployments. Are you sure you want a temporary product set?

DoD:
- add a temporary label to create product page to temporary created namespaces (e.g. training purpose, etc.) 
- add a flag to the DB schema
- exclude products with this label from the analytics dashboard
- create script to add filed `isTest` 

Checkbox language:
Temporary product set: this product set will be automatically deleted after 30 days. 
Let's maybe also have a pop-up when they submit that says:
You have selected a temporary product set. Please be aware that everything in the provisioned namespaces will be deleted after 30 days, including all data and deployments. Are you sure you want a temporary product set?

**Comment by funtigr** [comment]
Now the checkbox is in place that allows to toggle on temporary status for the product.
It is available both on Create page and on Product page (so you can add this status after provisioning too).
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW9VQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4054e6af8c6927fd1c4c21bc3aea95dcd8ed218e/image.png" alt="image.png" />

After checking the checkbox the popup with confirmation text is displayed:
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5b1c3110e86f68ce2a08b7db8bcab1917a23a90/image.png" alt="image.png" />

Marking existing product as Temporary creates a new Edit Request which is approved automatically.
