### ISSUE TITLE
Separate admin comments for Products and Requests [Backend]

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2842]
DoD:
- a comment can be added to a request level only

**Comment by Amritpal-Nijjar** [comment]
POST
To create a comment on a request
http://localhost:3000/api/private-cloud/products/[licencePlate]/comments

Body
{
  "text": "comment on a request",
  "requestId": "[requestId]"
}

GET
To list comments on a request
http://localhost:3000/api/private-cloud/products/[licencePlate]comments?requestId=[requestId]


GET
To read a comment on a request
http://localhost:3000/api/private-cloud/products/[licencePlate]/comments/[commentId]

PUT
To update comment on a request
http://localhost:3000/api/private-cloud/products/[licencePlate]/comments/[commentId]
Body
{
  "text": "updating the comment on a request "
}

DELETE
To delete comment on a request
http://localhost:3000/api/private-cloud/products/[licencePlate]/comments/[commentId]

**Comment by funtigr** [comment]
Tested. Every of endpoints is functional and makes expected actions.
