### ISSUE TITLE
Email Bugs [Private Cloud] 

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2844]
- [x] Scenario 1) User receives email mentioning the author, but the admin does not. Update docs, and update the template for the admin.
- [ ] Scenario 1) Rejection email is not being sent for some reason...
- [x] Scenario 2) Rejection email has documentation on product details, which is not currently in the template. Add these details to the template for scalability and visibility
- [x] Scenario 4) admins do not get the text in the email that says who actioned the request
- [x] Scenario 4) add product details that were also rejected (also wait for the summary page to reuse the same logic)
- [x] Scenario 5) admins do not get the text in the email that says who actioned the request

**Comment by Amritpal-Nijjar** [comment]
Scenario 1) Rejection email is not being sent for some reason... The email is being sent, but it is not being rendered at all, spent a lot of time trying to debug this issue, but was unsuccessful...

**Comment by funtigr** [comment]
- Scenario 1: now admin sees the who actioned the creation
- Scenario 1: created a separate task for that: https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/2977
- Scenario 2: the changes now reflect the documentation. 
- Scenario 4: mixed request now have the name of person who actioned the request in admins email.
- Scenario 4: mixed request has all the changes listed in the rejected request.
- Scenario 5: now the delete request has the name of person who actioned the request in admins email.
