### ISSUE TITLE
Add validation before prompting for change request details

### ISSUE THREAD

**Issue by mtspn** [bcgov/platform-services-registry#2899]
When requesting a change that would be automatically provisioned without requiring approval, users are still prompted to give a description of the change. Since we don't need this information, could we validate first and only prompt when the changes are in a category that requires approval? 

In my case, I change 25 tech lead details bi-monthly for OpenShift 201 so this is a bit of a drag for my use case. Thank you! 

Team's discussion: 
- make this comment field optional for those requests that don't require an approval. 
- make a button "Submit request" clickable without providing a comment
- Update the prompt text in the box "Type a comment..." to "Comment is optional as this request will be automatically approved"
- Update the text at the top of the comment box to indicate that a comment is optional as this request won't require an approval and it will be approved automatically

<img width="1216" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b072964e4fa8d95e2a33b10ccfbda645e425402/Screenshot%202024-05-23%20at%2011.34.20%E2%80%AFAM.png" alt="Screenshot 2024-05-23 at 11.34.20 AM.png" />

**Comment by junminahn** [comment]
@Iryna-Kaplun I believe we will need a team discussion to have:
1. when to prompt the comment box.
2. whether or not the comments are mandatory or not.

**Comment by junminahn** [comment]
Not applicable, as the comment is now optional when submitting.
