### ISSUE TITLE
Text input of technical lead does not work when clicking away from input box

### ISSUE THREAD

**Issue by mtspn** [bcgov/platform-services-registry#2900]
When changing a technical lead's details, if users enter a valid email but click out of the text input box (instead of using return or selecting a name from the drop down) then the contact details of the tech lead are not updated. 

This could be confusing from a user perspective. 
<img width="847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0FKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a114cdd4fa32ebab0cc95f9f3611af2695a5c6a/Screenshot%202024-05-23%20at%2011.43.54%E2%80%AFAM.png" alt="Screenshot 2024-05-23 at 11.43.54 AM.png" />

**Comment by funtigr** [comment]
Now if user clicks outside the input tooltip or input field, the field gets erased, so the user would not think that they have made a valid input.
<img width="1473" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2poQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c65fd2d96292244e1df725b7d1961b0acb0a4592/image.png" alt="image.png" />
