### ISSUE TITLE
Login Page Enhancements

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2960]
Rearrange the Login page to make logical sense with the sections and the information presented there. 

Implement the following suggestions: 

1. Rename "Private Cloud Hosting" to "Private Cloud OpenShift Platform" and "Public Cloud Hosting" to "Public Cloud Landing Zone".
2. Remove "4" from the "For existing applications hosted on OpenShift 4 Platform or B.C. Government Public Cloud Landing Zone." sentence.
2. Blue disclaimer - rename "Public Cloud" to "Public Cloud Landing Zone".
3. Remove the Login button (yellow one) in the middle of the page 
4. Move Blue disclaimer to the Register a new product section under the Public Cloud link
5. Add "or a Technical Lead" to the following sentence:  "If you are a Product Owner {or a Technical Lead} for a new cloud-native application and are interested in hosting the application please review the available options below:" in the Register a new product section
6. Rearrange "Before your start" section
7. Add a link to the IDIR page to the sentences in the section "What you will need": 
- "Have a valid IDIR {insert the link in the word IDIR} account, which you'll use to access the registry"
- "Share contact details and IDIR {insert the link in the word IDIR}  information for the product owner and up to 2 technical leads".
https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/id-services/idir

**Comment by funtigr** [comment]
All options are implemented.
Section 'Register a new product' has been deleted, so there is nowhere to implement option 6. 
The links with info on each hosting type is moved to the bottom of the page to the section 'Learn more'.
