### ISSUE TITLE
Add "changes to product contacts" chart to analytics page

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#2961]
**Describe the issue**
As a service designer, I want the ability to visibly see how many people are changing their team's contact information (for PO and TLs) in the Registry. I want the ability to see the number of product contact changes to be presented on the y-axis and the date on the x-axis, similar to how the requests over time chart look.

**Additional context**
I want to see out an email to all product contacts with a survey for our new AlertManager service. This survey will be sent alongside a message to all contacts to make sure their product contacts are up to date (they often aren't changed when personnel move projects). I'm bundling these two requests together so we don't have to worry about annoying people with too many emails. However, this means this request is more urgent as I'd like to send the survey ASAP. 

**How does this benefit the users of our platform?**
It directly measures the effectiveness of our email blast - we send an email to everyone to make sure the product contacts are up to date, but does that actually get actioned? Having the number of contact changes over a given period would be helpful to see if we should continue using email as our main communication method with users.

**Definition of done**

- [ ] Graph is visible on the analytics page

**Comment by junminahn** [comment]
PRs:
- https://github.com/bcgov/platform-services-registry/pull/3211
- https://github.com/bcgov/platform-services-registry/pull/3219

**Comment by Kolezhanchik** [comment]
visual chart works as expected for both public and private, `Export` button doesn't work for me both public and private namespaces
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWVVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73d9614566dfda7067d7ffc06b674a3e100b8365/image.png" alt="image.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWlVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9b796cd8d019f48c45e0eaa7cf81120d0005c22/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
now it is possible to download `.csv file like: 
`<img width="326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmlVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86abc4c7e569f36a669a3d8e65083b36492fcabe/image.png" alt="image.png" />
`
