### ISSUE TITLE
Add traffic chart to analytics page

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#2962]
**Describe the issue**
As a service designer, I want the ability to visibly see how much traffic the Registry sees in a given day. Ideally, this would be a similar line graph with the number of users on the y-axis and the date on the x-axis. This would help me answer how many people are visiting the site on a given day

**Additional context**
I want to see out an email to all product contacts with a survey for our new AlertManager service. This survey will be sent alongside a message to all contacts to make sure their product contacts are up to date (they often aren't changed when personnel move projects). I'm bundling these two requests together so we don't have to worry about annoying people with too many emails. However, this means this request is more urgent as I'd like to send the survey ASAP. 

**How does this benefit the users of our platform?**
It directly measures the effectiveness of our email blast - we send an email to everyone to make sure the product contacts are up to date, but does that actually get actioned? Having the ability to see how many people are checking the Registry is helpful in demonstrating if people are actually reading and responding to our emails. 

**Definition of done**
- [ ] Some form of chart is added to the analytics page

**Comment by funtigr** [comment]
Now we have General Analytics chart that counts Login events;
<img width="1702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--960c17f197717b3d416c8c7beaa80e4c2f0c16d6/image.png" alt="image.png" />
