### ISSUE TITLE
Emails: The Create Request Rejection email comes empty

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#2977]
The Create Request Rejection email is not rendered.
"The email is being sent, but it is not being rendered at all".
<img width="1348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1rQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bbc23cee2c69674442f515d7e37eebfe1b94f81/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
works as expected 
<img width="536" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55f918cd3ee8ecd46d3cfdbbfdf08256d31c3387/image.png" alt="image.png" />
