### ISSUE TITLE
Create API endpoint for project info from license plate

### ISSUE THREAD

**Issue by IanKWatts** [bcgov/platform-services-registry#3001]
**Describe the issue**
There is an API endpoint that takes a project's internal ID and returns project information in the same format as what is sent to the Provisioner.  Please create a similar endpoint that returns the same information, but using the project license plate as input instead of the internal ID.

**Rational/Why**
Allow supporting applications to interact with the Registry using the public-facing license plate, which is known, versus the internal ID, which is not known outside of the Registry.

**Additional Context**
This endpoint returns project info in JSON format using the internal ID as input:
`/api/v1/private-cloud/products/${PROFILE_ID}/nats-message`
We would like similar functionality using the license plate as input.

**Dependencies**
- Contact Ian Watts when this is ready for testing or for more information.

**Tests**

**Definition of done/Acceptance Criteria**
- [ ] API endpoint is available in Prod
- [ ] Ian has been notified

**Comment by junminahn** [comment]
I will ask Ian for testing.

**Comment by junminahn** [comment]
@IanKWatts , we pushed the changes to prod environment; you can use the same endpoint; it will take both `id` and `licence plate` as the unique id.
