### ISSUE TITLE
On Decision Page for Edit Request, CPU for test-namespace is showing requested quota in current quota

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#3034]
**Description**:
There is a bug in representation of the Edit Request. In Summary it is shown correctly, but in decision page it displays `requested quota` for Test as `current quota`, thus not showing the changes:
<img width="1459" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkErQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f42d891c6aa0e2c12a48c5cda4d7af93fc2c47e/Clipboard%20-%20June%205%2C%202024%202_13%20PM.png" alt="Clipboard - June 5, 2024 2_13 PM.png" />

**Comment by junminahn** [comment]
@funtigr I don't think it is a bug as the decision is already made. I would hide `current xxx` texts if the decision is made.

**Comment by funtigr** [comment]
At this screenshot decision is not yet made. 
It is the decision page for the Admin.

**Comment by junminahn** [comment]
> At this screenshot decision is not yet made.
> It is the decision page for the Admin.

Is it edit request, if the request is still active how come the inputs are grayed out for admin?

**Comment by funtigr** [comment]
Sorry, my bad. 
Decision page shows everything right. And yes, we don't need Current Quota on other than Decision page.
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3QvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d88ebd7cdafc5de11234f97a5ca9340898988df/image.png" alt="image.png" />
