### ISSUE TITLE
Automatic Subscription of POs/TLs/Secondary TLs and Other Contacts of a New Registry Product to Registry Contacts for Private Cloud in MailChimp 

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3040]
To Do:
To automate subscription of POs and TLs of Registry Product to Registry Contacts for Private Cloud in MailChimp 

Explore the MailChimp API and subscription options

DoD:

- [ ] automated subscription of POs/TLs//Secondary TLs and Other Contacts (once they are implemented) of Registry Product to Registry Contacts for Private Cloud in MailChimp

**Comment by junminahn** [comment]
reference:
- https://github.com/mailchimp/mailchimp-marketing-python
