### ISSUE TITLE
App Events System - Update the database schema and codebase accordingly.

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3042]
App Events System - Update the database schema and codebase accordingly.

**Comment by junminahn** [comment]
Audit event structure
- type
- user id?
- date time
- payload

Audit Log events:
- User Login
   - empty
- User logout (explicit)
   - empty
- User create api token
  - empty
- User delete api token
  - empty
- Create private product request
  - request ID
- Update private product request
  - request ID
- Delete private product request
  - request ID
- User private export product
  - filter information
- Admin review requests
  - request ID
- resend private  request
  - request ID
- reprovisioning private product
  - licence plate
- Create public product request
- Update public product request
- Delete public product request
- User public export product

**Comment by funtigr** [comment]
Everything corresponds to description from previous comment except the Downloading the CSV files (User private export product, User public export product).
<img width="1453" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFpoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8dcabfb31497e6e737670b33e2816d70a0882d72/image.png" alt="image.png" />

**Comment by junminahn** [comment]
@funtigr right, I missed those two for some reason; thank you for finding them out; I will make a PR soon.

**Comment by funtigr** [comment]
Now export in both Public Cloud and Private Cloud is logged in the Events collection of DB with search parameters:
<img width="1388" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTVvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--592b2daa922a4f3d6653fbb9a897aab5f921724b/image.png" alt="image.png" />

<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTlvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8bb8afcdfc2c62aef70992ae06b7d314d231a6b9/image.png" alt="image.png" />
