### ISSUE TITLE
Update Public Cloud emails scenarios for Azure products

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3049]
- [ ] clarify with Public cloud team what scenarios and info/links, etc. should be for Azure products 
- [ ] update the language/info/links in the email template tailored for Azure products and various scenarios

**Comment by Kolezhanchik** [comment]
comment from Olena "Could you please add the following custom message to the provisioning confirmation email for Azure projects only
Your project in Azure will automatically be added to the Enterprise Support Plan ("Unified") that BC Government has procured with Microsoft. Please wait 7 business days after your project has been provisioned, before attempting to open a case with the Microsoft support team through the Azure Portal, the instructions on how to open a support case are available here. If you need to open a support case before the access to the Enterprise Support Plan is enabled for your project, please contact BC Gov's account representative BHASKAR.HALDER@microsoft.com and he will be able to assist you with this"

**Comment by Kolezhanchik** [comment]
<img width="1659" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVo5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adb93c50b1a2835118f017fcdbdf75e5c5f21944/image.png" alt="image.png" />

**Comment by funtigr** [comment]
The emails are changed to reflect Azure:
<img width="979" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGwvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f569fe6dff011153af6a2965e0e2b4766928da0a/image.png" alt="image.png" />

<img width="968" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHAvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--913a5df612e2d0cdf6f85755dd12e0086cb99746/image.png" alt="image.png" />

<img width="982" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHgvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31bd83531e2c207a8a9a9c8e7b7d4b2d417f4bb7/image.png" alt="image.png" />
