### ISSUE TITLE
API/DB: Approve projects within the Registry

### ISSUE THREAD

**Issue by sbathgate** [bcgov/platform-services-registry#305]
**Describe the issue**
This issue depends on issue #304 - WEB: Approve projects within the Registry

To approve a project within the registry the following must be implemented:

- API:
  - Approval:
    - Message to NATS with required JSON body
    - Update project in DB
    - Await callback response
    - Email user that project has been approved
  - Denial:
    - write to DB, archive project request, no NATS message
    - Email user informing of rejection, include custom message from Olena / Justin H

- DB:
  - Add request detail to include Approval / Rejection 

**Definition of done**
When Olena / Justin H can approve or reject a project request within the registry

**Comment by yhfreeman** [comment]
@sbathgate for your review https://gist.github.com/yhfreeman/110385ae178174446b7561c04ff603de

**Comment by sbathgate** [comment]
Currently blocked until Multi-cluster support has been merged, tested and released.
