### ISSUE TITLE
Some Products on Prod don't have corresponding requestedProject which leads to Prisma Validation Error on Edit

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#3052]
**Description**:
Some Products on Prod don't have corresponding requestedProject which leads to Prisma Validation Error on Edit.

Jennifer Dowd tried to change contacts for the Product with licencePlate: 534380
The Submit button doesn't let it through. Me and Zhanna could reproduce the bug. 
The problem is that Prisma schema needs requestedProject keys on validation and doesn't let to make any changes to the Product. 
The Product itself is created in 2020. We looked at other Products and found another one with licencePlate: a3e512

DoD:
Write a script which will find such Products and create minimal required corresponding documents in requestedProject table of DB for them.

**Comment by junminahn** [comment]
there are many projects with out the initial request:
```
0d0eec
0dff19
17db4f
1b91ec
1dbf2e
1f9996
1fd77b
269007
27e8b8
3a0694
3b2420
47ba99
461a32
48aa05
2d982c
4a9599
534380
55b94d
59e31e
5b7aa5
77c02f
735b8b
74a571
7d3aa1
7e154b
7d321c
8878b4
9daef1
a40635
a3e512
a99fd4
aa27f1
acf456
ad204f
ad3577
ab537b
acc72b
afffe0
b07b69
b183a5
b48f1e
b5f574
b4f134
b8531e
b25be4
bbe4c3
c00d40
bf01c0
c207ac
c52cb8
c57b8f
c6af30
c5aa9e
ca94a8
ccc129
cef916
cef9ac
d3d940
dab7fb
de957b
deb54b
dc383e
e24757
e34374
e09bc1
e0cee6
e11dbf
e4589f
e82e9a
e84410
e704e1
e7c518
e903c2
e8470a
e8b9ad
ed9154
ed57f0
ee74a4
f0431b
f047a2
f5dfb9
f6b17d
te1690b
ffcb5f
```
