### ISSUE TITLE
Refactor NATS

### ISSUE THREAD

**Issue by sbathgate** [bcgov/platform-services-registry#306]
**Describe the issue**
To enable multicluster support, the current Registry NATS message will need to be refactored to remove cluster details from the NATs message and instead target a specific channel that corresponds to the correct cluster

**Definition of done**
When the NATS message has been reconfigured to target specific NATS channels on a per cluster basis

**Comment by yhfreeman** [comment]
For the agreed MVP deliverables over this sprint, it's decided to have registry api keep sending the same blob of json
https://gist.github.com/j-pye/c63934e389f0b3378fd5edc770630ac4
https://gist.github.com/j-pye/02c3bb929db4f49afc6f66571b00941c
but publish the message to different nats subjects based on the requested provisioning cluster.

Nats subjects will include:
`registry_project_provisioning_silver`
`registry_project_provisioning_gold`
`registry_project_provisioning_klab`
`registry_project_provisioning_clab` 

Moving forward in the next sprint, it's decided to create a (priority) ticket to make the above configurable for team to figure out what works best from the subscribing side including using nats api and argo-events.

/cc @j-pye @sbathgate

**Comment by yhfreeman** [comment]
As per RC communications it's requested to have cluster names in the (frontend) menu dropdown match the following new naming conventions.
| Name        | Display Name     |
| ------------- |:-------------:|
| silver      | Silver Kamloops |
| gold      | Gold Kamloops      |
| golddr | Gold (DR) Calgary      |
| klab | KLAB Kamloops     |
| clab | CLAB Calgary     |

https://chat.developer.gov.bc.ca/channel/devops-registry?msg=FNE9ozYxg49KFteyi
https://chat.developer.gov.bc.ca/channel/devops-registry?msg=hakNr5iH2dnw7wkZz

**Comment by yhfreeman** [comment]
Additional clarifications on RC that may affect the api implementation of multi-cluster feature.
https://chat.developer.gov.bc.ca/channel/devops-registry?msg=YWBjXLTWGaXukfj7F
