### ISSUE TITLE
automatic scheduled Temporary products deletion request

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#3077]
send deletion requests automatically in 30 days a product was created with `isTest` flag
send notifications to users notifying about soon `Temporary`  product deletion

If the temporary product, that is due for deletion, has job running, it can't be deleted and we need to reach to the product contacts and/or plat admins to stop the job in that product space.

**Comment by junminahn** [comment]
reference:
- https://github.com/mailchimp/mailchimp-marketing-python

**Comment by funtigr** [comment]
The task is showing fails in Airflow and some in logs (though works).
<img width="1727" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3dKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee7616ec0dbeb5f029fc8b61cfbb96f42b27edb4/image.png" alt="image.png" />

<img width="1707" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTRKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df51ada42ab03dd7b5759024675ca4f6bad82636/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Update. If there are many requests it works for parts of them. They are all older than 30 days: 
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0lKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0616eef0497b55be7bd026566e09f8e9900a213b/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Now works as expected.
<img width="1530" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzBPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--206456006ddc86156456afe13c6eba24b41b329c/image.png" alt="image.png" />
