### ISSUE TITLE
see errors in dashboard after login

### ISSUE THREAD

**Issue by ll911** [bcgov/platform-services-registry#308]
**Describe the issue**
<img width="680" alt="Screen Shot 2021-02-10 at 12 33 45 PM" src="https://user-images.githubusercontent.com/11949273/107568729-444e8980-6b9c-11eb-84e3-e509a3d43758.png">

**Additional context**
error shows up after select any project from dashboard 

**Definition of done**
error free

**Comment by yhfreeman** [comment]
Closing this as a result of ticket #310.
Thanks @ll911 for reporting the issue.
