### ISSUE TITLE
Display request box in public cloud product list

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#3094]
Display request box in public cloud product list which is missing from the UI.

**Comment by junminahn** [comment]
@funtigr I cannot re-produce the bug.

**Comment by funtigr** [comment]
Sorry, I didn't provide clear description. If `public-admin` is not mentioned in the contacts of the product, he cannot see the Delete button.
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFovQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17afbaf824fbf5d6dde78834575257fa6154e04d/image.png" alt="image.png" />

**Comment by junminahn** [comment]
@funtigr  i see. Then please update the name & description as “public admin” not “global admin”

**Comment by junminahn** [comment]
@funtigr the issue is not related to the role, it is related to the existing delete request.
Q. does public cloud need to review `delete requests`? I know they do for `create requests`, but `edit requests`.

**Comment by Amritpal-Nijjar** [comment]
<img width="1382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15fb4053a244dcfa1bb29c6ba2bf3cb3cfe5bc16/Screenshot%202024-06-21%20at%203.31.12%20PM.png" alt="Screenshot 2024-06-21 at 3.31.12 PM.png" />
Request does show, but it currently shows a string of text in the "Submitted by ..." section of the request box

**Comment by junminahn** [comment]
@Amritpal-Nijjar fixed the issue.

**Comment by Amritpal-Nijjar** [comment]
The request boxes are now properly displayed in the public cloud tabs, with the correct information:<img width="1674" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXlLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--679724996972a8a1753724f7914d2a8517b4e30e/Screenshot%202024-06-24%20at%201.38.26%20PM.png" alt="Screenshot 2024-06-24 at 1.38.26 PM.png" />
