### ISSUE TITLE
Ministry editor role doesn't see related ministry product page 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#3103]
**Describe the bug/ Actual behaviour**
Ministry editor role - user having this role doesn't see related ministry product page 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to registry with a ministry editor role
2. Click on a product of related ministry in a list of products 
3. See error

**Expected behaviour**
See the related ministry page to edit it if needed

**Screenshots**
<img width="1666" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3BuQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c233d2e9d5336408fdcc6b4f2fa6c27fba49661/image.png" alt="image.png" />

**Definition of done:**
Bug is fixed and user with a ministry related role can see single product page

**Comment by funtigr** [comment]
Ministry Editor can now see the products of the ministry where not mentioned in the contacts.
