### ISSUE TITLE
Implement Commit Message Linting with Conventional Commits

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3118]
### Description
To enhance the quality of commit messages in the Git history and changelog, we aim to lint commit messages both locally and in the CI pipeline.

### Technical Details
- Evaluate the following tool or explore other alternatives:
  - [Commitlint](https://github.com/conventional-changelog/commitlint)

### Definition of Done (DOD)
- If a new commit message does not adhere to `conventional commits`, the pre-commit hooks will fail in the local environment and the CI pipeline will also enforce this rule.

**Comment by funtigr** [comment]
The hook is working. If the commit message is out of format it gives errors:
<img width="663" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBNQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9072b11c770c0611c172b27b53e86e73418e50a/image.png" alt="image.png" />

<img width="786" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHRNQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7af52ba7c4350d6032037cd3ab4e70150c84533d/image.png" alt="image.png" />

If everything is right, it gives success message:
<img width="565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDVNQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8603463ed3eaac31995c78b7ccaf15fb6ee23416/image.png" alt="image.png" />
