### ISSUE TITLE
revisit users with roles and remove those who don't need the role anymore

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3120]
Let's review the roles of our users to ensure they have the minimum necessary privileges.

**Comment by Kolezhanchik** [comment]
https://docs.google.com/spreadsheets/d/1XgjCgXGJ46qZs-dBRs6EnDtG4UC3jPsbB-QQ0Dl4ihQ/edit?gid=1894034524#gid=1894034524

**Comment by junminahn** [comment]
I had a discussion with the major platform services' admins to determine the most appropriate person to handle user cleanup. Nick, as the MISO, can review the users and revoke access if necessary.
