### ISSUE TITLE
add the custom message to the provisioning confirmation email for Azure projects only

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#3132]
comment from Olena "Could you please add the following custom message to the provisioning confirmation email for Azure projects only
Your project in Azure will automatically be added to the Enterprise Support Plan ("Unified") that BC Government has procured with Microsoft. Please wait 7 business days after your project has been provisioned, before attempting to open a case with the Microsoft support team through the Azure Portal, the instructions on how to open a support case are available here. If you need to open a support case before the access to the Enterprise Support Plan is enabled for your project, please contact BC Gov's account representative BHASKAR.HALDER@microsoft.com and he will be able to assist you with this"

**Comment by funtigr** [comment]
Now the `Provisioned` email for Public Cloud create request has the above text:
<img width="960" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFovQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--390b28bc670edee89cd7c3974f8f30a6be253e95/image.png" alt="image.png" />
