### ISSUE TITLE
Draft Email Notification about the Gold and Gold DR Change 

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3137]
Email about the New UI change for the reference:

> Dear Cloud services community,
> 
> I hope this email finds you well. We're happy to share some exciting news with you—there's an update to the Platform Product Registry user interface!
> 
> What to expect:
> Starting today, you'll notice a fresh new look for the Platform Product Registry. Rest assured, your data will remain intact. The update focuses on enhancing visual elements and user experience. Admins will now have the ability to modify requests that you make. That will mean that they can discuss with you and make necessary changes instead of rejecting the request.
> 
> Why the change:
> We believe in staying ahead of the curve, and our goal with this update is to provide you with a more modern and minimalistic interface. We're confident that the refreshed design will improve your overall user experience.
> 
> Your input matters:
> We value your opinion, and we're eager to hear what you think about the updated UI. If you have any feedback, suggestions, or thoughts, please feel free to reach out to us at platformservicesteam@gov.bc.ca and Rocket.Chat channel. Your insights are essential in helping us refine and enhance the Platform Product Registry further.
> 
> Thank you for being a valued member of the Cloud services community. We appreciate your continued support, and we're committed to delivering an app with useful improvements for you!
> 
> Best regards,
> The Platform Registry Team
>

**Comment by funtigr** [comment]
Dear Cloud services community,
I hope this email finds you well. 
There is a new functionality we would like to tell you about. We have added a new 'Include Gold DR' checkbox that reflects wether your namespaces in Gold have matching namespaces in Gold DR cluster.
When you create a new Product, the checkbox is unchecked by default. If you leave it unchecked, you will get namespaces in Gold cluster only and will **not** have the disaster recovery (DR) option. 
<img width="804" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk41QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c401c1c9ad7f5add7548c755effa0dd7a3e0b0d/gold-dr-screenshot-3.png" alt="gold-dr-screenshot-3.png" />

If you check 'Include Gold DR' checkbox, the namespaces with same license plate will be provisioned for you in Gold DR cluster. You can find more information on how to use it here: https://digital.gov.bc.ca/cloud/services/private/internal-resources/gold/
<img width="811" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlY1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72f7a2b80627c0d769bd691071c0358c08d601db/gold-dr-screenshot1.png" alt="gold-dr-screenshot1.png" />

If you have Products in Gold cluster and they were created before May 9, 2024, you have 'Include Gold DR' on by default. If you don't need it, you can uncheck the checkbox and that will allow you to submit an Edit Request. After request is provisioned, the namespaces in Gold DR cluster will be deleted.

If you will need Gold DR namespaces in the future, you can check the checkbox and submit it as an Edit Request to provision them again. 

If you have any feedback, suggestions, or thoughts, please feel free to reach out to us at platformservicesteam@gov.bc.ca and Rocket.Chat channel #devops-registry 

Best regards,
The Platform Registry Team

**Comment by Pilargit12** [comment]
Dear Cloud services community,

We hope you are doing well! 

We wanted to remind you of the new update added to the Platform Product Registry. There's a new checkbox called 'Include Gold DR' and this feature helps you see if your namespaces in the Gold cluster have matching namespaces in the Gold DR cluster.

When you create a new Product now, this checkbox is **not selected**. This means you'll only get namespaces in the Gold cluster and won't have disaster recovery (DR) options.

It's important to know that Products made in the Gold cluster before May 9, 2024 have the 'Include Gold DR' checkbox **selected** by default. If you don't need DR, you can remove the selected checkbox and send an 'Edit Request' to submit the change. After we process it, the namespaces in the Gold DR cluster will be deleted.

If you need Gold DR namespaces later, you can select the checkbox and send another 'Edit Request' to add them back.

Let us know if you have any questions or feedback by emailing u at platformservicesteam@gov.bc.ca and Rocket.Chat channel [#devops-registry](https://chat.developer.gov.bc.ca/channel/devops-registry)

Best regards,
The Platform Registry Team
