### ISSUE TITLE
Create gitops repo per cluster for multi-cluster support

### ISSUE THREAD

**Issue by yhfreeman** [bcgov/platform-services-registry#314]
**Describe the issue**
Create gitops repo per cluster for multi-cluster support.

**Additional context**
Repos should be created for clab, klab, and silver clusters tenant namespaces. 
`platform-gitops-<region>-<cluster>-namespaces`
eg. `platform-gitops-kamloops-silver-namespaces`

**Definition of done**
For each cluster:
- [x] Repository Created
- [x] Configure Squash Based merging by default
- [x] Configure Policy Bot and Bulldozer Bot for automatic merging 
- [x] Add matching team members from the `platform-gitops` repository 
- [x] Configure Github Actions for Registry Provisioned Callback

**Comment by j-pye** [comment]
Done.
