### ISSUE TITLE
Update UI Delete confirmation modal

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3157]
- [ ] 154). UI: Jason L.: Delete Request: In Deletion Popup make "this can't be undone" bolder and/or bigger. Team suggestion - Combine the message that we have in yellow with "This can't be undone". Put it at the top of the popup, make it red.
- [ ] 155). UI: Luke: Delete Request: Make a red (or red on hover) "Delete" button at the bottom.
- [ ] 152). UI: Abibat: Delete Request: Add data about decommission of the product and link to documentation to Deletion Popup. Clarify if the message/link will be different for different providers. https://digital.gov.bc.ca/cloud/services/public/intro/#closure

**Comment by funtigr** [comment]
For Admin we have this Delete button inside the Dropdown menu and now it looks non-logical to have a button in the dropdown menu:
<img width="1455" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeitKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efed9c7c6f3562193bdb55ab6f0b0f39e16552df/image.png" alt="image.png" />

Can we add the old style for Admins (make it a separate component or mute the style for Admin pages) and leave the new changes for User pages. The example of how it looked previously:
<img width="348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMENKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2803e900cd3ad0f87f3b90322fb8ebae179abee7/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Fixed:
<img width="361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVNWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f4ab668d078daf01cb65d9bfe02ab586e060e6e/image.png" alt="image.png" />

<img width="990" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVdWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f5a58117fbc8d4fbd7d5d7257e342cc7b3923fa/image.png" alt="image.png" />
