### ISSUE TITLE
Enhance Search, Filter, and Sort Functionality on Private Cloud Product Page

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3165]
### Description
Enhance the search, filter, and sort functionalities on the private cloud product page.

### Technical Details
- **Search:** Supports searching by licencePlate, name, description, and member name.
- **Filters (multi-select):**
   - status: default to active
   - temporary flag: default to all
   - ministry: default to all
   - cluster: default to all

- **Sort By:** Name, description, licencePlate, updated date
  - Each field supports both ASC and DESC sorting options.
  - Default: Updated date (DESC).

### Definition of Done (DOD)
- The search, filter, and sort functionalities operate as expected.

**Comment by funtigr** [comment]
Now we have a convenient filtering and search at the same time.
Filter works as expected:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1lHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4421c5564b08ff16012201d8a6e45d68fd0568e/image.png" alt="image.png" />

Search is working as expected:
<img width="1458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2dHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0e76a084281423f6db498f17092a60302cb1e76/image.png" alt="image.png" />

<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2tHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d9690d1977ba706adfa3f3af94316b7479fbbc6/image.png" alt="image.png" />
