### ISSUE TITLE
Enhance Search, Filter, and Sort Functionality on Private Cloud Request Page

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3166]
### Description
Enhance the search, filter, and sort functionalities on the private cloud request page.

### Technical Details
- **Search:** Supports searching by licencePlate, name, description, and member name.
- **Filters (multi-select):**
   - request types: default to all
   - decision status: default to pending
   - temporary flag: default to all
   - ministry: default to all
   - cluster: default to all

- **Sort By:** Name, description, licencePlate, status, created date, updated date, decision date, provisioned date
  - Each field supports both ASC and DESC sorting options.
  - Default: Updated date (DESC).

### Definition of Done (DOD)
- The search, filter, and sort functionalities operate as expected.

**Comment by funtigr** [comment]
The Search and Filtering in Private Cloud Requests tab works as expected.

**Side Note:**
Now if User or Admin goes to `Requests` tab, he sees `Inactive` requests as well.
It makes sense to the User as they will have little of them.
But for Admin can cause some confusion if Reviewer approves something in non-chronological order. But I think they will just get used to it.
