### ISSUE TITLE
Enhance Search, Filter, and Sort Functionality on Public Cloud Product Page

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3167]
### Description
Enhance the search, filter, and sort functionalities on the private cloud product page.

### Technical Details
- **Search:** Supports searching by licencePlate, name, description, and member name.
- **Filters (multi-select):**
   - status: default to active
   - ministry: default to all
   - provider: default to all

- **Sort By:** Name, description, licencePlate, status, updated date
  - Each field supports both ASC and DESC sorting options.
  - Default: Updated date (DESC).

### Definition of Done (DOD)
- The search, filter, and sort functionalities operate as expected.

**Comment by funtigr** [comment]
Search and Filtering works as expected for Public Cloud Products tab:
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5270f75cbda408dc17858f8ed315e4c5dc4cb98/image.png" alt="image.png" />
