### ISSUE TITLE
Enhance Search, Filter, and Sort Functionality on Public Cloud Request Page

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3168]
### Description
Enhance the search, filter, and sort functionalities on the public cloud request page.

### Technical Details
- **Search:** Supports searching by licencePlate, name, description, and member name.
- **Filters (multi-select):**
   - request types: default to all
   - decision status: default to pending
   - ministry: default to all
   - provider: default to all
 
- **Sort By:** Name, description, licencePlate, status, created date, updated date, decision date, provisioned date
  - Each field supports both ASC and DESC sorting options.
  - Default: Updated date (DESC).

### Definition of Done (DOD)
- The search, filter, and sort functionalities operate as expected.

**Comment by funtigr** [comment]
Search and filtering works as expected on the Public Cloud Requests tab
