### ISSUE TITLE
fix profile image bug for admin comments

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#3173]
map the correct profile image to the comment, currently it is using the image of the session user

**Comment by Amritpal-Nijjar** [comment]
<img width="1453" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXFEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f29521a87c03bb4426e75daec02aba5e4fbd5670/Screenshot%202024-06-21%20at%2011.57.09%20AM.png" alt="Screenshot 2024-06-21 at 11.57.09 AM.png" />
<img width="1453" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64984addfbfbd88819da4da59c963b03568d7663/Screenshot%202024-06-21%20at%2011.57.42%20AM.png" alt="Screenshot 2024-06-21 at 11.57.42 AM.png" />

**Comment by funtigr** [comment]
The comments have corresponding to authors avatars.
