### ISSUE TITLE
add rich text features for admin comments

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#3179]
Based on the user testing sessions, these rich text features in the mantine library should be implemented:
1) code block and line
2) quote blocks
3) links
4) lists (bullet and numbered)
5) Bold, ~italic~, strike-though, underline
6) undo redo

**Comment by junminahn** [comment]
@Amritpal-Nijjar excited to have this

**Comment by Amritpal-Nijjar** [comment]
<img width="1394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2FKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc2d43cc7046f339f19b4a4b7f8d2bc0984590a9/Screenshot%202024-06-24%20at%2011.26.24%20AM.png" alt="Screenshot 2024-06-24 at 11.26.24 AM.png" />
