### ISSUE TITLE
View the past and current request comments on the notes pages [Admin Notes/Comments]

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#3190]
There are two entities, the product and the request
A comment can be made on either a product or a request
The posted comments can only be viewed in the context of whichever entity is was made on
A product comment is only on the product, and a request comment is only on the request

We want the ability to view the past comments made on the requests of a product on the comments section of that product (currently titled Admin Notes). 

Likely to have two columns on the page, where in one column we can see all the past requests, and the comments that were made by admins under each request. That way an admin can view the past comments/notes that were made in resolved requests, and also view the notes that have been taken for that product at the same time. 

DoD: 
In the product admin notes section, have two sections:
- [ ] 1. a section to have the admin notes regarding the product itself.
- [ ] 2. a section to display the comments regarding the product's requests. (read-only)

**Comment by junminahn** [comment]
<img width="328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXJiQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f5f1a9ba25ee3f3714c28615e8d378c786cd9f9/image.png" alt="image.png" />

**Comment by funtigr** [comment]
@junminahn 
Now any product has all the comments made in the app, including ones from other products.
For example, product A has all the comments left in requests for products B, C, D and so on.

**Comment by funtigr** [comment]
Now works as expected:
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy96Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc2b2c3ccb55257cab1a5a6753a1fb26dff3bdfa/image.png" alt="image.png" />
