### ISSUE TITLE
consistent sizes of request box

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#3196]
The request box adapts to the size of the content that is inside of it. we would like for these to have consistent sizes so that they are not so jarring to users when seeing multiple requests. Also to have consistent text colours used. 

- [ ] Consistent text colours for the content inside the request box
- [ ] Consistent sizes of the tiles in the request box
- [ ] Consistent sizes of the request boxes relative to other request boxes

<img width="1187" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHlLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a30672e0f3c8e0cd8b1fd5de1319915593abdb2/Screenshot%202024-06-24%20at%202.06.57%20PM.png" alt="Screenshot 2024-06-24 at 2.06.57 PM.png" />

**Comment by junminahn** [comment]
pr: https://github.com/bcgov/platform-services-registry/pulls
note that I added a `loader` in the table list as well.

**Comment by funtigr** [comment]
Boxes for Requests are now of the same size:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWIrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27214b8cb8b4b30886110c4e5e2317bbcb0b0d68/image.png" alt="image.png" />
