### ISSUE TITLE
display the number of comments that exist on a request

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#3207]
On the requests tab the admin user would like to see a visual indicator on the requests that have a comment and the number of comments. This helps to keep track of which requests have a comment on them and thus been actioned on, and those who have yet to be actioned. This is a likely workflow that admins are to adopt based on user testing feedback...

The mantine indicator can be helpful for this: https://mantine.dev/core/indicator/

example mockup<img width="1416" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2lMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d00529ab8f7eb65a492131a769841e1576947c84/Screenshot%202024-06-24%20at%2011.38.39%20PM.png" alt="Screenshot 2024-06-24 at 11.38.39 PM.png" />

**Comment by Amritpal-Nijjar** [comment]
https://github.com/bcgov/platform-services-registry/pull/3236

**Comment by Amritpal-Nijjar** [comment]
<img width="1967" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXJIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62d2c7fe935b06552516c619d131a4755f081a8b/Screenshot%202024-06-26%20at%201.55.05%20PM.png" alt="Screenshot 2024-06-26 at 1.55.05 PM.png" />

**Comment by funtigr** [comment]
Now on Requests tab we have the number of the comments on the In Progress badge.
If there are now requests, no digits are shown.
If the comments are added it doesn't affect the number.
If the comment is deleted it is not displayed or subtracted from the number if other comments are left.
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnJIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00bdb03563df2974bd417ed978da80f1133bb40d/image.png" alt="image.png" />
