### ISSUE TITLE
[Email Sandbox] Mock CHES Service

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3225]
### Description
Since the CHES service does not follow the standard SMTP specification, we need to create a mock service to bridge the application and email service. The mock service will receive messages from the application intended for CHES and relay them to email service via the SMTP protocol. 

### Definition of Done (DOD)

- [ ] Emails sent through the mock CHES service are captured and visible in the any email service interface.
- [ ] Testing confirms that the mock service works for various email formats and content types.

**Comment by funtigr** [comment]
Mailpit receives the email from the Ches-mock service on local machine:
<img width="1463" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem9mQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b18d41e76e43906d28370f3bf586a877e30a0f4/image.png" alt="image.png" />

**Comment by funtigr** [comment]
The emails come to mailpit for Requests made on localhost as expected:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2dsQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bdb8226059606f682cb5bd2da4c7168c5b93eda3/image.png" alt="image.png" />
