### ISSUE TITLE
Histogram vs Barchart

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#3234]
In the analytics dashboard we have many charts to display certain statistics. The problem is that the tremor library only provides basic charts that are commonly used. We are using the incorrect type of chart for the `Request decision time frequency (%)`. This chart should instead be a histogram chart which is not supported by the tremor library. Although histogram and bar charts look very similar they are not the same and cannot be used interchangeably, as they each serve a specific purpose to relay information to users. See the provided screenshot and link to learn more about histogram vs bar chart. https://www.guru99.com/histogram-vs-bar-chart.html
 <img width="1060" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGlWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72bdf42f3f37aa60ff347f18595806571f90d730/Screenshot%202024-06-26%20at%201.06.04%20PM.png" alt="Screenshot 2024-06-26 at 1.06.04 PM.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ace97ae06dc3a31648be1c4e1fbe8144f876c656/Screenshot%202024-06-26%20at%201.06.37%20PM.png" alt="Screenshot 2024-06-26 at 1.06.37 PM.png" />

There is another chart we can refactor to instead use a bar chart, and that is the `Ministry per Cluster` chart. A doughnut style chart is not great overall, as humans are not great at seeing proportions or percentages in a circular fashion. It is okay for quick summarizations when there are about 5 or less elements. This chart would benefit much more from a bar chart as the screenshot above checks all the boxes for this data.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHlWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cee6b06d4015f3cebde3b033d1fac11a24a0b518/Screenshot%202024-06-26%20at%201.07.03%20PM.png" alt="Screenshot 2024-06-26 at 1.07.03 PM.png" />

**Comment by Iryna-Kaplun** [comment]
Iryna confirmed this with Alex on Dec 6. Alex thinks that this is a good idea as the pie chart is the most difficult to read. Originally, it was her idea and suggestion to Amritpal to create this ticket. Alex thinks that it's a low priority but a useful visual change.

**Comment by Iryna-Kaplun** [comment]
Alex' suggestion: 
I actually think having the first chart as a bar chart is fine upon review, however I do think we need to add a timeframe to that chart as I assume that's the average since we started tracking that metric. It'd be good for decisions over time frequency to be able to be broken down by specific time periods - that way we can see if we actually got slower to respond when say, Billy was on vacation

**Comment by Iryna-Kaplun** [comment]
This feature will be put on hold for now as per PO's (Luke) comment.
