### ISSUE TITLE
The homepage needs content and context added

### ISSUE THREAD

**Issue by juhewitt** [bcgov/platform-services-registry#324]
As a user, I would like to hit the homepage of the Project Registry, and be provided with a brief overview of the application, it's purpose and what I need to do next now that I'm here.

![image.png](https://images.zenhubusercontent.com/5d658f800f25370001090f16/0a0ad923-6160-4ef4-b007-2df93bc62dd7)

**Comment by sbathgate** [comment]
![Screen Shot 2021-07-15 at 10.19.03 AM.png](https://images.zenhubusercontent.com/5f720f05f993f11eb9af6d6f/fb4110ce-a0cc-4107-9de0-84acb84007cc)

**Comment by w8896699** [comment]
pr: https://github.com/bcgov/platform-services-registry/pull/463
