### ISSUE TITLE
[New Ui Registry]Ministry projects view role for Registry

### ISSUE THREAD

**Issue by NickCorcoran** [bcgov/platform-services-registry#328]
**Describe the issue**
Create a role for Ministry staff to see all projects in their Ministry or Ministries. 
Allow for them to export the list using the export to csv function. 

Comment from Olena from Oct 10, 2023:

> Creating a Ministry admin role in the Registry for private and public projects. This role will allow the user to see and edit all projects belonging to their Ministry.  This role will be used by people such as Ryan Louiselle and Justin Hewitt that look after the abandoned apps that belong to their Ministry.

**Additional context**
From working with Ministry Privacy and Security teams, they struggle to keep up with what projects are on OpenShift that relate to their Ministry or Ministries.  This capability would help resolve that issue.  
This role would likely also be valuable to senior business or technical staff that oversee OpenShift development for their Ministry or Ministries.
Also, providing the ability to export the list will help in their reporting on projects.

**Updates from the discussion with Nick and Ian:** 
[Oamar to provide the info]

**UPDATE**
We will create hard coded ministry roles like `CITZ

**Definition of done**
Ministry IMB manager role (view and edit Ministry projects) is created
GIVEN a user has been granted ministry  IMB manager role
WHEN they login to the Projects home page (public or private) the registry reads their Ministry for the IDIR token
THEN they should be able to see and edit all ministry related projects

**Comment by okanji** [comment]
After meeting with Nick and Ian, we have decided that we will create ministry roles using the current ministry list we have in the registry.

**Comment by funtigr** [comment]
Now we have admin roles set in the KeyCloak that are mapped to the ministries available in the Registry.
If user has one of these roles, he can see his products (whatever ministry he is in) and the products of the ministry mentioned in his role. 
If a user has two such roles, he can see all the products of two corresponding ministries and his own products.
If a user is not admin and doesn't have ministry admin roles assigned, he can see only his products.
