### ISSUE TITLE
Search Input Clear Button

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3296]
Regarding the previous ticket (https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/2891), we want to enhance the behavior of the clear button in the search input field.

1. Display the X button only when there is text in the input field.
2. Show a hover tooltip explaining the button's function when it is displayed.

**Comment by Kolezhanchik** [comment]
works as expected <img width="680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d18dfa992a5a769f8b7baff6a4e16d0d75f0e3a0/AD2ADF31-7EA1-41B4-BE08-F72FB9C233E9_4_5005_c.jpeg" alt="AD2ADF31-7EA1-41B4-BE08-F72FB9C233E9_4_5005_c.jpeg" />
