### ISSUE TITLE
Restriction on the distinct PO and TL

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3314]
### Description
Implement a restriction on the product page to ensure that the PO and TL have different IDIR accounts.

### Technical Details
Enhance the `zod` schema that validates the product data to enforce that the `idir` fields for PO and TL are distinct.

### Definition of Done (DOD)
An error is thrown when creating or updating a product if the same IDIR user is set for both PO and TL.

**Comment by funtigr** [comment]
Now there is a restriction for Create and Edit Request for same PO and Primary TL:
<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDYxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5f89e77588b9dc9f37893ce764883843efb46e5/image.png" alt="image.png" />
