### ISSUE TITLE
team service accounts - Backend core

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3332]
We want to update the API core function to:

1. accept the authorization header generated by team service accounts.
2. grant the privileges based on `roles` attribute of the token.

**Comment by junminahn** [comment]
PR: https://github.com/bcgov/platform-services-registry/pull/3342

**Comment by junminahn** [comment]
@funtigr 
1. the email must exist on Keycloak to assign the role to the user; I will add an error if the user does not exist.
2. it works for me, can you try again?
3. it is more design choice but the way it looks now is pretty common when adding multiple strings on the form.
ex) https://www.telerik.com/kendo-react-ui/components/form/field-array/

**Comment by funtigr** [comment]
If I input an email non-existing in KeyCloak (e.g. make a typo in my email) and then correct and click `Save`, I see the accounts created for all previous attempts. If I input three bad emails and then one correct email, I see four accounts: 
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGJ4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7076c9aabeb9ae5aae173f196518428e2b1d3e34/image.png" alt="image.png" />

**Comment by funtigr** [comment]
I still face that bug with multiple accounts:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenZ5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d843cf55c4526913664c12864b242e9f46074127/Screen%20Recording%202024-07-18%20at%204.37.43%E2%80%AFPM.mov)

**Comment by funtigr** [comment]
Now if someone inputs a bad email that doesn't have IDIR the popup shows the Close button. And creates the account after clicking it. If no valid emails are present, it will make an account without any emails. They can be added in the account afterwards.
