### ISSUE TITLE
Enhance current deployment flow to eliminate human errors

### ISSUE THREAD

**Issue by yhfreeman** [bcgov/platform-services-registry#336]
**Describe the issue**
The registry team had a case where the code on a development branch got accidentally pushed into production environment. As a team member, I'd like to enhance the current deployment flow to eliminate such human errors.

**Additional context**
Before the complete version of testing and pipeline (defined in #192 ) is in place for project registry, a solution is needed to replace the manual step of tagging the `latest` image to each environment.

Create new GitHub Actions for each of the DB, API, and WEB components so that we are no longer using the "latest" tag, which gets applied automatically via the BuildConfig.  Tag each new build with the commit ID and with "dev".  The "dev" tag will cause the Dev environment to be updated with the new build.  Promotions to Test and Prod will be based on the dev tag (promoting to Test) and the "test" tag (when promoting to Prod).  This will prevent accidental promotions of "latest" to Test and Prod.

**Definition of done**
When the GitHub Actions for each component are in place and tested.

**Comment by IanKWatts** [comment]
I'm looking into this now.

**Comment by IanKWatts** [comment]
The new GitHub Actions are listed as:
DEV Build and Tag - API
DEV Build and Tag - DB
DEV Build and Tag - WEB

They have been tested by the team.  Closing this ticket.
