### ISSUE TITLE
Change title of product page from "Private Cloud OpenShift Platform" to product name

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#3361]
As a user, I get confused when looking at requests tab within a product page and the general request dashboard. I get mixed up when trying to navigate between the two. 

Task: I'd like for us to change the main headings of all product pages from stating the platform to stating the product name as written in the Registry. Underneath the product name, we can have platform type. For example, it would be "Alex Test" in say H1 and underneath it (left aligned as well) would be "Private Cloud OpenShift platform" in say H3. Note the sentence case used here (lower case "p" for platform) - we should be using that for all titles across the Registry ("Product description" not "Product Description).

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/3361?planning-poker) with Zenhub @Amritpal-Nijjar @funtigr @golebu2020 @junminahn @Kolezhanchik

**Comment by alexandralloyd** [comment]
Here's what I mean: 
<img width="1609" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0692ac8cc65e5d824a2dd2b96d18e08f9667b3da/Screenshot%202024-08-27%20at%205.02.20%20PM.png" alt="Screenshot 2024-08-27 at 5.02.20 PM.png" /><img width="1938" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUdSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3fe41917db761e699470f65d55831e00500e8f4/Screenshot%202024-08-27%20at%205.02.13%20PM.png" alt="Screenshot 2024-08-27 at 5.02.13 PM.png" />

**Comment by junminahn** [comment]
<img width="802" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1nQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db24618ba27d0bee94955d19991c5b4a1f6ccb0c/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Now we have the name of the product as main Heading and the platform in smaller font for both Private and Public Cloud:
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f664d88fb42c008f58a68bcb9e46c8aeb87d5ceb/image.png" alt="image.png" />
