### ISSUE TITLE
Rearrange the namespace order to dev, test, prod, tools (left to right).

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#3362]
**Describe the issue**
Rearrange the namespace order on the product page to dev, test, tools, prod (left to right).

**UPDATE: The product team decided to have the following order: dev, test, prod, tools**

**Rational/Why**
As a user I change the dev namespace the most, so I'd like to see it first on the page instead of prod.

**Additional Context**
Came from user testing 

**Dependencies**

**Tests**

**Definition of done/Acceptance Criteria**

- Clear description of the intended final result
- Acceptance criteria that describes the action a User Acceptance Tester would be trying to see if the work is complete

**Comment by junminahn** [comment]
@alexandralloyd @funtigr 
This ticket appears to conflict with an existing ticket (#3288), which was created based on feedback from another user.<img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVA4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f59658b8149584de86f7208bf78033d97fe68722/image.png" alt="image.png" />

**Comment by Iryna-Kaplun** [comment]
The product team decided to have the following order: dev, test, prod, tools

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/3362?planning-poker) with Zenhub @Amritpal-Nijjar @funtigr @golebu2020 @junminahn @Kolezhanchik

**Comment by funtigr** [comment]
Now we have the order: **Prod**, **Tools**, **Test**, **Dev**:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3JoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adb49ee60b696fce5bfca2cd3c951f1ae8b41b56/image.png" alt="image.png" />

As far as I remember, we were going to do **Dev**, **Test**, **Prod**, **Tools**.

**Comment by funtigr** [comment]
The order changed to the one we decided on mutual meeting:
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2JoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--211c9487e45e4acb074e6a8d7f6c4eebfb305c82/image.png" alt="image.png" />
