### ISSUE TITLE
Highlight changes to quota with box around the namespace

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#3364]
**Describe the issue**
In the Platform Services Registry, when a new quota amount is selected (for both increase or decrease), a thin blue box should appear around the namespace in order to visually indicate to the user that the inputs for that namespace have changed. The current quota amount and the requested quota amount should then be listed underneath the specific dropdown menu that was changed.

**Rational/Why**
As an admin, I want to be able to quickly identify which namespaces the quota change is in. As a user, it's helpful to see what the prior input was as well as the current input (as I may want to change the current input to the prior input if I made a mistake)

<img width="1063" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXp3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aec7c51f52a668d4ac3a781dc7bfe6df67cd2c4b/Screenshot%202024-07-18%20at%209.51.28%20AM.png" alt="Screenshot 2024-07-18 at 9.51.28 AM.png" />

**Additional Context**
Request originally from Billy, but users found it useful during testing

**Tests**

**Definition of done/Acceptance Criteria**

- Clear description of the intended final result
- Acceptance criteria that describes the action a User Acceptance Tester would be trying to see if the work is complete

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/3364?planning-poker) with Zenhub @Amritpal-Nijjar @funtigr @golebu2020 @junminahn @Kolezhanchik

**Comment by funtigr** [comment]
The changed Quota is highlighted now:
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzdnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17b9adb6a3aca2c5c054081c7e8c750dc0e835eb/image.png" alt="image.png" />

<img width="1470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0RoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b077057551ea1ae12b67de2920bcc94997a463f0/image.png" alt="image.png" />

<img width="1464" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--835cdec94e1c07b41f1e25a7d5696c123fc17266/image.png" alt="image.png" />
