### ISSUE TITLE
Change all registry titles to sentence case

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#3365]
**Describe the issue**
Change all registry titles to sentence case. Sentence case is "[when] you capitalize just the first letter of the first word in the title. The rest of the words and letters in the title should not be capitalized, unless they're proper nouns." 

**Rational/Why**
As a designer, I want all of our product's to align with BC gov web standards. That mean's implementing sentence case in the Platform Registry.

**Additional Context**
It's an accessibility issue and is mandated by the BC Gov web style guide.
Capitalization and names in web content: https://www2.gov.bc.ca/gov/content/governments/services-for-government/service-experience-digital-delivery/web-content-development-guides/web-style-guide/writing-guide/capitalization

Here's all the corrections I could find looking at Private Cloud section of the site:

- "[Products in Private Cloud OpenShift Platform](https://registry.developer.gov.bc.ca/private-cloud/products/all)" to "Products in Private Cloud OpenShift platform"
- "[Private Cloud OpenShift Platform](https://registry.developer.gov.bc.ca/private-cloud/products/d0afa3/edit)" to "Private Cloud OpenShift platform"
- "1. Product Description" to "1. Product description", "Product Name" to "Product name", "Hosting Tier" to "Hosting tier"
- "3. Team Contacts" to "2. Team contacts", "Product Owner Email" to "Product Owner email", "Technical Lead Email" to "Technical Lead email", "First Name" to "First name", "Last Name" to "Last name", "After-Hours Support Contact (optional)" to "After-Hours support contact (optional)"
- "Production Namespace" to "Production namespace", "Tools Namespace" to "Tools namespace", "Development Namespace" to "Development namespace", "Test Namespace" to "Test namespace"
- "4. Common Components" to "4. Common components"

Here's all the corrections to Public Cloud product pages that I could see:
- "1. Product Description" to "1. Product description", "Product Name" to "Product name", "Cloud Services Provider" to "Cloud service provider"
- "Production Account" to "Production account", "Development Account" to "Development account", "Test Account" to "Test account", "Tools Account" to "Tools account"
- "3. Team Contacts" to "2. Team contacts", "Product Owner Email" to "Product Owner email", "Technical Lead Email" to "Technical Lead email", "First Name" to "First name", "Last Name" to "Last name", "After-Hours Support Contact (optional)" to "After-Hours support contact (optional)"
- "Expense Authority Email" to "Expense Authority email", "First Name" to "First name", "Last Name" to "Last name"
- "5. Project Budget" to "5. Project budget", "Estimated average monthly spend - Development Account" to "Estimated average monthly spend - Development account", "Estimated average monthly spend - Test Account" to "Estimated average monthly spend - Test account", "Estimated average monthly spend - Production account" to "Estimated average monthly spend - Production account", "Estimated average monthly spend - Tool Account" to "Estimated average monthly spend - Tool account", "Total Estimated average monthly spend" to "Total estimated average monthly spend"
- 6. Billing (Account Coding) to 6. Billing (Account coding)

**Dependencies**

- Internal, external, who to talk to if more information is needed

**Tests**

**Definition of done/Acceptance Criteria**

- Clear description of the intended final result
- Acceptance criteria that describes the action a User Acceptance Tester would be trying to see if the work is complete

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/3365?planning-poker) with Zenhub @Amritpal-Nijjar @funtigr @golebu2020 @junminahn @Kolezhanchik

**Comment by funtigr** [comment]
As far as I see we still have some title not changed to `sentence case`. 
1. The component for reasoning of choosing particular `Cloud Provider` in `Public Cloud`: 
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXhXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c87a5b4dabc2beede37056bbb200282d68b85ebb/image.png" alt="image.png" />

2. The component showing status of eMOU:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekpXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cef48ec96f712c839789a68a830acca093bf2c88/image.png" alt="image.png" />

3. Items in `Select Reason for Choosing Cloud Provider` dropdown:
<img width="1485" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemxXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c80901b446c7a888ab018a3b23273f835088b2b9/image.png" alt="image.png" />

4. Titles on `Resource Usage` tab in `Private Cloud`:
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4edddf2a8c91db48d9d993ff0bc4d6ca3b68d4c/image.png" alt="image.png" />

5. Menu items on `Security` tab in `Private Cloud`:
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME5XQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e024c130dec2ea4e35d86d46e74b52875c503e13/image.png" alt="image.png" />

6. `Admin Comments` tab buttons and tooltip:
<img width="1545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--988a33e26c9db5ab527b283a10af4820d4248ee8/image.png" alt="image.png" />
<img width="673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--651f506669fa1871bfc5f8042dbebe1f7ea00b14/image.png" alt="image.png" />

7. In the banner `Temporary Product` in Private Cloud:
<img width="1475" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHRXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f8aad13fbd942d46476731767a743c5293cb8cf/image.png" alt="image.png" />

@alexandralloyd could you please review the screenshots in this comment and approve or disapprove the necessity of changes in the existing case?

@junminahn if the fixes would be needed should we do it in a separate task as second iteration?

**Comment by junminahn** [comment]
@funtigr yes, as I was focusing on the ones on the ticket description, there might have more places to be updated. let's create a new ticket as it also requires a review by Alex as well.

**Comment by funtigr** [comment]
Made a separate task for that:
https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/4010

All changes from the original task description are implemented.
