### ISSUE TITLE
Add new contact fields for quota increase

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#3368]
**Describe the issue**
Add new fields for contact info (name and email) for all **increases**  of quota increases. These fields will require inputs from users in order to submit their quota increase request. This information would just be captured for admin use - no automatic emails would go to this email. These fields would appear at the end of the quota section, and only appear once the user has selected a higher quota in the drop down menu.

**Rational/Why**
As an admin, I want to be able to email contractors or non-product contacts about quota requests. 

**Additional Context**
- Within Platform Registry
- I've added some additional text for clarity based on user testing
- May want to check in with Nick before we go live <img width="1788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW54QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f8e03ec7ffddf08d323813213301d82a26b59e3/Screenshot%202024-07-18%20at%2011.52.10%20AM.png" alt="Screenshot 2024-07-18 at 11.52.10 AM.png" />

**Dependencies**
- Once this change goes live, we need to change the current language on the documentation page

**Tests**

**Definition of done/Acceptance Criteria**

- Clear description of the intended final result
- Acceptance criteria that describes the action a User Acceptance Tester would be trying to see if the work is complete

**Comment by funtigr** [comment]
- Now new fields appear on the page if the quota increase is chosen in one of quota dropdowns.
- If the quota changed to the same or lower, the fields hide again. 
- The name is a regular text field and the email looks for the input to correspond to email format but doesn't check for IDIR.
- The fields do not show up anywhere in the emails and decision/product/request pages.

<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2dKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--913a648908a2e17105d7c6e51b0c2ee500a4399c/image.png" alt="image.png" />
