### ISSUE TITLE
Email notifications to product team members regarding the automatic scheduled Temporary products deletion request

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3372]
Send an email notification about the temporary product deletion 2 weeks before the deletion

**Comment by funtigr** [comment]
@junminahn 
I set 3 Temp documents `createdAt` field for July 11, July 12 and July 13 to cover 15, 16 and 17 days ago, but after running the task in Airflow I didn't receive any emails. Let's try it together.

**Comment by funtigr** [comment]
The notifications work as expected: 
<img width="1321" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL01KQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aae6f80e1e7de23943b73075db37af817b6b211b/image.png" alt="image.png" />
