### ISSUE TITLE
E2E - Convert Gherkin language test into E2E Automation Tests - Approve & Delete Request

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3374]
Private cloud:
platform-services-registry/cypress/integration/approve-request-test.feature
platform-services-registry/cypress/integration/delete-product-test.feature

Public cloud: [Artem to update the links]
platform-services-registry/cypress/integration/approve-request-test.feature
platform-services-registry/cypress/integration/delete-product-test.feature

**Comment by funtigr** [comment]
Link to a PR: https://github.com/bcgov/platform-services-registry/pull/3493
