### ISSUE TITLE
Team Email addition to Team Contact

### ISSUE THREAD

**Issue by fergmac** [bcgov/platform-services-registry#3440]
Request:
Currently we can add a PO and 2 Tech Lead Contact's to the OpenShift registry. We would like to be able to add our team email as a contact. 

Context:
Team members graduate from our team on a 6 month to 1 year timeline. We take on applications that have not had an active team maintaining them. The registry Team Contacts section can be out of date when we pick up an application.

During our team onboarding/offboarding we update the Team Contacts section.

Due to flex days and needing coverage we would like the entire team to have insight into OpenShift related issues that arise. We can currently create an email rule that forwards emails to the team email. But this is another thing we need to manually update when a dev leaves/graduates to another team.

**Comment by Iryna-Kaplun** [comment]
This ticket can be related to the ticket about the Other Contacts #

**Comment by Iryna-Kaplun** [comment]
This work will be compete with the ticket #3097 that is almost completed and is in testing now.
