### ISSUE TITLE
Private Cloud Request: Summary tab doesn't show Quota Memory change for Test Namespace

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#3456]
**Description**:
In Private Cloud Request, Summary tab doesn't show Quota Memory change for Test Namespace

Summary tab of the Request for both User and Admin look like this:
<img width="1464" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1a829eb34eaab39587fbd164d30bd5be1720097/image.png" alt="image.png" />

User Request tab of the Request for User:
<img width="1455" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVVvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58d05e353a63df734349b778c9a10631d861c1bd/image.png" alt="image.png" />

Meanwhile Decision Page for Admin shows Quota change as expected:
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVlvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e26386716ecf22b7fbbbc8ee1bb0949f6856a3b9/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
it is shown in summary tab.in different section <img width="1552" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZ5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--009adfe8af32ace2bc48a07281ab9b258afa71f5/image.png" alt="image.png" />

**Comment by junminahn** [comment]
Exactly

**Comment by funtigr** [comment]
Oh, I see. In this case we can cancel this one.
