### ISSUE TITLE
API Research spike for resource table

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#3471]
**Describe the issue**
Research spike needed to assess the viability of the repopulated current resource usage table in the Registry. This table would repopulate information from the OCP console.

The goal of this spike would be to find out:
1) What the API endpoint is and 
2) What data is available for pre-population

**Rational/Why**
Billy finds this info very useful for action quota adjustment requests, and all the users we tested this table with really liked having this info available in an easy to read UI. I think this would help bring awareness to proper resource utilization on the platform. 

**Additional Context**
Relates to epic #5073 and #4565 in the Platform Experience board. 

<img width="1577" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEZFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7af82dacade6593c2f110d7e3231c6e3e37f87a2/image.png" alt="image.png" />

**Dependencies**
- [x] Let Alex know about the viability of the table and want info is available so she can revise mockups

**Tests**

**Definition of done/Acceptance Criteria**
- [x] Two main questions are answered
- [x] Next steps are outlined

**Comment by Kolezhanchik** [comment]
`GET` /api/v1/namespaces/{namespace}/pods/`


the Request URL:
Use the following format:

`https://<kubernetes-api-server>/api/v1/namespaces/<namespace>/pods`

Replace `api-server` with your Kubernetes API server's address. 
terminal `cat ~/.kube/config`
res `server: https://api.silver.devops.gov.bc.ca:6443`
Replace `namespace` with the specific namespace from which you want to list the pods.(e.g. silver, gold, emerald, golddr) 

`https://api.silver.devops.gov.bc.ca:6443/api/v1/namespaces/101ed4-test/pods/`

Authorization Header
`Accept:application/json`
`Authorization: Bearer <bearer-token>` - got from oc login line, it is a temporary one. Talked to Cailey, she supposes it is possible to provide registry itself permission to get service account token.

Response: 

{
    "kind": "PodList",
    "apiVersion": "v1",
    "metadata": {
        "resourceVersion": "11152882246"
    },
    "items": [
        {
            "metadata": {
                "name": "pltsvc-app-669c5ff5b8-74m7n",
                "generateName": "pltsvc-app-669c5ff5b8-",
                "namespace": "101ed4-test",

[response.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGlSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4673b04c31c97f5de9356ef2c9be02cc33171add/response.txt)

`GET /api/v1/namespaces/{namespace}/pods/{name}/status`
`https://api.silver.devops.gov.bc.ca:6443/api/v1/namespaces/101ed4-test/pods/pltsvc-app-669c5ff5b8-74m7n/status`

Response

`spec/initContainers/resources {
                    "limits": {
                        "cpu": "100m",
                        "memory": "64Mi"
                    },
                    "requests": {
                        "cpu": "50m",
                        "memory": "32Mi"
                    }
                },`

 `spec/containers/resources: {
                    "limits": {
                        "cpu": "300m",
                        "memory": "512Mi"
                    },
                    "requests": {
                        "cpu": "30m",
                        "memory": "128Mi"
                    }
                },`

 
[response2.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1SQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a004939cbf5a91ff3cfccab5db45a30dbbce1d57/response2.txt)

**Comment by Kolezhanchik** [comment]
shows running pods metrics 
`mautic-40-j496b [
  { name: 'mautic', usage: { cpu: '0', memory: '242036Ki' } },
  { name: 'POD', usage: { cpu: '0', memory: '0' } }
]
mautic-db-25-w5wpd [
  { name: 'mariadb', usage: { cpu: '4m', memory: '1678340Ki' } },
  { name: 'POD', usage: { cpu: '0', memory: '0' } }
]
mautic-db-backup-3-ntbf6 [
  { name: 'mautic-db-backup', usage: { cpu: '0', memory: '224888Ki' } },
  { name: 'POD', usage: { cpu: '0', memory: '0' } }
]
mautic-subscription-api-prod-9-65w4g [
  {
    name: 'mautic-subscription-api-prod',
    usage: { cpu: '0', memory: '23072Ki' }
  },
  { name: 'POD', usage: { cpu: '0', memory: '0' } }
]
mautic-subscription-api-prod-9-fp2nx [
  {
    name: 'mautic-subscription-api-prod',
    usage: { cpu: '0', memory: '11624Ki' }
  },
  { name: 'POD', usage: { cpu: '0', memory: '0' } }
]
mautic-subscription-api-prod-9-q7rcl [
  {
    name: 'mautic-subscription-api-prod',
    usage: { cpu: '0', memory: '15192Ki' }
  },
  { name: 'POD', usage: { cpu: '0', memory: '0' } }
]
mautic-subscription-prod-39-d9hx5 [
  {
    name: 'mautic-subscription-prod',
    usage: { cpu: '0', memory: '18864Ki' }
  },
  { name: 'POD', usage: { cpu: '0', memory: '0' } }
]`

<img width="693" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWFnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2316e55d1f701a92944764497253876ced6467d/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
figma mockup https://www.figma.com/design/jsrhMxnmN4awqlbU8LuyuK/Quota-Redesign?node-id=1141-2500&node-type=CANVAS&t=L19ZYUXAX9jlE7NQ-0

**Comment by Kolezhanchik** [comment]
responce 
[
  {
    "name": "mautic-40-j496b",
    "usage": {
      "cpu": "0",
      "memory": "248484Ki"
    },
    "limits": {
      "cpu": "1",
      "memory": "2Gi"
    },
    "requests": {
      "cpu": "50m",
      "memory": "1Gi"
    }
  },
  {
    "name": "mautic-db-25-w5wpd",
    "usage": {
      "cpu": "5m",
      "memory": "1678460Ki"
    },
    "limits": {
      "cpu": "1",
      "memory": "2Gi"
    },
    "requests": {
      "cpu": "1",
      "memory": "2Gi"
    }
  },
  {
    "name": "mautic-db-backup-3-ntbf6",
    "usage": {
      "cpu": "0",
      "memory": "0"
    },
    "limits": {
      "cpu": "0",
      "memory": "0"
    },
    "requests": {
      "cpu": "0",
      "memory": "0"
    }
  },
  {
    "name": "mautic-subscription-api-prod-9-65w4g",
    "usage": {
      "cpu": "0",
      "memory": "23084Ki"
    },
    "limits": {
      "cpu": "1",
      "memory": "80Mi"
    },
    "requests": {
      "cpu": "10m",
      "memory": "40Mi"
    }
  },
  {
    "name": "mautic-subscription-api-prod-9-fp2nx",
    "usage": {
      "cpu": "0",
      "memory": "11620Ki"
    },
    "limits": {
      "cpu": "1",
      "memory": "80Mi"
    },
    "requests": {
      "cpu": "10m",
      "memory": "40Mi"
    }
  },
  {
    "name": "mautic-subscription-api-prod-9-q7rcl",
    "usage": {
      "cpu": "0",
      "memory": "15164Ki"
    },
    "limits": {
      "cpu": "1",
      "memory": "80Mi"
    },
    "requests": {
      "cpu": "10m",
      "memory": "40Mi"
    }
  },
  {
    "name": "mautic-subscription-prod-39-d9hx5",
    "usage": {
      "cpu": "0",
      "memory": "18876Ki"
    },
    "limits": {
      "cpu": "50m",
      "memory": "60Mi"
    },
    "requests": {
      "cpu": "10m",
      "memory": "30Mi"
    }
  }
]
