### ISSUE TITLE
Fix the email in Public Cloud Azure Approved email

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#3480]
Now the email in the lower text block of the Public Cloud Azure Approved email doesn't have spaces around it and it mentions a person instead of the team email. 
Abibat asked to change it back to the team email `cloud.pathfinder@gov.bc.ca`:
<img width="988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0U1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9928cd2751f36926304b1dfbb3dd01eda7df6642/image.png" alt="image.png" />

**Comment by junminahn** [comment]
@funtigr nice screenshot that is encrypted very well so that I cannot decrypt it :)

**Comment by Iryna-Kaplun** [comment]
This bug has been fixed already.
