### ISSUE TITLE
Public Cloud eMOU Form - Workflow Diagram

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3502]
Initial diagram for the current process: 
https://miro.com/app/board/uXjVKyTKbkI=/

**Comment by junminahn** [comment]
@lukegonis https://github.com/bcgov/platform-services-registry/blob/main/docs/emou-workflow.md

**Comment by lukegonis** [comment]
@junminahn looks good to me, thank you.
