### ISSUE TITLE
Add a link to the quota increase document

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/platform-services-registry#355]
**Describe the issue**
We have some guidelines for app teams before they request for a quota increase. Doc is here: https://developer.gov.bc.ca/Need-more-quota-for-OpenShift-project-set

The plan is to add the ref link in Registry and make sure teams have read and completed the documented steps before they submit the quota increase request.

**Definition of done**
- [ ] some sort of confirmation window for teams to go through the guideline doc before submitting quota increase request

**Comment by w8896699** [comment]
PR: https://github.com/bcgov/platform-services-registry/pull/460
