### ISSUE TITLE
capitalize CPU in the summary section of a request

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#3573]
<img width="1426" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlYrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--530c58aebde351e47c6aa2cb2cc8456de0f94e43/Screenshot%202024-08-22%20at%2011.04.50%20AM.png" alt="Screenshot 2024-08-22 at 11.04.50 AM.png" />

**Comment by funtigr** [comment]
Looks like the change is still not in Dev:
<img width="1483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVRxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--238984ab3fb73d9a04862be584bbbe128820fd77/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Hm, I see it changed on Test though. So there are some features that are not synced yet:
<img width="1463" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWJxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--101b7afb67a0feb222cf3d1d82b97846e84aa7bc/image.png" alt="image.png" />
