### ISSUE TITLE
ProjectNamespace type does not match database schema

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#358]
In the `ProjectNamespace` type, the properties of the type does not match the table schema:

```
export interface ProjectNamespace extends CommonFields {
  name: string;
  profileId: number;
  clusters?: ClusterNamespace[];
}
```

The field `clusters` does not apply to the database schema and it's not used anywhere in in the `NamespaceModel` class. It should probably be removed to better reflect the table it is associated with.

**Comment by yhfreeman** [comment]
@jleach Thanks for your feedback. It was initially added because of the logics @ Namespace.findForProfile for bots message structure. Will remove it.

**Comment by yhfreeman** [comment]
The field `clusters` is now removed.
