### ISSUE TITLE
Automate setup of pull credentials for Artifactory service accounts

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#359]
As per Wade's comment in [this Q&A](https://github.com/BCDevOps/OpenShift4-Migration/issues/51), automate the set up of pull credentials and linking them to the Artifactory service accounts as part of the project provisioning through the Registry (please get Cailey's input in the design of this feature).

**Comment by WadeBarnes** [comment]
Just wondering where this is in the pipeline.  Teams keep tripping over docker rate limiting and the setup to use Antifactory.  This experience should, and can easily, be completely transparent to them.

**Comment by mitovskaol** [comment]
@WadeBarnes  I bumped the priority on this. Things have been moving slow with Artifactory over the last couple of Sprint due to other competing priorities but we are bringing an additional Arctiq's resource to help @jefkel with Artifactory work. I will see to it that this ticket is included in the next Sprint's backlog (the next Sprint starts on April 28).

**Comment by caggles** [comment]
If the goal is to allow teams to pull from artifactory automatically without requiring any work on their part, it would be better if we could make a cluster-wide default. Using the artifactory service account object this way would potentially require the operator taking additional control of more objects in a given namespace, which we should not do unnecessarily. We are investigating the possibility of a cluster-wide default option in BCDevOps/developer-experience#1126.
