### ISSUE TITLE
API Registry & MailChimp - Removed Label Bug

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3606]
Some contacts in the MailChimp don't have any label applied and they've been added/updated through the API Registry. 

After investigating the downloaded list of all the private cloud contacts from the Registry, I found many emails that are still registry contacts but don't have an appropriate label in MailChimp.

Example of the contacts: 
- krishna.rajendharan@gov.bc.ca
- saranya.viswam@gov.bc.ca
- nicole.vukosavljevic@gov.bc.ca

DoD:

- [x] investigate this API Registry & MailChimp bug
- [x] ensure that all the Registry contacts for the private cloud products have the appropriate label ("Registry Contacts for Private Cloud - DO NOT DELETE") applied in MailChimp

**Comment by junminahn** [comment]
@Iryna-Kaplun please confirm when you have a chance and move the ticket closed. thanks.

**Comment by funtigr** [comment]
We have checked. Thanks, works as expected.
