### ISSUE TITLE
Subscribe Website Update

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3612]
https://subscribe.developer.gov.bc.ca/subscription

Update the current Subscribe website moving the info about the Private Cloud new sign up form to either: 
- to the bottom of the list
OR
- make it in black to stand out and move it a bit down from the header

<img width="1054" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXlRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6b8bc25ba99e77940a0d0a47ee7c50a12876892/Screenshot%202024-08-27%20at%202.14.31%E2%80%AFPM.png" alt="Screenshot 2024-08-27 at 2.14.31 PM.png" />

**Comment by Kolezhanchik** [comment]
[Uploading... image.png]
