### ISSUE TITLE
Automate resource quota change review logic - Backend Logic and Endpoint

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3635]
Billy's ticket for reference: 
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5082

1. Decrease Request: Automatically approved regardless of the conditions.
2. Increase Request (CPU/Memory): Approved if the namespace meets the following:
- Current usage exceeds 85% of the total limit.
- Utilization rate is at least 35%.
- Usage-to-limit ratio is greater than 10%.(may be, lets not implement it for now)
- The request is only for the next quota tier.

DoD:

- [ ] - some requests (requests included in the above code) should be auto approved in the Registry

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/3635?planning-poker) with Zenhub @Amritpal-Nijjar @funtigr @golebu2020 @junminahn @Kolezhanchik

**Comment by Kolezhanchik** [comment]
https://github.com/siimon/prom-client
