### ISSUE TITLE
Add Cloud provider selection reason (Text field) for Public Cloud

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/platform-services-registry#3636]
As a Platform Administrator, I want to track reasons that lead to a cloud service provider selection, so that I can report on those reasons for procurement requirements and also feed data to our service design research.

**ADDITIONAL Requirements:** 
Please see the comments below.

**Acceptance Criteria:**

1. On the Product Registry, when provisioning a new project, or editing an existing one, add a "Cloud provider selection" section just below/after the "Cloud service provider" dropdown section.
2. This should be a text field, character limit 1000. (similar look and feel as the "Description field above").
3. Explanation text below: "Please provide a short description of the reason(s) that lead you to select this cloud service provider."
4. For any new project provisioning, make this field mandatory.
5. For any existing project, this should be blank, and mandatory to answer when a user comes in and wants to save changes (prompt them to fill out this field).
6. Add this field to the **CSV** export.

**Comment by ThibaultBC** [comment]
As a Platform Administrator, I want to track reasons that lead to a cloud service provider selection, so that I can report on those reasons for procurement requirements and also feed data to our service design research.

Acceptance Criteria:

1. On the Product Registry, when provisioning a new project, or editing an existing one, add a "Cloud provider selection" section just below/after the "Cloud service provider" dropdown section.
2. This should be a text field, character limit 1000. (similar look and feel as the "Description field above").
3. Explanation text below: "Please provide a short description of the reason(s) that lead you to select this cloud service provider."
4. For any new project provisioning, make this field mandatory.
5. For any existing project, this should be blank, and mandatory to answer when a user comes in and wants to save changes (prompt them to fill out this field).

**Comment by ThibaultBC** [comment]
Note: This is initially required for Public Cloud, but my suggestion is it would also be useful information for Private Cloud projects.

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/App-Dev-Team-646fdb4400ed8c0021aceeb4/issues/bcgov/platform-services-registry/3636?planning-poker) with Zenhub @Amritpal-Nijjar @funtigr @golebu2020 @junminahn @Kolezhanchik

**Comment by Kolezhanchik** [comment]
questions:
should this info be shown on product page for users and/or admins 
should this info be included in email notifications, nats-messages
add this filed to export - does it mean to add it to eMOU or .csv file with list of products? 
answers from Thibault:
No need to display it on the product page
Not sure what's the nats-message, emails notifications: no need to edit the emails with this info.
Export: I meant the CSV export that we can access from the products page (cf. screenshots)

**Comment by ThibaultBC** [comment]
Hello,
Following up on a discussion with Olena, we would like to add a dropdown field, in order to make this result more easily extractable for statistics.
This doesn't change the previously laid out acceptance criteria, but there will be an addition to this ticket.

1. In the "Cloud Provider Selection" section, above the text field, add a dropdown field, with the default option being "Select reason"
2. Options available in the dropdown list are as follow:

- Cost Efficiency
- Scalability Needs
- Security Level
- High Availability/Disaster Recovery features
- Specialized Cloud Services (e.g., AI/ML, Big Data)
- Vendor Preference
- My Team Expertise
- Internal Support Level within OCIO,
- Project-Specific Requirements
- Other
 
3. Text below the dropdown space "Please select the main reason that led your choice of cloud provider."
4. Both fields (the dropdown, and the text description) are mandatory.

**Comment by junminahn** [comment]
@golebu2020 you can use `mantine`'s multi select component:
https://mantine.dev/core/multi-select/

**Comment by Kolezhanchik** [comment]
public cloud,(at least for now)

**Comment by funtigr** [comment]
Now we have a new field and dropdown for the reasons of provider selection. Textfield has limit for 1000 characters.
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29WQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38abac249b7bef5fa421298f43bdaa994d2e61ec/image.png" alt="image.png" />

The CSV has the fields listed:
<img width="1407" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3dWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9486339f826734158dd60a84a085279fcc45ac32/image.png" alt="image.png" />

**Comment by funtigr** [comment]
We checked the bug with Cloud provider choice reason with Prabhu.
The issue occurred because the Request was created before the deployment of the feature.
And the attempt to Review it was made after the deployment of the feature. 
This way the fields were left empty but were already needed while reviewing.
