### ISSUE TITLE
Multiple App versions in the footer

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#3641]
On Dev we have multiple App version blocks in the footer:
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNCtjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea6607a2bf63132507fc28a6c8e6abe0b64e59a2/image.png" alt="image.png" />

**Comment by funtigr** [comment]
We still have two App Versions on the Requests Tab:
<img width="1475" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzJ1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b158bb81286b6e6734935f21243ab9bb8b30830/image.png" alt="image.png" />

**Comment by junminahn** [comment]
@funtigr the dev is failed to deploy the changes.

**Comment by funtigr** [comment]
Fixed
