### ISSUE TITLE
Update PO information for BC Data Catalogue OCP4 namespaces

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/platform-services-registry#365]
**Describe the issue**
@TerryLanktree is now the PO for the BC Data Catalogue and related technologies.  Accordingly, we need to update the contact information for the related OCP4 namespaces.

**Definition of done**

For the relevant namespaces, please update the contact information to remove @SteveChapmanBCDX as PO and replace him with @TerryLanktree.

These are the relevant OCP4 namespaces:
* 40db83-XXX ("BCDC"); and
* dab7fb-XXX ("DataBC")

Thanks for your assistance!

**Comment by yhfreeman** [comment]
Hi @SteveChapmanBCDX thanks for this.

I am happy to help you updating the info but will need to know the first name, last name and email of the new PO (can be DM to me if you'd like considering this is a public repository).

Alternatively, the Registry web portal https://registry.developer.gov.bc.ca/profile/226/overview also has self-serve edit capabilities where the current PO, TC and the initial project requester can update such info.

**Comment by SteveChapmanBCDX** [comment]
Hi @yhfreeman - It looks like the first step is to add Terry to the BCDevOps org in GitHub.

Can you do that for us?  If so, I'll try using the Registry web portal to update our project information.

Thanks for your help!

**Comment by yhfreeman** [comment]
@SteveChapmanBCDX to add the new PO to BCDevOps org in GH, please submit a request [here](https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+ShellyXueHan%2C+patricksimonian&labels=openshift-access&template=openshift_user_access_request.md&title=). 
Let me know if you need anything else. Thanks!

**Comment by SteveChapmanBCDX** [comment]
@yhfreeman - Thanks - I filed new issue in the other repo => https://github.com/BCDevOps/devops-requests/issues/974

**Comment by SteveChapmanBCDX** [comment]
@yhfreeman - I can close this issue for you - thanks for your help!

**Comment by yhfreeman** [comment]
@SteveChapmanBCDX my pleasure!
