### ISSUE TITLE
display graphic for when there are no comments to be displayed

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#3663]

**Comment by Amritpal-Nijjar** [comment]
**Before**
<img width="1430" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXUxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6328180514f1a9ea3a6beb024199dc7648807591/Screenshot%202024-09-05%20at%203.03.53%20PM.png" alt="Screenshot 2024-09-05 at 3.03.53 PM.png" />
**After**
<img width="1430" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXkxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a01fe26bb3f578157d30fba8957a1c9f760068b1/Screenshot%202024-09-05%20at%203.01.12%20PM.png" alt="Screenshot 2024-09-05 at 3.01.12 PM.png" />

**Comment by funtigr** [comment]
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDI1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47b3af8ae63dff6dcb06c1624df60827e03b3375/image.png" alt="image.png" />
