### ISSUE TITLE
eMOU enhancements

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3669]
1. If the product team enters a new account coding, display the message: "No eMOU exists for this account coding. We will initiate the process by sending an email to the EA for their signature. After the eMOU is signed, it will be reviewed and approved, which typically takes up to 2 business days."

2. Display the description and budget when the EA views the approval page.

3. eMOU Status Changes:
   - Current Step: Pending sign-off from the Ministry Expense Authority (EA's name)
   - Next Step: Sign-off by the OCIO Cloud Director
   - --> Sign-Off Complete

4. Enable eMOU download for other products with the same account coding.

5. Update the PDF to include the agreement paragraphs and redesign it to match the current PDF.
   - Check if the `division` is available via the MS Graph API.
   - **added branch/position instead.**

6. Send emails to both the EA and the Cloud Director with the PDF:
   - For new account coding: After approval by the Cloud Director.
   - For existing account coding: After submitting the requests.

7. Update the existing message to: "Our records show that your team already has a signed MoU with OCIO for AWS/Azure use. This new product will be added to the existing MoU. A copy of the signed MoU for this product will be emailed to the Ministry Expense Authority."

**Comment by junminahn** [comment]
[OCIO and (TEAM NAME)- AWS (1).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJ2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--065c4064954e39a18857b402bcf724c5fc2b61f8/OCIO%20and%20%28TEAM%20NAME%29-%20AWS%20%281%29.docx)

**Comment by funtigr** [comment]
If User uses for Azure product the Billing Code, that is already used for existing signed and approved AWS product, the message appears that says two things:
- that MoU is signed for Azure, though it was signed for AWS
- that account coding is currently undergoing an approval process, while it was already approved

<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk8xQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--453abe0bc8081f5517b54a8433fcf0183a7129c3/image.png" alt="image.png" />
