### ISSUE TITLE
Provisioner update for cost management label

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3680]
Issue on the Platform Experience board #5098

**Describe the issue**
In order to use the Cost Management tool in OpenShift, a namespace must have a certain label. Update the provisioner's namespace template to include this label.

**What is the Value/Impact?**
Enable use of the Cost Management tool for all users

**What is the plan? How will this get completed?**

Update roles/tenant/templates/namespace.yaml.j2, adding label: insights_cost_management_optimizations: "true"
Commit the change
Build a new version of the app-provisioner image, incrementing the minor version number by one
Update the private cloud sensors in the provisioner's gitops repo for each environment (dev, test, prod)
Verify the change by reprovisioning a test project that you control
Identify any dependencies
n/a

**Definition of done**

- [x]  Implementation complete

**Comment by funtigr** [comment]
The changes are implemented. Now if the new namespace is made by Provisioner, it has new label:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXExQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30b40fd541d27578b7fc74ad16990bd31c0f1291/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Ian has checked the implementation and approved it.
As it is not about our app I will not add the task to any release.
