### ISSUE TITLE
Swagger/OpenAPI for Project Registry

### ISSUE THREAD

**Issue by juhewitt** [bcgov/platform-services-registry#369]
**Describe the issue**
As a developer, I require the ability to query the Project Registry API for my own application(s).  This interface should be something I'm familiar with, like OpenAPI (Swagger) definitions, and data results should be restricted by the appropriate access I have as a user.

**Additional context**
https://swagger.io/resources/open-api/ 

**Definition of done**
Swagger/OpenAPI definition created and available for those with permission to query.

**Comment by mitovskaol** [comment]
The access to the Registry API will be developed as part of the Registry Re-Write.
