### ISSUE TITLE
Add sort by cluster and by ministry functionality

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3730]

**Comment by funtigr** [comment]
Now we have sorting by Ministry and Cluster for Private Cloud:
<img width="1459" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelFzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27d8a82e54670b48fd630e9a1d710d24cc959b43/image.png" alt="image.png" />

And by Ministry and Cloud Provider for Public Cloud:
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelVzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e67ae73d6eac297821ae80451d0fc8c65042b2b8/image.png" alt="image.png" />

Every sorting option works as expected.
