### ISSUE TITLE
Public Cloud: Can't delete old products because of missing fields in DB

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#3773]
**Description**:
Users can't delete old Public Cloud products in the Registry because they lack some new fields in DB.
`Form validation error`
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejNjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e87ef361a0594c7836985f540bec312dba1350c9/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Still a thing when I try to approve deletion of old products. All live products on Prod are old ones, so this problem can occur if users try to delete them:
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1hoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1789acf7c9528f5222cbc000b604c677cadb65e8/image.png" alt="image.png" />

**Comment by junminahn** [comment]
@funtigr I will try to copy the data from dev to have the same product data as in the screenshot.

**Comment by junminahn** [comment]
661dc42f396b0185137eaff1

**Comment by funtigr** [comment]
Fixed. Worked both for Rejection and Approval.
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODdyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23b0d1b255597d1759978769bfe386549e6def19/image.png" alt="image.png" />
