### ISSUE TITLE
Enhance Rocket.Chat Notifications for Deployment Status

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3794]
### Description
Enhance notifications in the `#app-dev-team` channel on Rocket.Chat to include updates on deployment status for the following events:
- Successful deployment on Prod
- Successful deployment on Test
- Failed deployment on Prod
- Failed deployment on Test
- Failed deployment on Dev

### Technical Details
- Use the existing notification setup for `successful deployments on Prod` as a reference.

### Definition of Done (DOD)
- Rocket.Chat is updated with notifications including necessary information, such as GitHub links, for the specified deployment events.

**Comment by funtigr** [comment]
After adding the webhooks to repository the notifications work as expected:
<img width="1360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUJMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60410fa39e3ed869028f349926d537aa4eaaf8b2/image.png" alt="image.png" />
Avatar image fixed later:
<img width="393" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUZMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec0cb44524b307a25265e1fe09c0485df6ce9e77/image.png" alt="image.png" />
