### ISSUE TITLE
Enhance Search, Filter, and Sort Functionality on Private Cloud Product - Request Page

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3838]
### Description
Enhance the search, filter, and sort functionalities on the private cloud request page.

### Technical Details
- **Search:** Supports searching by name, description, and member name.
- **Filters (multi-select):**
   - request types: default to all
   - decision status: default to pending
   - temporary flag: default to all
   
- **Sort By:** Name, description, status, created date, updated date, decision date, provisioned date
  - Each field supports both ASC and DESC sorting options.
  - Default: Updated date (DESC).

### Definition of Done (DOD)
- The search, filter, and sort functionalities operate as expected.

**Comment by funtigr** [comment]
Filters and Search work as expected inside `Requests` tab in Private Cloud product.
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbaf8a0d93d44afae9c8a5a127532770411889d9/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Above issue is fixed.
