### ISSUE TITLE
new provider on public cloud products

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3849]
The public cloud team wants to add another provider `AWS-LZA` that is similar to `AWS`.
- The new service provider `AWS-LZA` is only available in dev and test environments.
- The behaviour is the same as AWS in terms of eMOU workflows.
- When a NATs message has been sent, it will include the new provider suffix as the message subject.

**Comment by funtigr** [comment]
@junminahn 
When user tries to approve the `AWS-LZA` request they see validation error. After two repetitive attempts, the approval goes through, but `mock-nats-provision` doesn't get the NATS message (according to logs of the pod). 
<img width="1509" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDRYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa3e93ac87f0e9990860904221b43638127865a2/image.png" alt="image.png" />

<img width="1455" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDhYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a52f0cd255c20b89d2a8042e20bbcbb00f1c2895/image.png" alt="image.png" />

**Comment by junminahn** [comment]
@funtigr I believe it is a separate issue; have you had a chance to capture the request payload as well?

**Comment by funtigr** [comment]
I tried it just now and now it get's approved from the first attempt but still not visible in `mock-nats-provisioner` logs.

**Comment by junminahn** [comment]
@funtigr it is more of the mock-provisioner issue that does not recognize the provider; I updated it.

**Comment by funtigr** [comment]
Oh, I see. 
Thanks.
