### ISSUE TITLE
Revisit request page progress status component

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3925]
Since the product and request list UIs are quite similar, and to provide more meaningful insights about requests, we would like to explore displaying the request status progress more effectively on the page.

**Comment by junminahn** [comment]
<img width="746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07c296ac09fefd065f21b31df69b19c68060e69f/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Now we have a new feature for showing the life cycle of the Request.
Clicking on any of the steps leads to Admin Decision tab of the Request.
Licence plate can now be copied from under the name of the product.
