### ISSUE TITLE
"light" project set for the Private Cloud

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#3966]
**Description**
After further research and discussion, we've decided to proceed with the second option: adding an empty quota option to the dropdowns. This approach maintains the current workflow and simplifies development efforts by avoiding the use of namespace checkboxes.

**Technical Details**

- add a new Enum option for the empty Quota.
- add an empty Quota option into the UI.

**Definition of done**

- [ ] The solution is fully tested

References: 
- https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/3965

**Comment by funtigr** [comment]
Now we can change every resource quota to 0 in the Registry:
Changing:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee50241eb238a5af396a31e8c5474a506be01edd/image.png" alt="image.png" />

Applied in mocked environment:
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1pXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a28f0ec11a3cbab2a471ea659736674dcd107009/image.png" alt="image.png" />
