### ISSUE TITLE
When User changes Quota in Private Cloud and switches browser tab, the changes get reset

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#4012]
**Description**:
When User changes Quota in Private Cloud and switches browser tab, the changes get reset

**Steps to reproduce**:
- open existing Private Cloud product
- open additional browser tab if do not have one
- in the Private Cloud product browser tab change any Quota value
- switch to another browser tab 
- switch back to Private Cloud product browser tab

**Expected result**:
The changed value retain

**Actual result**:
The changed value gets reset

**Comment by junminahn** [comment]
@funtigr When reporting an issue, it's important to identify the cause more clearly, especially for bugs reported by team members. During testing, the behavior occurs for all fields, not just for Quota changes.

**Comment by funtigr** [comment]
Oh, I see. Didn't notice that on that time.
This is fixed now.
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzFoQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7d855cacdcd48aaa37e46813681f8c7aee7aef0/image.png" alt="image.png" />
