### ISSUE TITLE
minor UI changes

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4014]
1. for eMOU review email, display `Hi OCIO Cloud Director,` instead of displaying EA's name.
2. display more information of submitters and decision maker's detail on popup of the progress bar on requests page.

**Comment by funtigr** [comment]
1. Implemented:
<img width="804" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2xoQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--930ea2270e2576ad1f66ee1e497040ff9849cb22/image.png" alt="image.png" />
2. Implemented:
<img width="1470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3hoQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--563c2df4c7cf9c0e225950801797197697351b74/image.png" alt="image.png" />
