### ISSUE TITLE
Add side panel for assigned tasks.

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4018]
We want to implement a side panel (drawer) that displays all assigned tasks in a single view. Currently, the available task types are:
- Sign eMOU
- Review eMOU

**Comment by junminahn** [comment]
<img width="132" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTliQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb428f4d5b0892b97a1cb110ca9e487bb5e38164/%7B3ADFAAD9-92A5-4DFE-B6C2-2756BDABCEB1%7D.png" alt="{3ADFAAD9-92A5-4DFE-B6C2-2756BDABCEB1}.png" />
<img width="451" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekJiQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9eeb8a409ee9b21063f3d6458f9d2442ac44ddec/%7B0736D0B7-BAAD-47E9-94DB-B3E1A051D796%7D.png" alt="{0736D0B7-BAAD-47E9-94DB-B3E1A051D796}.png" />

**Comment by funtigr** [comment]
@junminahn 
That's a really cool feature.
I have a concern about a couple of nuances:
1. Should we show the `Tasks` button to the Private Cloud users and admins and to regular Public Cloud users?
Now if user doesn't have any roles assigned, they can see the `Tasks` icon.
Maybe we would make the button visible only to billing-reviewer and cloud
2. There are duplicates for some requests in the Side Panel, that lead to the same request:
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWRnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c7b85de93bed8fd200a67c09442f9aefe922b7b/image.png" alt="image.png" />

**Comment by junminahn** [comment]
@funtigr 
1. the tasks would be expanded and assigned to any users; ex) `review emou` task is assigned to EA who does not have global admins either.
2. are you sure they point to the same requests? please check the request IDs.

**Comment by funtigr** [comment]
Yes, If I hover over them, the link is the same.

**Comment by junminahn** [comment]
@funtigr  it seems like you hit the assign button two times that creates two tasks. I will prevent it at the backend.

**Comment by funtigr** [comment]
And I added a point 3 in the above comment. For my user there are empty tasks, without name or link.
Here is the code of last two of them from Preview tab in Developer Tools:
```
{
        "id": "66d01c642f12e7e52a36f332",
        "type": "SIGN_MOU",
        "status": "ASSIGNED",
        "createdAt": "2024-08-29T06:59:48.954Z",
        "completedAt": null,
        "completedBy": null,
        "data": {
            "requestId": "66d01c642f12e7e52a36f331"
        },
        "closedMetadata": null,
        "link": "",
        "description": ""
    },
    {
        "id": "66d01b4d2f12e7e52a36f323",
        "type": "SIGN_MOU",
        "status": "ASSIGNED",
        "createdAt": "2024-08-29T06:55:09.810Z",
        "completedAt": null,
        "completedBy": null,
        "data": {
            "requestId": "66d01b4d2f12e7e52a36f322"
        },
        "closedMetadata": null,
        "link": "",
        "description": ""
    }
```

**Comment by funtigr** [comment]
And here is the data for the request from point 2 in above comment, the json for the duplicated tasks:
```
{
        "id": "671145f5a965360da681e6a6",
        "type": "REVIEW_MOU",
        "status": "ASSIGNED",
        "createdAt": "2024-10-17T17:14:29.755Z",
        "completedAt": null,
        "completedBy": null,
        "data": {
            "licencePlate": "ca3d73"
        },
        "closedMetadata": null,
        "link": "/public-cloud/requests/6660d06485f04819233d5a58/request",
        "description": "Artem Test Jun 5.5"
    },
    {
        "id": "671145cda965360da681e6a5",
        "type": "REVIEW_MOU",
        "status": "ASSIGNED",
        "createdAt": "2024-10-17T17:13:49.454Z",
        "completedAt": null,
        "completedBy": null,
        "data": {
            "licencePlate": "ca3d73"
        },
        "closedMetadata": null,
        "link": "/public-cloud/requests/6660d06485f04819233d5a58/request",
        "description": "Artem Test Jun 5.5"
    },
```

**Comment by funtigr** [comment]
4. If the user doesn't have any roles in the Registry and is assigned as Expense Authority, the `Task` icon shows 0 tasks and the Network tab in Developer tools, shows error 401, Unathorized:
<img width="1478" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2hnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7aa9468bea65f377e3e5b9076ad4bb543363cccc/image.png" alt="image.png" />

**Comment by junminahn** [comment]
@funtigr that should be a bug then, let me check it out as well.

**Comment by funtigr** [comment]
If a User has no roles assigned and is an Expense Authority and has already signed the eMOU, they still see one task pending, though it is a task for billing-reviewer and not for Expense Authority:
The Icon shows one task waiting:
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGhoQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65077dbfc291d2c0997073af0029a7679f680427/image.png" alt="image.png" />

After clicking the link in the sidebar, the next action is for the `billing-reviewer`:
<img width="1473" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHhoQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a94d3e66e055544ebc491cffd2248c55f04a30f5/image.png" alt="image.png" />

All above things are fixed (except #1, showing icon to regular users, which in my opinion may be confusing for them but not critical).

**Comment by junminahn** [comment]
@funtigr that is because from the bad data, I deleted the duplicates, please try again.

**Comment by funtigr** [comment]
Yes, works as expected after clearing the data.
