### ISSUE TITLE
Refresh access token from Keycloak

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4026]
We would like to explore the option of regularly refreshing the Keycloak access token or providing a button for manual refresh. Currently, logging out and back in to obtain a new access token after role changes can be inconvenient.

DoD:
Research + implementation

**Comment by Kolezhanchik** [comment]
[TEST] 
in 30min  being inactive auto logout
change role - 3min max - role reflected 
user inactive for 30 min user logged out

**Comment by funtigr** [comment]
While testing the `auto logout`, I wasn't required to login after closing browser for more than 30 minutes.
I used Firefox and platform.services.test.account@gov.bc.ca.

**Comment by funtigr** [comment]
Roles change works good.
But the auto logout works for my account in Chrome and doesn't work for platform.services.test.account@gov.bc.ca. I suppose it is used by someone other on other computer which renews the session every time.

**Comment by junminahn** [comment]
@funtigr please test again.

**Comment by funtigr** [comment]
It still doesn't work for me. 
Roles were changing almost instantly yesterday when we tried that together on the call, but now they don't change for me again. 
And when I visit dev using platform.services.test.account@gov.bc.ca, and then close the browser completely and come back in about an hour, it still doesn't log me out.

**Comment by junminahn** [comment]
@funtigr it works; just I forgot to tell you that after the changes are deployed, the users need to logout and login to have the initial `refresh timestamp` configured properly in DB; after that they no longer needs to do that.

**Comment by funtigr** [comment]
Yes, both conditions work as expected now 👍
