### ISSUE TITLE
Make quota request instructions accessible

### ISSUE THREAD

**Issue by yhfreeman** [bcgov/platform-services-registry#403]
**Describe the issue**
As a user, I'd like to see useful information @ quota request instructions be made accessible regardless whether users can further edit a given project.

**Additional context**
Currently on the web ui, the instructions to contact platform admins disappears after an edit request is submitted. There's a case where a user forgot to capture such info, went back but couldn't find them.

Reference: https://chat.developer.gov.bc.ca/channel/devops-registry?msg=7eDSa5SGxS4JFRwox

**Definition of done**
When the above is done.

**Comment by yhfreeman** [comment]
@rloisell ^ to reflect what you suggested

**Comment by yhfreeman** [comment]
Relates to https://github.com/bcgov/platform-services-registry/issues/355

**Comment by w8896699** [comment]
https://github.com/bcgov/platform-services-registry/pull/460/files

**Comment by w8896699** [comment]
[07-23 10:27 a.m.] Mitovska, Olena CITZ:EX
     Wording changes: Upgrade/Downgrade Quota for the modal title and "Request Quota Change" for the button
