### ISSUE TITLE
Research about Displaying subnet info for project namespaces in Registry UI (Emerald Cluster Only)

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#4059]
Apps hosted in the Emerald Cluster had /24 subnet information generated for them at the time of provisioning namespaces as described in this document (IDIR protected). This information resides in Openshift as part of the namespace meta information. Product teams would like to see this information displayed on the product detail page in the Registry UI.

At this moment the information is only passed from the Registry app to the provisioner to Openshift. This feature requires building the second communication line where information can be passed from Openshift to the provisioner to the Registry app.

Related comments: 

DoD:

 /24 subnet information is displayed on the product detail page in the Registry for Emerald namespaces.

**Comment by golebu2020** [comment]
During my one-on-one with Cailey, I asked about enabling this feature, and I was referred to the Emerald Teams Guide at https://digital.gov.bc.ca/cloud/services/private/internal-resources/emerald/, specifically the section titled **While the issue description noted that the Emerald Cluster generates subnets with a /24 CIDR, the documentation specifies a /26 CIDR for internal pod networks. According to the guide, we can fetch the /26 subnet information for each namespace using the following oc command: 
```
oc get namespace <namespace> -o jsonpath='{.metadata.annotations.ncp\/subnet-0}{"\n"}'
```
For example, a typical response might look like: `10.90.68.0/26`. `<namespace>` would have to be replaced with then actual `namespace` in question. 

It's important to note, however, that the account used to run this command must be a member of the specified namespace or project. Alternatively, this information is accessible through the web console at the following URL: 
```
https://console.apps.emerald.devops.gov.bc.ca/k8s/cluster/projects/<namespace>/yaml
```
