### ISSUE TITLE
Add task type "Review Request" for both Clouds

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4093]
**Description**  
- Currently, privileges for reviewing requests, are granted based on a user's roles and the status of a product or request. To better manage these privileges, we want to introduce a new `Task` type `Review Request` within the system. When a new request is created, a task will be generated and used to manage review permissions, ensuring consistent tracking.

**Technical Details**  
- Add a new `Task` type to the Prisma schema. (possibly we might add two separate ones for private and public)
- Automatically create a task when a request is initiated and close the task when the request is completed.
- Display the task in the task side panel.
- Assign `read` privileges for products/requests based on associated tasks.
- Grant `review request` document-level permissions based on assigned tasks.

**Definition of Done (DOD)**  
- A new task is generated when a request is created, and the review workflow works as expected, including email notifications.

**Comment by funtigr** [comment]
1. Edit Request that was auto-approved has status `Partially provisioned`, though logs show that it was successfully approved:
<img width="1485" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVHQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32d44748a47071fc39459b8a3874de8fba49f3ba/image.png" alt="image.png" />

<img width="1432" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlHQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56b78283423ee3240fa53289dc6c48ac22e47777/image.png" alt="image.png" />

2. After submitting a `Create` request, `private-reviewers` get an empty email about `Edit` request waiting for review:
<img width="1361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNHQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf240e4641d8d7ab42f1e967a76eabbb0b2f13df/image.png" alt="image.png" />

3. After submitting a `Create` request, `private-reviewers` also get an email about `Delete` request waiting for review:
<img width="1364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlKQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22529ce9ce56e7affe07d8ef989a8d43c2684bbd/image.png" alt="image.png" />

4. After clicking the Request link, the browser shows `application error` and doesn't display the contents of the page:
<img width="1478" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVKQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d96edeb0922eb7ec93a15e3490bf5365b89fb6c1/image.png" alt="image.png" />

5. After submitting `Edit` request, increasing quota, Reviewers receive the email about `Delete` request waiting for review:
<img width="1427" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNKQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--843bea249e9d6fa3182ead8431014e80920e668a/image.png" alt="image.png" />

6.  After submitting `Edit` request, increasing quota, Users receive email about `Automatic approve`, which is not true in this case:
<img width="1361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThKQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c7e6902b5de3dac65a92cd49fc8354dafac9c69/image.png" alt="image.png" />

7. After Rejecting `Delete` request, User doesn't receive any email

**Comment by funtigr** [comment]
Now everything works good, all the users, having `private-reviewer` role receive tasks when there is a new request (of any type) waiting for approval. The link leads to the request. The emails are reflecting right stages of the flow and are displayed in full.
