### ISSUE TITLE
Use simple list of mock users for sandbox

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4094]
**Description**  
We are transitioning from using `m364-proxy` server to `m365-mock`. As part of this change, we will deprecate the proxy server. During this process, the user list in `/localdev/m365proxy/mocks.json` should be refactored into a flat structure and relocated to a more generic directory for better organization.  

**Technical Details**  
- Refactor the user list into a flat structure and move it to a common/generic directory.  
- Update any related application and sandbox server configurations that depend on this file.  

**Definition of Done (DOD)**  
- The application's tests and sandbox environment function as expected without any issues or regressions.

**Comment by funtigr** [comment]
The new list works as expected on localdev environment
