### ISSUE TITLE
When Private-Reviewer changes quota in the Request, they need to enter Justification fields

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#4110]
**Description**:
When Private-Reviewer changes quota in the Request, they need to enter Justification fields

When Private-Reviewer changes quota to higher in the Admin Decision page of the Request that they review, Justification fields become empty and they have to fill out Justification fields in order to Approve the Request

Expected result:
If Private-Reviewer changes quota to higher in the Admin Decision page of the Request that they review:
- they do not have to fill out Justification fields
- the Justification fields keep the values that were input by the user

**Comment by funtigr** [comment]
Now if `private-reviewer` changes quota during the review, the Justification fields do not appear for filling out.
But they also are not visible. I believe they need to be visible for the `reviewer` for making an informed decision:
<img width="1464" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNCtLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0ec46c8b283550a0915650edfb9d8729b3f84d5/image.png" alt="image.png" />

So we need to make them visible but not editable by the `reviewer`.

**Comment by junminahn** [comment]
@funtigr there is a dedicated section to check the information, do you remember?

**Comment by funtigr** [comment]
Oh, right. 
The `reviewer` can see it in the Summary tab in Justification section.
