### ISSUE TITLE
Testing of the Automated resource quota change

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#4111]
In order to ensure that the automated qouta approval logic works as expected, this needs to be tested by Billy before the App Dev team can push this into production. For now, this change is in the testing env only.

DoD:
- this feature is tested and if it works as expected, this feature is pushed into prod

**Comment by funtigr** [comment]
We had a testing session with Billy and Zhanna.
The requirements changed. We need to measure the cpu.utilization for an hour before request was submitted by user.
Also we need to use different metrics for cpu.utilization - it should be the sum of the requests of the active pods.
Here are helping notes from Billy for new implementation:
https://invented-trust-0c9.notion.site/Note-for-quota-auto-approve-135a3ae24b3180d3bf05fbfd99f55599

**Comment by Kolezhanchik** [comment]
wording for summary tables should be changed Total CPU Limit => CPU Usage Limit
Total CPU Usage => CPU Usage same for memory (clarify with Billy)

**Comment by junminahn** [comment]
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5082
