### ISSUE TITLE
Enable users to adjust their quotas by + or - 0.5 - Gather Requirements & Identify Dependencies

### ISSUE THREAD

**Issue by lukegonis** [bcgov/platform-services-registry#4113]
**Describe the issue**
Instead of our current quota t shirt sizes/increments, users should be able to adjust their quotas by 0.5 core increments with "-/+" controls. The value can be anything between "0" and "MAX"

**Rational/Why**
More granularity for users to tune their project sets

**Additional Context**

- Link to the code repositories
- List of technologies that may be expected to be known in order to work on the task
- Clear description of where the code change is going, e.g "add the text input to the create request form in components/request.js"
- Clearly identify which products are being updated ("Platform Services Registry")

**Dependencies**

- Internal, external, who to talk to if more information is needed

**Tests**

**Definition of done/Acceptance Criteria**
- confirm with Ian if it's feasible with Provisioner 
- estimate the effort to do that
- explore other options that can be used for this scenario
- create the implementation ticket

**Comment by golebu2020** [comment]
To move forward with integrating this feature into our product, I organized a meeting on November 15, 2024, with Ian, Cailey, Billy, and the app dev team. Our focus was on how to give users more precise control over quota adjustments, making it easier for them to scale resources up or down as needed.

Ian, supported by Cailey, confirmed that the provisioner could feasibly implement this feature. Testing will be conducted in a dedicated environment to ensure no impact on our live or development setups. Additionally, we decided to replace the current form-select method for setting resource quotas with an input field, allowing users to specify their quotas within established boundaries. As the app dev team develops this feature, they’ll stay closely aligned with Ian to ensure it’s executed as envisioned. This feature is expected to require only moderate development effort.

Another key decision was to define how users will interact with these quotas on the frontend:

- CPU: Users can adjust quotas from 0 to 64, with increments of 0.5.
- Memory: Memory quotas will be configurable from 0 to 128GB, adjustable in 1GB increments.
- Storage: Storage will be adjustable up to 512GB, also in 1GB increments.

In this update, we’re eliminating fixed CPU and memory limits. Instead, resources will be dynamically allocated to pods based on availability, offering users a more flexible, efficient experience. This approach aligns resource distribution with practical demand, ensuring smoother scalability for users.
