### ISSUE TITLE
[Public Cloud] Additional product members

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4123]
**Description**  
- Expand product member assignments to enable more users with roles to have added
- ref: https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/4117

**Technical Details**  
- Add a new `members` field in the public cloud project schema, which is a list of objects including:
   - `userId`: unique identifier for each user
   - `roles`: assigned member roles for the user
- Introduce a new `MemberRole` Enum with values:
   - `BillingViewer`
   - `Editor`
   - `Viewer`
   - `Subscriber`
- Develop a dynamic UI to manage members (limit 0–10 members) with columns for:
   - User lookup (1st column)
   - Role selection (2nd column)
- Give privileges to the members accordingly

**Notes**  
- After completing the public cloud implementation, we will apply this feature to the private cloud as well.
- Confirm with the public cloud team whether additional members need to be sent to their provisioner. If provisioning is unnecessary, allow immediate updates to the member list and consider placing this functionality on a separate tab if it’s isolated from other provisioning needs.

**Definition of Done (DOD)**  
- Product Owners or Team Leads can successfully manage additional members.

**Comment by junminahn** [comment]
<img width="1687" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZsQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13dae3c191951b0c87544208ae3ad1f6f9279ba6/%7BB6B1091B-7846-4BD3-8B39-76C3E5075241%7D.png" alt="{B6B1091B-7846-4BD3-8B39-76C3E5075241}.png" />

**Comment by funtigr** [comment]
If a user is assinged an `Editor` role for the product, they can't submit the changes to it.
The error has status code 500:
```json
 "error": "PrismaClientValidationError: Invalid `prisma.publicCloudRequest.create() \n Unknown argument `id`. `"
```

**Comment by funtigr** [comment]
Now fixed and works as expected.
