### ISSUE TITLE
user search picker modal

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4156]
**Description**  
- Develop a reusable user search picker component that can be integrated across different areas of the application.

**Technical Details**  
- Implement a dedicated endpoint to enable M365 user search functionality. When a search is performed, create database entries for the users, including profile images retrieved from the M365 image endpoints. This will allow the frontend to reference user IDs directly.

**Comment by funtigr** [comment]
User picker works as expected.
Now the search doesn't show the accounts without UPN or IDIR.
<img width="1473" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejYxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--074887fe16f5dc3763cd4948f62dfda116305e24/image.png" alt="image.png" />
