### ISSUE TITLE
Automated resource quota change

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#4176]
After a testing session the requirements changed. 

1. We need to measure the average cpu.utilization for an hour before request was submitted by user. avg_over_time
2. Also we need to use different metrics for cpu.utilization - it should be the sum of the requests of the active pods.
   Here are helping notes from Billy for new implementation:
 https://invented-trust-0c9.notion.site/Note-for-quota-auto-approve-135a3ae24b3180d3bf05fbfd99f55599

 https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5082

PromQL doc: https://prometheus.io/docs/prometheus/latest/querying/basics/

 useful cheat-sheet: https://promlabs.com/promql-cheat-sheet/

https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time
the average for the last 1hour

3. wording for summary tables should be changed Total CPU Limit => CPU Usage Limit
Total CPU Usage => CPU Usage same for memory (clarify with Billy)
4. Billy also asked for wording description about this function, like (clarify with Alex)

If your request meets the following cases, it will be auto-approved:
...
...
...

UPD: after deleting the limit for namespaces and objects, the requirements have changed:
<img width="966" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNklkQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--211ef652fc1b7a58da8d934bcce18b7300625fe6/image.png" alt="image.png" />

Also we will need to change the text above the quota correspondingly.

**Comment by Kolezhanchik** [comment]
Alexandra Lloyd sent you a message:

If your request for more CPU and Memory meets *all* of the following requirements, it will be automatically approved:
1 . Your namespace’s current usage exceeds 85% of its total limit.

2 . Your namespace’s resource utilization rate is at least 35%.

3 . You are increasing your quota allotment to the next tier only.

If your request for more Storage meets *all* of the following requirements, it will be automatically approved:
1 . Your namespace’s current usage exceeds 80% of its PVC limit.

2 . You are increasing your quota allotment to the next tier only.

**Comment by Kolezhanchik** [comment]
comment from Billy "lets take CPU max_over_time for 2 weeks if that is possible"

**Comment by funtigr** [comment]
We will need a mechanism to run over the quota limits for a month. I suppose we set the lowest possible quota and just constantly be over it for a month, running Billy's script in a loop.

**Comment by funtigr** [comment]
The CPU Usage is now not displayed, though Memory Usage does:
<img width="1494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS8yQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1400ddfd8f5daa0f1003b43078495fabb77eb795/image.png" alt="image.png" />

And if I `console.log()` fetched CPU manually it shows up. So the problem occurs somewhere on the way to frontend:
<img width="1165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0QyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bdbb130f34c4ecb82c29a5f27af118ae98059db9/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
changed formatCPU, since now it is getting cores <img width="1217" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmI4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ecf962adbdece18c236ab3045c008c908c64557/image.png" alt="image.png" />

**Comment by funtigr** [comment]
If user tries to increase quota under load, the backend prisma error is shown:
```json
PrismaClientValidationError: Invalid `prisma.privateCloudRequest.create()` invocation: 

Argument `connect` of type PrivateCloudRequestedProjectWhereUniqueInput needs at least one of `id` arguments. Available options are marked with ?.
```
The connect parameter in the body of the error looks like this:
<img width="1228" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdHQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--036f177ca85b3cb43a612502298798cc273b339b/image.png" alt="image.png" />

**Comment by funtigr** [comment]
There are two newly found problems:
1. On span of 2 last weeks the average utilization is more than the limit, which is impossible in reality (I suppose the problem is in prometheus query or count logic):
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRMQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbeff3b3704937e72084b34361987f9b34e741b3/image.png" alt="image.png" />

2. The request one step up in CPU doesn't get auto-approved with enough utilization (in this case utilization is far more than 50%).

**Comment by funtigr** [comment]
UPD: after deleting the limit for namespaces and objects, the requirements have changed:
<img width="966" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNklkQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--211ef652fc1b7a58da8d934bcce18b7300625fe6/image.png" alt="image.png" />

Also we will need to change the text above the quota correspondingly.

**Comment by Kolezhanchik** [comment]
what about memory?

**Comment by funtigr** [comment]
1. Billy said that if we have usage more than 100% of request, the burst-quota mechanism would be auto-triggered. So we implement auto-approval for the case when the Usage is over 35% of Requested quota for the namespace (e.g. if we have 4 CPU cores, the combined average usage in last 2 weeks is >1.4 CPU cores, then we auto-approve).
2. The 35% threshold is for CPU only. For Memory and Storage he asked to look into previous tickets, where he provided it (he says they are based on Requests (not limits) already).
3. He approved such UI changes:
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1kQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e49458797012f052eed6eab1a92eaa763657100/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
still not clear, any changes for memory?
