### ISSUE TITLE
Resource numeric inputs

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4188]
**Description**  
To enable more precise resource quota configuration for product teams, replace dropdown options with input boxes for resource request values.

**Technical Details**  
- Update the schema to accept numerical request values.
- Replace existing dropdowns with input fields for entering request values (limit values won't be collected)
- Set increment steps: `0.5` for CPU, `1` for Memory and Storage.
- Update NATS message generation to handle numerical values.
- Refactor code to use numerical values instead of string options.

**Definition of Done (DOD)**  
- Project teams can input and validate resource request values in numerical format.

**Reference**  
- https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/4113

**Comment by Iryna-Kaplun** [comment]
Ian and Artem will be testing this work. Ian will be testing the Provisioner side. Junmin asked Ian to test on Dec 4th.
