### ISSUE TITLE
Migrate Project Report and Time Tracker from to the Silver cluster

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#420]
## Description

Migration the Project and Time Tracker project from the Pathfinder cluster to the Silver cluster for Zach.

## Done When

- [x] The project is migrated and running on Silver;
- [x] The old project on Pathfinder is decommissioned and and the namespaces are removed.

**Comment by jleach** [comment]
WIP. Taking a bit longer than I expected because the app is a bit tough to debug. Deployment manifests and deployment is done. Just not sure how to test the app to make sure all the components are talking. I've updated Zach.

**Comment by jleach** [comment]
Confirmed backups and restore working as expected:

```
Successfully verified backup: /backups/daily/2021-06-23/timemachine-patroni-master-timemachine_2021-06-23_10-57-19.sql.gz
The restored database contained 25 tables, and is 18 MB in size.
```

**Comment by jleach** [comment]
I think we're done with the migration efforts. May need to do some CICD work in the future if they make changes but for now the migration looks good. Will close ones the decommissioning request is in.

**Comment by mitovskaol** [comment]
The decomm request is #1199
