### ISSUE TITLE
Auto-approve initial temporary product requests

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4284]
**Description:**  
To enable the onboarding process for project teams creating temporary project sets easy, we want to automatically approve products upon creation.

**Technical Details:**  
- Update the backend's `create` endpoint to check the flag for temporary products and bypass the approval process when applicable.

**Definition of Done:**  
- Temporary products are auto-approved upon submission, without an approval from an admin.

**Comment by funtigr** [comment]
Now the `Temp` products are approved automatically.
It works fine for new products, but for existing products, when the User checks the checkbox, the page crashes.
Though after refresh it works again and the product is already temporary.
Not sure if we need to fix it now as making existing products temporary is rarely used.
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkxWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b53f110d9d33ed2d34de0cd019081b290adb3b52/image.png" alt="image.png" />
