### ISSUE TITLE
Ability to update user roles via UI

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4304]
**Description**  
- Implement a feature that allows admins to update users' global roles directly through the UI, eliminating the need to log into Keycloak.  

**Technical Details**  
- Add a RESTful `put` endpoint for updating roles in addition to the existing `list` endpoint.  
- The new endpoint should accept only the `roles` attribute to update roles in Keycloak.  

**Definition of Done (DOD)**  
- Global admins can successfully update user roles via the UI.

**Comment by funtigr** [comment]
@junminahn 
After Admin makes changes to roles for a user and clicks "Save" the "Save" and "Cancel" button remain in place, but the changes are saved.
If Admin clicks "Cancel", then the changes are reverted in the UI but are not reverted in KeyCloak.
I propose to make the buttons disappear after Admin clicks "Save" button. And they would appear only if Admin makes another change to the roles.
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW55Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fa94074826f72ee017df7685894cc79683538e6/image.png" alt="image.png" />

**Comment by junminahn** [comment]
@funtigr I guess you tested before the deployment finished; can you try again?

**Comment by funtigr** [comment]
Yes, looks like. Now it works well.
