### ISSUE TITLE
Resource numeric inputs - Documentation

### ISSUE THREAD

**Issue by lukegonis** [bcgov/platform-services-registry#4310]
**Description**  
Update all documentation in developer.gov.bc.ca that related to this change/feature: To enable more precise resource quota configuration for product teams, replace dropdown options with input boxes for resource request values.

Sequence of events:
- documentation
- deployment
- email to community
- rocketchat communcation
- community meetup demo

**Definition of Done (DOD)**  
- update documentation

**Reference**  
- https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/4113

**Comment by junminahn** [comment]
@funtigr 
https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/automation-and-resiliency/request-quota-adjustment-for-openshift-project-set/
