### ISSUE TITLE
export feature on users page

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4363]

**Comment by funtigr** [comment]
Exporting works as expected. 
The content of the exported .csv file corresponds to the one reflected in Frontend:
<img width="799" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDc4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cafb4b69e8b7c6c3c8853cb054b3022a86298fb1/image.png" alt="image.png" />
