### ISSUE TITLE
"user-reader" role to the user pages

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4368]
Add a role to have read-only privileges on the user pages

**Comment by funtigr** [comment]
The role works as expected.
`User-reader` can see all the roles and export them, but can't edit.
<img width="1506" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUg4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d50a2bd318fadfd32691b46229119b5ef54dfee3/image.png" alt="image.png" />
