### ISSUE TITLE
CPU Usage UI Incorrect Unit Display 

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#4387]

**Comment by funtigr** [comment]
This one is fixed:
<img width="1481" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNHQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fa67629288273300312d49c375293f9b2e89cad/image.png" alt="image.png" />
