### ISSUE TITLE
Add "Get" /product API endpoint

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4397]
**Description**  
To support the use case of the AG Ministry and other end users utilizing the registry app's API endpoints, we want to add a new endpoint to retrieve information for a single product.

**Technical Details**  
- In addition to the existing `LIST` endpoint, introduce a `GET /api/v1/private-cloud/products/<id or licenceplate>` endpoint.
- Include the `user email` attribute in both the `LIST` and `GET` endpoints.

**Definition of Done (DOD)**  
- A machine can retrieve product information by ID or license plate using a service account token.

**Comment by funtigr** [comment]
The new API works as expected. 
The emails of the users are included in the response of the body.
<img width="1193" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekEwQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48ea065e4607e84789b62cd065a004f9a062e7d4/image.png" alt="image.png" />

The list endpoint now displays the emails of the contacts too:
<img width="1199" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekUwQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a7cab492afe89cada36abe516e389174b23ad8c/image.png" alt="image.png" />
