### ISSUE TITLE
Public cloud delete request approval

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#4527]

**Comment by funtigr** [comment]
This one is fixed:
<img width="1466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzh6Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e2a43f4a38e5fd2368349751da1fc61b86b2392/image.png" alt="image.png" />
