### ISSUE TITLE
Provide feedback as a request progresses through its workflow

### ISSUE THREAD

**Issue by lukegonis** [bcgov/platform-services-registry#52]
As a provisioning request progresses through its workflow the requester (or team) should have visibility into what step the request is at. If the step is not fully automated, then the requester should be able to determine what human is currently blocking the request.

**Comment by mitovskaol** [comment]
The submitter is able to monitor the progress of their request from the 2 emails they received during the submission process. The first email indicates that the request has been accepted and assigned to the Platform Services team for a manual review and approval. The second email indicates that the approval has been received and the request has been processed and the namespaces have been provisioned on the Platform. This part is done.

However, as a PO I want to be able to log into the Project Registry and see my request in the Dashboard with a pending status if it is still waiting for the approval or hasnt been processed yet. This part is not done yet.

**Comment by jleach** [comment]
Will need to coordinate with @j-pye on this one because we'll need this automata to call back to the registry at specific milestones.
