### ISSUE TITLE
Project Naming bug in Gold/GoldDR.

### ISSUE THREAD

**Issue by w8896699** [bcgov/platform-services-registry#535]
**Describe the issue**
Steven found a bug in F5 SIS firewall that blocks non-http egress traffic  from the namespaces that have a license plate that  starts with a number, it was first discovered by the DataBC team in their project in Gold.

**Additional context**
F5 team is working on finding a permanent solution for this problem but meanwhile we need to create a new projects set for DataBC team with a different license plate ( that does not start with a digit).

**Definition of done**
Registry no longer generates any project name that starts with a digit.
A new project set is created for DataBC in Gold.

**Comment by Amritpal-Nijjar** [comment]
https://github.com/F5Networks/k8s-bigip-ctlr/issues/2012
