### ISSUE TITLE
Separate quotas per namespace in a project sett

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#551]
In order to achieve further flexibility with assigning only necessary resource for each namespace individually, we need to enable teams to request separately CPU or RAM or Storage for each individual namespace *-dev*, *-test*, *-prod* and *-tools* **separately**. 

For example, a team may need to request more CPU for their *-dev* namespace to run PR-based deployments and more Storage for their *-prod* namespace to accomodate a large database.

DoD:
- On a project edit page , a PO/TL can click the "Edit" icon next to each of the 4 namespaces and on a separate page to choose how much of each resource in each of the 3 resource categories - CPU, RAM and Storage - they need for **the selected namespace**.

**Comment by w8896699** [comment]
Hi @mitovskaol , I have come up with two mockups, which do you prefer? 
![Screen Shot 2021-11-15 at 12.08.29 PM.png](https://images.zenhubusercontent.com/5d6ffb905ec50a5aa4201bcb/92ffce6a-20bf-469d-a05a-91607608de91)![Screen Shot 2021-11-15 at 11.56.52 AM.png](https://images.zenhubusercontent.com/5d6ffb905ec50a5aa4201bcb/5f1ed7e4-a04a-4f00-ae26-c8c1f8a1f65d).

Do you have any suggestions on your preferred one?

**Comment by mitovskaol** [comment]
<img width="1792" alt="Registry_Quota_Management" src="https://user-images.githubusercontent.com/28309901/141867680-23602570-c899-461f-82fd-aa9cbf6cdc9f.png">

@w8896699 What do you think about this layout?
