### ISSUE TITLE
Add custom resource quota size option in Project Registry for Admins only

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#554]
As we have at least one existing project (TheOrgBook) that does not fit into the [new quota sizes](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/552), we need to have a process in place to request custom quota sizes outside of the standard ones. However, we only want to have this option available to the Registry Admins only. 

DoD:
- [ ] add an text input field to the quota edit page for entering custom amounts of resources for CPU, RAM and Storage 
- [ ] make this field visible to the Registry Admin users only

**Comment by IanKWatts** [comment]
Reopening - was closed by bot
