### ISSUE TITLE
Create read-only admin account in Registry for 7-7000 agents

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#555]
To effectively assist teams calling 7-7000 for application support after hours, it would be helpful for 7-7000 agents to have read-only access to the Project Registry so that they can look up who the Technical Lead for the app in trouble as sometimes the caller may not know this information.

DoD:
- [x] An account created in the Registry that has read-only access to all projects 
- [ ] The account details provided to @sbathgate to include in the 7-7000 troubleshooting script

**Comment by okanji** [comment]
We can now assign 7-7000 users the **read-only-administrator** role in keycloak to prohibit them from making any admin write changes while still having read access. This is now in production. @mitovskaol will take care of assigning the 7-7000 agents to this new role.
