### ISSUE TITLE
Granular Access Control

### ISSUE THREAD

**Issue by sbathgate** [bcgov/platform-services-registry#577]
**Describe the issue**
Improvements to the Registry Authorization mechanics are necessary to enable more granular access control capabilities. This could include roles such as: 
- View all projects by Ministry
- View all projects
- Edit all projects
- Approve Projects
- View assigned projects
etc.

**Additional context**
An example that came up regarding this included 7-7000 having access to the Registry to gather contact details related to specific projects etc. Additionally, there are members of the community that oversee ministry wide project coverage which would be helpful to have a ReadOnly capability of all projects in their particular ministry.

**Definition of done**
When more granular access control is implemented in the Project Registry.

**Comment by mitovskaol** [comment]
More granular access control will be implemented as part of the Registry Re-Write. Closing this ticket as duplicate.
