### ISSUE TITLE
Registry project deletion self-check

### ISSUE THREAD

**Issue by w8896699** [bcgov/platform-services-registry#589]
**Describe the issue**
When the user deletes a project and its namespaces, the registry front-end will send a request to the provisioner to check if the pod down and four namespaces are there. After check finish, it will allow the user to continue the deletion process, otherwise. It will terminate the deletion process and let the user do a self-check again, 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Complete the above description.

**Comment by lukegonis** [comment]
@w8896699 can you please estimate this?
