### ISSUE TITLE
Collect information about the tech stack a project uses

### ISSUE THREAD

**Issue by lukegonis** [bcgov/platform-services-registry#62]
# Use Case

As a Ministry information specialist, I would like to know what tech stack a project uses so that I can make sure it is in-line with our available skill set (what employees can do).

As a platform owner, it would be useful to report on what technology is being used across all ministries so that we can make strategic decisions on hireling, technology, training and also let others know what is popular among peer projects.

# Description

It would be good to let let a team document their tech stack so that it can be shared. It's somewhat in line with an ask from NR asked for: They tend to get "tech stack sprawl" (I just made that up) where, as a result of teams having so much freedom, they use a very disparate tech stack within a ministry making it hard to hire people with such an expansive skill set. By collecting what a project uses (early) they can triage teams who want to go rogue and select some obscure tech stack because it's hot/cool or its what they know (PHP).

We're essentially creating a localized [Stack Share](https://stackshare.io/)

# Done When

We can collect metadata on the tech stack used by a product team.

**Comment by mitovskaol** [comment]
@jleach can you please add more details to this ticket. thanks!
