### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by lukegonis** [bcgov/platform-services-registry#620]
**Describe the issue**
Currently, whenever there is a react error, the registry directly shows a blank page with some error code.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Whenever there's react error, we should redirect the user to an error page, which allows them to go back to other health pages (dashboard)

**Comment by ShovelHand** [comment]
![image.png](https://images.zenhubusercontent.com/61685dc792ace60aa0bf03dd/f1a4e1db-5c63-453f-b1a9-395b7cb0a6c4)
