### ISSUE TITLE
Suggestion - provide a link to application help documentation

### ISSUE THREAD

**Issue by gjlawran** [bcgov/platform-services-registry#645]
**Describe the issue**
I could not find any links or references to any (Help or About) documentation that describes this applications purpose, functions, scope.  Without this kind of information I find it harder to use the application and provide meaningful feedback.  I see there are a few bullets as the top of the readme that might be the start of this - but perhaps there are other docs somewhere else (e.g. developer.gov.bc.ca) that could be linked into the interface?

**Additional context**
When I am using the application and want to know more about it - for example is there a workflow for changes to project content/metadata ? or  how does the registry fit in a project lifecycle  - I would naturally look for documentation about the Project Registry - that describe what is it for, why it exists, how do something. Having information like this about the application help me to better navigate it and provide meaningful feedback about the application. 

**Definition of done**
When there is a hyperlink from the dashboard page labeled help or about or linked to the title that takes me to some documentation.

**Comment by lukegonis** [comment]
the information about the project registry app will be available on the new Wordpress website for the private cloud platform under our 'Our Products' Section. The Launch of the Private Cloud website is planned for early May.

**Comment by gjlawran** [comment]
@lukegonis  - not sure why this would be closed - couldn't it be left on hold pending launch of WP site and then linked at that time ?
