### ISSUE TITLE
Show license plate in dashboard table

### ISSUE THREAD

**Issue by w8896699** [bcgov/platform-services-registry#652]
**Describe the issue**
Project License plate column is not currently included in the project list on the Dashboard page in the Project Registry. The user can manually add the license plate (aka namespace) column to the table using the button in the top right corner above the table. However, if the user goes to a project edit page and comes back to the Dashboard, the license plate column is removed from the table again.  

**Definition of done**
License plate column is permanently added to the project list on the Dashboard page as the last column.

**Comment by ShovelHand** [comment]
Submitted for code review.
