### ISSUE TITLE
Keep the search result 

### ISSUE THREAD

**Issue by w8896699** [bcgov/platform-services-registry#653]
**Describe the issue**
Keep the search result when the User redirect back from other pages to the dashboard

**Additional context**
URL search query or Redux might be handy in this case. 
We can also consider some changes on the time interval of pulling dashboard projects from api/db.

**Definition of done**
When the user comes back from the project edit page, they will still see what they saw before.

**Comment by ShovelHand** [comment]
I think we should cancel this one. An absurd amount of developer time (Oamar and I have both had a go at it) has been spent on trying to accomplish this one small change, and I don't feel like we're any closer to getting this done. 
Preserving a react component's state is supposed to be easy, so I'm not sure what's going on. Our Table component comes from a react-table import, but for all it's documentation on what components need to be memoized, etc. there doesn't seem to be any clear explanation as to why this is not working. I have gleaned a few details, such at the  filter value is undefined whenever the  table loads, but my attempts to preserve that value anywhere aren't working out. 
If we really want this feature, and I certainly see the usability benefit, any further work I do will involve trying to use a table library other than react-table, which represents a significant time investment. 
@mitovskaol @lukegonis @okanji

**Comment by okanji** [comment]
@ShovelHand I agree, this is something that we will be able to implement when we have the freedom to create it from scratch in the re-write and not be constrained to the way it's been set up in the current registry. Even though we are deciding not to continue the development of this I am glad that it has been a valuable learning experience.
