### ISSUE TITLE
Add authentication and authorization to the API

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#655]
Implement keycloak auth in the API. Authorization should be granular with read, write privileges for users and admins.

Would be nice to be able to scope admin roles (e.g someone can be an admin for a projects belonging to a particular ministry). This does not need to be implemented, but auth should be set up in a way that makes granular authorization like this easy to set up. 

DoD

- [ ]  Keycloak authentication is set up in API, available for all resolvers to use this authentication
- [ ]  Set up test users in SSO with different credentials to test API auth

**Comment by lukegonis** [comment]
Please get in touch with @NickCorcoran  about using the new KeyCloak realm in the registry.
