### ISSUE TITLE
Front end user experience and design

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#658]
ON HOLD UNTIL OUR NEW UX/UI DESIGNER JOINS THE TEAM IN JUNE/JULY
As we are doing a re-write, we have the opportunity to take a look at the user experience and the flow of the current front end and critique it to help us decide on changes that will be implemented in the new front end.

We should have a high-level discussion about the user experience for the new front end. This will involve a meeting with the Dev team, Billy, Olena and whoever else may be interested. 

Dod:
- [ ] Research the design of other project platforms (like google cloud console e.t.c) and compile a small report on findings such as screenshots of dashboards e.t.c
- [ ] Research project dashboard existing templates like material UI
- [ ] Compile this information to be presented in the meeting
- [ ] Conduct meeting
- [ ] Create tickets for components based on the meeting

**Comment by mitovskaol** [comment]
@marthaedwards Would you like to participatee in this discussion?
