### ISSUE TITLE
Create validator functions for quota strings

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#687]
The new project registry will support custom quotas, but we should constrict the client to only be able to input/ select valid quota for CPU, Memory, Storage, Snapshot. 

Below is an example from the current registry. 

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/4b63110e-0ac8-4b18-95d9-35d4456a582d)

In order to support custom quotas, we need to understand what a valid quota looks like for CPU, Memory, Storage, Snapshot. I.e do the quota and limit need to be integers? Do they need to be multiples of some number? Should we set upper and lower limits for the size of the quota that can be inputed (we probably should), what would those be for each type of quota? 

Once we have found this out, we need to write a validator function for the API for each of the CPU, Memory, Storage, Snapshot strings as shown above that will throw and Error if an invalid quota string is passed to it.

**Dod:**

- [x] Create some documentation on what a valid quota should be for CPU, Memory, Storage, Snapshot. This will help us create the front end component for selecting the quota (when we start working on the front end)
- [ ] Create validator functions that throw an error when a quota string is invalid and create a PR into the new registry API

**Comment by ShovelHand** [comment]
When we say, "what valid quota should be...", are we talking about our defined best practices, or what OpenShift will allow? My vote would be for the first, with maybe some message like, "your request of 6 CPU cores is in excess of typical requirements. Contact the Exchange Lab to discuss your project's requirements", or something like that. 
@okanji

**Comment by okanji** [comment]
@ShovelHand that's a good question. If possible, can we have two validators? One that simply checks of open shift will allow it (i.e the project will be provisioned) and one that implements best practices?

**Comment by okanji** [comment]
@ShovelHand I don't believe that we have anything that checks if a quota is valid. The way it currently works is that we have like 5 options that are hardcoded into the front end. All of those options are valid as we created them. For the re write, we want to give the user the ability to input any value that is valid so that's why we want the validator functions

**Comment by ShovelHand** [comment]
Checked off the first box because this already exists. https://developer.gov.bc.ca/Need-more-quota-for-OpenShift-project-set
