### ISSUE TITLE
make quota changes in batch

### ISSUE THREAD

**Issue by ll911** [bcgov/platform-services-registry#691]
**Describe the issue**
currently, I can only adjust quota for one project space at a time, I would like to adjust changes for the project set, instead of 4 separated requests

**Definition of done**
make quota request for project set, can set different quota for different environment, and submit as one request per project set instead of 4 different requests.

**Comment by mitovskaol** [comment]
@ll911 Leo, we intentionally separated quota increase requests for each namespace to encourage teams to think whether they need the increases for all environments. The situation with the resource "wasting" in Silver has gotten to the point where we now require a justification for every quota increase request. A request for the first namespace must be approved before the request for the next namespace can be submitted.

When teams become more digilent with using resources effectively, we may decide to reconsider this decision, but for now this is the process that will remain in place.
