### ISSUE TITLE
In the Platform Registry - Broken link in the "Git documentation for Platform Services Registry and a link to report issues can be found  here." line

### ISSUE THREAD

**Issue by rstens** [bcgov/platform-services-registry#694]
**Describe the issue**
Link is broken

Git documentation for Platform Services Registry and a link to report issues can be found  [here.](https://registry.developer.gov.bc.ca/https://github.com/bcgov/platform-services-registry)

**Comment by ShovelHand** [comment]
Hi,  Roland. This ought to be fixed in the latest build, but I will make sure I have not made a mistake here.

**Comment by ShovelHand** [comment]
Fixed in newer build. Closing this ticket.
