### ISSUE TITLE
Email Quota information display error

### ISSUE THREAD

**Issue by w8896699** [bcgov/platform-services-registry#695]
![image.png](https://images.zenhubusercontent.com/5d6ffb905ec50a5aa4201bcb/e6e5c142-23bd-4221-8db8-0bffdaa06dcc)
**Describe the issue**
 there is an error in the confirmation email. Quota Size: [object Object] See picture above 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Quota size can be displayed correctly in email

**Comment by lukegonis** [comment]
This bug will be addressed in the registry 2.0
