### ISSUE TITLE
When populating a new environment please use license plate in secret names

### ISSUE THREAD

**Issue by rstens** [bcgov/platform-services-registry#711]
**Describe the issue**
In my case, I was provisioned an environment b1d40d and in this environment 2 Artifactory related secrets were populated in tools:

**b1d40d-tools**
- artifacts-default-vltnyk
- artifacts-pull-default-vltnyk

The secret names get suffixed with a random id.

**Definition of done**
I would like to see the secrets created as such:
- b1d40d-artifacts-default
- b1d40d-artifacts-pull-default

The reason is that this will allow me to template my deployment scripts better, instead of having to look up the secret name whenever I run my deployment template.

I know, not a major deal, but more of a convenience thing.

**Comment by mitovskaol** [comment]
@caggles I will move this ticket to the Backlog to look into in the next Sprint
