### ISSUE TITLE
Write tests for project resolvers

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#715]
The project resolvers let the font end read projects, these need to have corresponding integration tests.

- Create jests units tests for all **project** resolvers in platform-services-registry-api
- Work with @okanji for this ticket. This may involve pair programming and creating examples

Dod:

- [ ] Units tests for each **project** resolver

**Comment by ShovelHand** [comment]
Oamar pointed out that this really needs a few more features in place before there's anything to test. Moving to Blocked for now.
