### ISSUE TITLE
Users should be able to request a new namespace via an actions menu

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#72]
Create a button, up near the Logon button that appears when the user is authenticated. This button, when clicked / touched, should show a menu allowing the user to see actions they can take. The first action, will be to request a new namespace set.

![Screen Shot 2020-09-22 at 2.43.03 PM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/6cef1dd2-ba21-418c-bf7c-faa1bcadd605)

Here is what a similar button does on a cloud service provider's web console / portal:

![Screen Shot 2020-09-18 at 1.46.22 PM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/9f30a03a-b4e0-45ad-bbee-2a5319078f12)

**Comment by mitovskaol** [comment]
Please update the menu item under the Create button to: "A new Openshift project set" to stay consistent with the existing intake process
