### ISSUE TITLE
Long email address handle

### ISSUE THREAD

**Issue by w8896699** [bcgov/platform-services-registry#720]
**Describe the issue**
We now only allow email that is under 30 character, some user do have very long email address

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done
- [x] to test, enter a 40 character email in the front end, save the change and go back to project record in the registry to confirm the email appears

**Comment by qrdn** [comment]
There seems to already be a system in place to detect and prevent emails over 30 characters long.

**Comment by qrdn** [comment]
No, the next button is blocked until the validator allows it to do so, when all the red messages are gone. There is similar behaviour when the email does not have a valid ending.

**Comment by rstens** [comment]
see 736,739 as bugs reported on this
