### ISSUE TITLE
Add klab2 to the project regisry

### ISSUE THREAD

**Issue by w8896699** [bcgov/platform-services-registry#723]
**Describe the issue**
Klab2 is a new cluster.
Just like klab, only admin can see this option

Contact @StevenBarre to get access details for KLAB2 cluster

**DoD**
- [x] update registry schema
- [x] update registry constants list
- [x] update provisioner
- [x] create CD for project creation in klab2
- [ ] end to end testing of namespace provisioning testing is successful

**Comment by StevenBarre** [comment]
Following

**Comment by w8896699** [comment]
I think we might need to update in ccm as well including auth, acs, and resources generator.

**Comment by ShovelHand** [comment]
@w8896699 Hi, Billy. 
What is the schema registry, and schema constants list, and where do I find those? What's involved in updating the provisioner, and where do I start out to "create CD for project creation"?

**Comment by ShovelHand** [comment]
"KLAB2 is a new Openshift cluster that we have recently added to the Platform and we want to be able to provision namespaces there through the Registry the same way we provision them on other Openshift clusters. This dropdown option will only be available for users with admin access to the Registry, the same way that only admins can provision namespaces in other LAB clusters - KLAB and CLAB.
However, I want to clarify that this ticket is not only aboutt adding KLAB2 as an option in the dropdown but making changes in other parts of the Registry to enable the actual provisioning in Openshift, in other words, the provisioning of namespaces in KLAB through the Registry must actually work and create namespaces in Openshift", says Olena.

**Comment by ShovelHand** [comment]
Note to self: at this point I'm trying to confirm that I did "update registry schema" properly before checking off the item.

**Comment by ShovelHand** [comment]
Ian is taking care of the dependency I added to this ticket. What a guy!

**Comment by ShovelHand** [comment]
I am sending this off for Billy's review. Ian has done the provisioner part, and I believe Steven took care of the last item in the DoD some time earlier.

**Comment by ShovelHand** [comment]
@StevenBarre is that last item in the DoD, "end to end testing of namespace provisioning testing is successful", something I should leave in your hands, or is there someone else I should talk to about that?

**Comment by StevenBarre** [comment]
We're still working on getting the KLAB2 cluster accessible to your team. Maybe just put this in Blocked for now? Once you can access the cluster I'm hoping you can set up the provisioner and do the testing.

**Comment by ShovelHand** [comment]
Sounds good. Putting in blocked for now.

**Comment by ShovelHand** [comment]
Ian has made some configuration changes for this environment, outlined by Steven. In Ian's words:
"I have modified the namespace template to add the desired fields only for NSX clusters
The “thin” quota file has been added, as well as a new default deny network policy template. These will be used only when the target cluster is NSX (klab2 or emerald)"
