### ISSUE TITLE
Create a dashboard where the user can view their existing projects.

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#73]
## Story

As a user, I would like to see all my previously requested projects in a "Dashboard" format so that I can see what I have requested and I have a clear understanding of what requests were received by the registry.

## Description

When a user authenticates they should be taken to a "Dashboard" where they can view a table of all the namespaces they have requested. 

![Screen Shot 2020-09-22 at 2.56.44 PM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/399b8eae-1b93-4310-9bb1-8de53007b381)

## Done When

A user logs into the dashboard and sees a history of their requests (and only their requests) in table format with each "card" representing a project.

**Comment by jleach** [comment]
@yhfreeman Hey, I'll make some API change for this ticket so that it only returns the authenticated users projects and not every project in the registry (which is what will happen now).

**Comment by mitovskaol** [comment]
Can we please display the PO and TC email info as well.

**Comment by mitovskaol** [comment]
Justin and I reviewed the dashboard (view-only feature) and are very happy with it. Consider the UAT testing done :)

**Comment by yhfreeman** [comment]
The dashboard view feature is merged in PROD-READY (silver) code base on November 05, 2020.
