### ISSUE TITLE
When updating Product Owner name, I ran into unexpected data entry limitations

### ISSUE THREAD

**Issue by rstens** [bcgov/platform-services-registry#736]
**Describe the issue**
When adding a product owner name to the project, I ran into 2 issues:

1. Data entry does not accept dashes in the last name: "Aubertin-Young" - Error: Must be alphabetic
2. The email address only takes 32 characters: "macgregor.aubertin-young@gov.bc.ca", error: Max 32 characters

These limitations seem arbitrary and counter-productive.

**Additional context**
![image](https://user-images.githubusercontent.com/22899001/176035574-1570730c-8b60-4cdd-83fc-9974216b6bfe.png)

**Definition of done**

1. Any valid visible character should be allowed in the name fields (dashes, periods, colons, diacritics etc.)
2. Comply with: 
_In addition to restrictions on syntax, there is a length limit on
   email addresses.  That limit is a maximum of 64 characters (octets)
   in the "local part" (before the "@") and a maximum of 255 characters
   (octets) in the domain part (after the "@") for a total length of 320
   characters. However, there is a restriction in RFC 2821 on the length of an
   address in MAIL and RCPT commands of 254 characters.  Since addresses
   that do not fit in those fields are not normally useful, the upper
   limit on address lengths should normally be considered to be 254._

**Comment by rstens** [comment]
Related to 720

**Comment by lukegonis** [comment]
Hello @rstens thank you for submitting this issue, we will review and prioritize it at our Sprint Planning meeting next week.

**Comment by lukegonis** [comment]
@rstens the email address length limit has been increased to 40 characters
We will open an issue to address the first concern in this issue (allow dashes in names)

**Comment by ty2k** [comment]
Hi @rstens, just wanted to close the loop and let you know that both of issues you mention should be taken care of now.

1. The form validation now allows spaces and dash characters.
2. A stop-gap solution was put in place to increase the length of characters accepted in email addresses in the front- and back-end of the app. Some very long but valid email addresses may still be blocked.

Please note that the Platform Services Registry application is in the process of having both its front- and back-end re-written, at which point the validation and length rules will be liberalized to accommodate more use cases.

In the specific case of the new Product Owner you mention in your post, the Technical Lead was able to submit an update using the Product Owner's details, and the Registry was able to process it.

Thank you very much for reporting this and for your patience while we fixed it.
