### ISSUE TITLE
Move documents from Miro to Mural

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#737]
We need to start moving documents out of Miro and into Mural.

Dod:
The following documents: https://miro.com/app/board/o9J_kpdNXhE=/ 
 are moved out of miro and into this mural board: https://app.mural.co/t/platformservices5977/r/1641490288136 are

**Comment by qrdn** [comment]
The migrated mural board is at: https://app.mural.co/t/platformservices5977/m/platformservices5977/1657826638454/d3f1625dfedb6bf8f8024c44ab088ee1220a7df1?sender=u6dec79b7b17b9f7132fa6175
