### ISSUE TITLE
Email character limit

### ISSUE THREAD

**Issue by mtspn** [bcgov/platform-services-registry#739]
**Describe the issue**
The email character limit in the registry is shorter than some email addresses (32 characters)

**Additional context**
![Screen Shot 2022-06-29 at 4 02 36 PM](https://user-images.githubusercontent.com/99685508/176560021-8a8f5c06-6d45-493d-990a-503c94c3a817.png)

**Definition of done**
- [ ] Registry allows email addresses longer than 32 characters

**Comment by rstens** [comment]
Duplicate of 737

**Comment by mtspn** [comment]
I should have searched first! Thanks Roland, I'll close this issue.
