### ISSUE TITLE
Developer Guild presentation

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#750]
There is an opportunity to take part in presenting about GraphQl at the Developer Guild presentation on Jul 27th. Oamar will be the main presenter and will create the presentation and allocate a bit of time for you to present something about GraphQl. This would be something small and manageable like showing an example query from the new Registry API.

ToDo

- [ ] Meet with Oamar to go over the presentation and decide on what you will be presenting

**Comment by Kolezhanchik** [comment]
https://docs.google.com/presentation/d/1jp8bYYIDdAgMl9Us3E7CbLHW1oZZrwo6IxkljYwjcY0/edit?usp=sharing
