### ISSUE TITLE
Form validation for create product request

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#760]
The form to create product requests is under development: 

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/a8efef41-cfa9-4291-9ad4-b961d2c40a09)

We need to implement form validation to make sure that the user inputs valid data into the forms e.g an email is in the correct email format. 

Use the react hooks form package to implement form validation in the create product request

**Comment by lukegonis** [comment]
@okanji  The front end UI for the new registry should be redone to match exactly what we have in the current registry
