### ISSUE TITLE
Dead link on registry readme

### ISSUE THREAD

**Issue by mtspn** [bcgov/platform-services-registry#777]
**Describe the issue**
In the architecture section of the [platform services registry readme](https://github.com/bcgov/platform-services-registry#architecture) there is a dead link: https://github.com/bcgov-c/devops-fulfillment-pipeline
**Additional context**
The link is meant to point to the namespace provisioning repo
**Definition of done**
- [ ] Link points to the correct location, or is removed.

**Comment by okanji** [comment]
This will be fixed by the new registry
