### ISSUE TITLE
The app doesn't load on safari due to a regex issue

### ISSUE THREAD

**Issue by loneil** [bcgov/platform-services-registry#793]
**Describe the issue**
Attempting to navigate to https://registry.developer.gov.bc.ca/dashboard on Safari on a Mac fails to load the page (blank white screen). The browser console shows an error below.

**Additional context**
Add any other context, attachments or screenshots
![image](https://user-images.githubusercontent.com/17445138/198122404-3f4f64ff-8424-4b3e-90f9-2ae4c361d401.png)

Tried on OSX Monterey, version 15.6 of Safari. Also checked an older version of Safari (through BrowserStack) and the same issue occurred. 

No problems on Chrome/Firefox/Edge (on Windows at least)

**Definition of done**

**Comment by okanji** [comment]
Hi @loneil , thanks for pointing that out. I tried that out myself and yes I can confirm that it does not work on safari.We are very close to releasing a new version of the registry that will not have this issue and I can confirm that this issue will not be the case
