### ISSUE TITLE
Transaction Test result not accurate 

### ISSUE THREAD

**Issue by w8896699** [bcgov/platform-services-registry#794]
**Describe the issue**
Currently, uptime.com is doing transaction tests for the registry's dashboard. But the test didn't really check if project is successfully loaded or not. It would be best if we can have some HTML indicators to represent that the dashboard project has been loaded completely so the transaction test can be more accurate.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
The registry dashboard page can have an HTML element to represent loading-complete.

**Comment by ShovelHand** [comment]
"You can find more info about transaction test on Google, but basically I will need a HTML element when all dashboard projects (this api call: https://registry.developer.gov.bc.ca/api/v1/profile/dashboard-projects) finish fetching. So when project finish loading, this html element shows on the dahsboard page and uptime.com knows that this page has been successfully loaded. This html tag can be anything, just need a unique identifier(id or class).

The test we run now just check if Git documentation for Platform Services Registry and a link to report issues can be found appears in dashboard page, which doesn’t represent the project load situation."
