### ISSUE TITLE
Implement Graph API search for contacts in new registry front end

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#838]
**Describe the issue**
The new registry should use the Microsoft Graph API to look up contacts for project owners and technical leads. A user should only be able to add a contact that they can look up through the microsoft graph API.

**Rational/Why**
. This way a user cannot add a 'random' person as a contact on a project. Only gov. contacts will be added to projects

**Additional Context** 
This has been implemented in the current registry. The same will need to be implemented in the new registry

Here is the file that fetches the user from the API: https://github.com/bcgov/platform-services-registry-web/blob/main/src/components/forms/UserInput.js

It corresponds to this component in the frontend:

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/4fd4d9a4-09a2-4e3d-a1b9-43d5ab6b88be)

This is the component that you will need to implement the graphapi search. The intended flow is that when creating a user, the graph API will fetch the email of the user such that they can only enter in an email that exists in the graph API. 

The graph api will fill out the email field and possibly any of the other fields in the UserInput form. These are email, ministry, firstName, lastName, githubId. I am not sure what information the graph API has, but lets automatically fill out the fields that it provides, the rest will need to filled out manually by the user.

**Note** Since I am not around to clarify things and you have not worked in this repo before, don't worry if you are not able to get the intended functionality down 100%. Just setting up the graph API will be extremely helpful. I can always take if from there to get the component working all the way.

- Would be nice to also have some documentation in the readme about using the Graph API, if this has already been done in the Registry 1.0 readme, then it can be copied over

**Dependencies**
Alex C has already implemented this once, so there should not be a need to pull in any additional people into this.

**Comment by ShovelHand** [comment]
This is done, and ready to be merged into the main branch.
