### ISSUE TITLE
Add sonarcloud/ owasp Zap into our pipeline and use ACS to review/remediate image security issues

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#846]
Our security team has made these requirements for going live with the new registry.

**Comment by w8896699** [comment]
- [ ] sonarcloud scan: 
1. https://sonarcloud.io/project/overview?id=bcgov_platform-services-registry-web
2. https://sonarcloud.io/project/overview?id=bcgov_platform-services-registry-api

- [ ] owasp zap scan: happens every monday
1. https://github.com/bcgov/platform-services-registry-web/actions/workflows/zap_scan.yaml
2. https://github.com/bcgov/platform-services-registry-api/actions/workflows/zap_scan.yaml

**Comment by w8896699** [comment]
Will have a meeting with Nick about ACS image fix

**Comment by w8896699** [comment]
Still haven't find a good solution yet, Nick asked me to try: https://github.com/flipkart-incubator/Astra, but it doesn't works out.

**Comment by NickCorcoran** [comment]
Since we have SonarCloud and OWASP ZAP in use I think this ticket should be closed.  If we want additional scanning for the api, then we can create a separate ticket.

**Comment by w8896699** [comment]
Seems like the graphQL scan works: https://github.com/bcgov/platform-services-registry-api/actions/workflows/zap_scan.yaml
