### ISSUE TITLE
License plate should be a link to the console and emails should be mail to links in the dashboard

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#848]
In the product/ request dashboard, the license plate and the emails should be clickable links.

- The license place should be a link to the OC console. Copy the link format from the current registry
- The email should be a mail link

Definition of done:
The above is implemented and Alex L has reviewed it

**Comment by Kolezhanchik** [comment]
@okanji in the old reg  license place link is not in board and route to dev test tool or prod, please, see the screenshot. Should I do it from dashboard? if so, where to route dev, tool, test or prod? 

![image.png](https://images.zenhubusercontent.com/62c35ec2ef07f0a53a3f3d28/fc86fd36-f392-447e-92a4-3045c450dc82)

**Comment by okanji** [comment]
@Kolezhanchik, I have done this from the project page already I just have not pushed it. We just need to do it now from the dashboard row:

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/977b1710-e187-485a-a63f-ad8cca80251c)

. The url format will be the same as in the current registry, you will need to take a look at the current registry and inspect the url format
