### ISSUE TITLE
License plate generated for public cloud projects must start with a letter

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#852]
**Describe the issue**
Public cloud projects must have license plates that start with a letter, as this is a requirement from AWS. In preparation for adopting public cloud we need to verify that license plates always start with a letter. If this is not the case then we need to change this for public cloud.

We may need to get in touch with the public cloud team for more information on this

**Comment by Kolezhanchik** [comment]
for now generateLicencePlate.ts creates licencePlates started with "t" for non-production and other letters for production
![Untitled.png](https://images.zenhubusercontent.com/62c35ec2ef07f0a53a3f3d28/88e625f6-03df-4b7e-9758-0ba61c497ec3)
