### ISSUE TITLE
Allow annotation of project edit requests

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#857]
**Describe the issue**

It is very useful when evaluating a quota edit request to add notes to the approval or rejection for internal use. This may be, for example, adding a note saying: 

"This is a temporary increase to allow database upgrades. Contact team on May 14th to reclaim the quota."; or
"Rejecting. They have plenty of storage. They need to reclaim existing unused storage so they can create new PVCs".

- All notes should be attached to the quota change in issue #856.
- All notes should indicate who created the note incase more information is needed.

**Additional context**

n/a

**Definition of done**

As a registry administrator, I would like to add a note or memo when approving or rejecting a quota request. The comments shouldn't be visible to clients and users, only to platform admins. Different admins can post comments to the same request.

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/857?planning-poker) with Zenhub @alexandralloyd @funtigr @okanji @Kolezhanchik
