### ISSUE TITLE
When fulfillment fails or stale requests exists a human should be alerted

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#863]
**Describe the issue**

From time to time one of our smart robots does not complete a quota increase. When this happens it fails silently. It is only when the team ask for an update to we discover that it failed. 

As a user, I would like it if the automation could automatically alert the team if a quota request has failed, or if un-fulfilled requires are in the queue. This could be done by a nightly CronJob.

**Additional context**

n/a

**Definition of done**

When fulfilling a quota change request fails or stale requests exist in the queue then an alert should be generated for a human to look into. When a request is pending for 1 hour, send an alert email to Platform Services + Billy + Ian mailbox that this request needs someone to look into. 
Stretch goal would be to post it in the RocketChat in the future.

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/863?planning-poker) with Zenhub @Kolezhanchik @okanji @funtigr

**Comment by Iryna-Kaplun** [comment]
Ian Watts advised that this ticket can be closed and here is his comment: 

> Yes, I think that particular ticket can be closed. There are other tickets with more recent information for achieving the same result. Not sure which one is closest, but it is related to the cron job that checks the status of requests in the provisioner. Here are the ones I see when I search for "cron":
2058
2021
1846
