### ISSUE TITLE
Remove form components from request page

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#869]
**Describe the issue**
Currently, the Request pages reuse the form components in the Create Request page. This is an issue as the request page is not editable but the form components indicate to the user that a request can be edited. 

**Definition of done**
The request page does not show any form inputs, all options that were selected in the create or edit page are shown in plain text.

**Comment by funtigr** [comment]
1. The Test Env Quota is not showing Current Quota:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/6ec74867-4732-4399-9a69-770fa76a2d95)

2. Regular request has heading Requested Quota but doesn't show it:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/d6146f67-a164-40e4-9aea-5603d3345c82)

3. In Current quotas only CPU is shown. Memory and Storage are empty:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/b8058b4f-73b9-4d7b-89be-78863c701d43)

**Comment by funtigr** [comment]
Now everything looks as expected except one little thing. 
When we make a **_Change Quota_** and it is approved the **_Request_** shows only **_Current Quota_** (which after change has values of Requested Quota) but no **_Requested Quota_**. And it's shown in grey. 
It's fine but if we think of **_Request Tab_** as a **_History Tab_** it's an unexpected thing.
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/5214ed23-6a37-44da-9d36-f138e10d51ec)
