### ISSUE TITLE
Re implement deletion check

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#873]
**Describe the issue**
Deletion check needs to be implemented in the new registry such that a user will not be able to delete a namespace if it is NOT empty.

**Additional context**
This is a feature that was available in the previous registry

**Definition of done**
The deletion check exists in the new registry and performs as explained above.
After a PO click "delete", a message appears if the namespace is not empty: "Your name space cannot be deleted. Please make sure all projects are deleted before deleting a namespace".
If a namespace is empty, the safety text is already implemented and it says "Are you sure you want to delete this product?"

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/873?planning-poker) with Zenhub @okanji @Kolezhanchik @funtigr @alexandralloyd

**Comment by okanji** [comment]
Artem and I have decided to wait till the provisioner is available for test. This way we can test the deletion feature without creating and deleting products in the prod version of the registry

**Comment by okanji** [comment]
Artem is working on setting the required openshift secrets for this to work.

**Comment by okanji** [comment]
Zhanna and Artem have pointed out an issue for this, I am currently working on it

**Comment by funtigr** [comment]
Now it works on our side without flaws but is blocked at Provisioner side.

**Comment by funtigr** [comment]
There is a small problem after the deletion itself.
Now if we delete the project the deletion goes fine but we have a remainder on the Products page. It looks the same as it was not deleted from the outside:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/3a50750f-fdc6-4207-b385-91f534f1c2e7)
But when you click inside the product it is just empty:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/8668ce0e-525e-4772-a3c5-927e2a948ff4)

On the Requests Page it looks as provisioned Delete request:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/fcc2e912-113a-4329-8a0b-879e72d534c4)

The name of this particular product is:
"Artem Test June 8.1 Backend contacts and photos!" and its license plate is "eba608".

**Comment by funtigr** [comment]
Needs more testing to ensure deletion works on different clusters.
