### ISSUE TITLE
Gather API requirements for the public cloud team

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#874]
**Describe the issue**
Public cloud will integrate with our platform and will use our API. We may need to build out new API endpoints or show them our existing endpoints.

We need to kick this off with a Technical meeting with the public cloud.

These people should be in attendance:
- Sal
- Artem
- Zhanna
- Oamar
- Warren
- Carles
- Prabhu

Optional attendees: 
- Billy (as he has been working with public cloud API)
- Nick (Platform security)
- Ian 
- Shelly 

In preparation for the meeting, Oamar will:

- Meet with Billy to get updated on public cloud
- Update our API documentation and create examples for fetching and creating data on each endpoint.
- Create an example of creating an Auth token for API endpoints

**Definition of done**
- [ ] Meet with Public Cloud
- [ ] We understand the public cloud requirements for our API

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/874?planning-poker) with Zenhub @okanji @Kolezhanchik @alexandralloyd @funtigr

**Comment by Iryna-Kaplun** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/874?planning-poker) with Zenhub @Iryna-Kaplun
