### ISSUE TITLE
Public cloud provisioner callback authentication

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#876]
**Describe the issue**
We will be creating an API endpoint for the public cloud provisioner to call when a project has been provisioned.

**Additional context**
The public cloud team has expressed interest in creating an auth token that will only be used by the public cloud team.

**Definition of done**
Talk to people with auth experience, like Shelly or Nick or Marco about if this is possible and how it can be achieved

**Comment by mitovskaol** [comment]
@okanji Is this still relevant? Has it not been completed already?
