### ISSUE TITLE
Environment name should appear over each quota column

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#877]
**Describe the issue**

Project edit requests no longer display environment name above the quota columns. To ensure clarity regarding the requested namespace for a quota change, each quota column should include the corresponding environment name. This is crucial because a single edit request may contain multiple quota change requests for different namespaces.

**Additional context**

![Screenshot 2023-04-20 at 9 16 26 AM](https://user-images.githubusercontent.com/390891/233427770-c5b1d41f-fb06-487a-a58c-b9eb439e92a8.png)

**Definition of done**

The environment name appears above each quota column.

**Comment by Iryna-Kaplun** [comment]
This ticket if fixed. Close it.
