### ISSUE TITLE
Add Missing Objects to the Registry Gitops Repo

### ISSUE THREAD

**Issue by caggles** [bcgov/platform-services-registry#880]
During the outage post-mortem, Ian indicated that he had a significant list of objects that should have been in the gitops repo but weren't. The recovery would have been much easier/faster if they had been.

This is also a good opportunity for Artem to learn a little more about the infrastructure behind the registry.

Add the missing objects and the config stuff for the tools namespace!

**Comment by IanKWatts** [comment]
I have added an Argo CD Application for the registry tools namespace, which includes BuildConfigs, a ServiceAccount, Role, and RoleBindings.

**Comment by IanKWatts** [comment]
I'd say the next step for the registry would be to create its secrets in vault and update deployments to pull them from there instead of from openshift secrets.
