### ISSUE TITLE
Exporting registy data includes test project namespaces

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#881]
**Describe the issue**

There are some erroneous results when the CSV file is downloaded from the registry. There a number of `test` projects. I think they should be removed.

**Additional context**

![Screenshot 2023-04-20 at 4 57 09 PM](https://user-images.githubusercontent.com/390891/233510434-abbd28d0-4b77-45f7-8ce6-4577aa8f44d4.png)

**Definition of done**

The test namespaces should be removed from the production data. This clean up process should be done only after the deletion check is implemented in the registry. The team will only review and delete the test namespaces that were created by the app dev team.

**Comment by Iryna-Kaplun** [comment]
Oamar will have a meeting with Zhanna and Artem to carefully review all test namespaces to ensure the proper deletion of only test namespaces.

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/881?planning-poker) with Zenhub @funtigr @Kolezhanchik @okanji
