### ISSUE TITLE
Create a second dev environment for the registry 

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#884]
It would be helpful for the app development team to have another dev environment. This will allow multiple developers to test their feature branches simultaneously.

We also have the public cloud API deployed in dev that is blocking us from using the environment for anything else, so having an additional dev instance would be helpful. 

**Note:** Billy Li has said he would be happy to help out with this ticket so feel free to contact him 
Try to clone the existing namespace and have it as a second dev space. 

Dod:
- A second dev environment is available for a developer to deploy their feature branch. 
- Show the rest of the dev team (Oamar) how you created this.

Stretch Goal
- We can have an unlimited number of dev environments (is this even possible?)

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/884?planning-poker) with Zenhub @alexandralloyd @funtigr @Kolezhanchik @okanji

**Comment by funtigr** [comment]
Had a discussion with Ian about the best way to implement it. 
And it's adding a new env in our existing set of namespaces (101ed4). It's definitely solvable but would need some time.
