### ISSUE TITLE
Make the cluster field plain text once it is provisioned

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#885]
A cluster is not changeable after it is provisioned, so it should not be a dropdown input and should be changed to plain text.

We may also want to make the ministry not changeable after creation, but this needs to be double-checked. Talk to the product owner about this feature.

Dod:
- Once a project is provisioned, the cluster should be plain text.
- Find out if ministry should also be plain text and if so, make it plain text

**Comment by funtigr** [comment]
After Create Request is provisioned it appears in the Product Tab. Starting from there the Cluster field is not editable and shown in plain text as expected:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/7f18cd5d-a292-4f2b-bc4e-b736cdabd0d1)
