### ISSUE TITLE
Implement pagination, search, filter and sort for all users in the registry 

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#886]
Currently, pagination, search, filter, rows per page, and sort are only available for admin and read-only admin users in the registry. We now want to roll this feature out to all users.

The functionality and the UI should be the same for all users as it is for admin. Except that a user should only see projects that they are a contact of. 

Dod:
- The above is implemented and tested. This is just for projects but not all the requests

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/886?planning-poker) with Zenhub @alexandralloyd @funtigr @Kolezhanchik @okanji

**Comment by funtigr** [comment]
Pagination is in place and works good, but Sorting and Filtering elements are absent for regular users:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/808e7063-3d5f-4e77-84d4-c86905274abe)

**Comment by funtigr** [comment]
It now works on Test for all users:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/1dcf39e0-796c-4c59-aa1d-543defcbdb52)
