### ISSUE TITLE
Billing group component that allows POs to select previously created billing groups they've created, or create new billing groups

### ISSUE THREAD

**Issue by lukegonis** [bcgov/platform-services-registry#891]
**Describe the issue**
A billing group is a "tag" that represents a group of projects that will receive a single bill for their usage. E.g if projects A, B, and C are tagged with the same billing group, then they will be billed together. We need to create a billing group component.

**Additional context**
A billing group is attached to a project owner. When a new project is created, the billing group component should give the options to:

a) Create a new billing group, the project will be tagged with the new billing group. A billing group is a random five-digit alphanumeric string.
b) Use an existing billing group that the project owner has created in the past, selecting that billing group will tag the project with the selected billing group.

Please see Gautham's UI designs for a guideline but there is no need to implement the full design yet. You can MVP the component as long as the above functionality is included.

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/6defeb88-0d5e-40e6-a461-d77c549cd96b)

He has made a video about the component: https://bcgov-my.sharepoint.com/:v:/r/personal/gautam_malhotra_gov_bc_ca/Documents/Microsoft%20Teams%20Chat%20Files/Billing%20Group.mov?csf=1&web=1&e=id5FbE

This component will require work on the database schema and API. @okanji will help design this. First, implement the UI then ping Oamar when that is done.

**Definition of done**
The Billing group component is created alongside the necessary DB and API functionality
A PR for this is made to the **public-cloud-api** and **public-cloud-web** branches (not our main branch)

**Comment by Iryna-Kaplun** [comment]
This ticket has been cancelled and replaced by the ticket #
