### ISSUE TITLE
Create a cron job to get provisioning status of projects

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#893]
**Describe the issue**
We want to create a cron job in the registry API that periodically looks up the workflow status of all active requests. If the workflow has been completed, the request will be marked as provisioned.

**Rational/Why**
We want to decrease the amount of "miss-communications" between the provisioner and the registry as sometimes projects are successfully provisioned but the registry does not get the callback and the project is "stuck in provisioning". This cron job will work in addition to the callback such that in case the callback does not happen, the cron job will be able to mark a request as provisioned.

**Additional Context** 
The **cron job** will go in our **api**: `src/index.ts`. It would look something like this:

```
const task = cron.schedule('* * * * *', () => {
    
   // Rest of the code goes here ..

});

task.start();
```

The `* * * * *` is *cron syntax* for the job to run every minute. You can learn more about *cron syntax* here: https://crontab.guru/ . We want the cron job to run every **7 min**.

The code in the cron job should do the following:

1) Get all active requests
2) For each active request, fetch the workflow status (see below for more info on this request). You may want to use `Promise.allSettled` for this so that all the fetch requests are done concurrently. 

This is the documentation for the fetch request that returns the project workflow status:

```
% echo $PROVISIONER_NAMESPACE
eb6118-prod
% echo $WORKFLOW_NAME
clab-eb6118-507f191e810c19729de860ea
% curl -s https://provisioner-api.apps.silver.devops.gov.bc.ca/api/v1/workflows/${PROVISIONER_NAMESPACE}/${WORKFLOW_NAME} | jq '.metadata.labels'
{
  "events.argoproj.io/action-timestamp": "1684350214242",
  "events.argoproj.io/sensor": "nats-registry",
  "events.argoproj.io/trigger": "nats-registry-workflow-trigger-clab",
  "workflows.argoproj.io/completed": "true",
  "workflows.argoproj.io/phase": "Succeeded"
}
```

The data returned for `"workflows.argoproj.io/completed"` and ` "workflows.argoproj.io/phase"` will determine what to do with the request:

```
If completed = false, then wait and check again later
If completed = true and phase = Error, keep it open, and send a message to Rocketchat so someone can investigate (we
 will do this in another ticket, just put a comment where this would happen i.e "notification call will happen here" 
If completed = true and phase = Succeeded, then close it
```

The workflow has the format: `{cluster}-{licensePlate}-{request-mongodb-objectId}`. This will need to be generated dynamically for each active request and passed in as a URL param as shown above. The provisioner namespace url param is in this format: `{licencePlate}-{pocess.env.PROVISIONER_NAMESPACE} where the PROVISIONER_NAMESPACE environment variable will need to be set. Its value should be set to either `prod`, `test` or `dev` depending on the namespace that the API is running in. I.e the dev namespace will have an environment variable called PROVISIONER_NAMESPACE with the value of `dev`.

3) For each response that shows that a workflow was successful, we want to run the code that is currently in the `provisionerCallbackHandler` in the file: `src/controllers/provisionerCallbackHandler.ts`. I recommend transferring this code into a function and putting it in our scripts folder and passing in the required fields which are **licencePlate** and **cluster**. This will mark the request as provisioned. If a response comes back as unsuccessful, do nothing for that active request.

Additionally, we need to add some fields to the nats message in the following file `src/nats/message`. Add the following fields: 
- licencePlate
- workflow: `{cluster}-{licensePlate}-{request-mongodb-objectId}`

This will enable the provisioner to name the workflows with the workflow string we pass to nats. 

**Dependencies**
- The provisioner will need to be set up to accommodate this. Ian is working on that.

**Tests**
- Artem to test this in our test namespace, maybe recommend some automated tests?

**Definition of done/Acceptance Criteria**
- The above cron job has been successfully tested and is merged into prod

**Comment by IanKWatts** [comment]
A rule was recently created to prevent CronJobs from running more than once every five minutes.  I suggest having it run every five or ten minutes, so either `*/5 * * * *` or `*/10 * * * *`

**Comment by Kolezhanchik** [comment]
// Completed with error (failed)
//     completed: true
//     phase: Error - we have a problem
// Completed successfully
//     completed: true
//     phase: Succeeded - completed 
// In progress
//     completed: null
//     phase: Running   - in progress

**Comment by Kolezhanchik** [comment]
// Completed with error (failed)
//     completed: true
//     phase: Error - we have a problem
// Completed successfully
//     completed: true
//     phase: Succeeded - completed 
// In progress
//     completed: null
//     phase: Running   - in progress

**Comment by funtigr** [comment]
After call with Ian:
We need to add to new statuses:
- Completed with Error
- In Progress

Also I will add (and later attach here) a task for the UI part. Probably we will need to add a status: ERROR or FAILED on UI for customer to understand that their project is not Provisioned. With current mechanism client sees endless PROCESSING in this case.
