### ISSUE TITLE
Migrate env variables for pre deletion check from the old registry namespace to the new one

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#894]
We are re-implementing the pre-deletion check in the new registry and therefore we need the Open Shift cluster secrets for each cluster in the new registry.

Note: 
- We now have a separate provisioner instance for dev, test, and prod so this might mean that we need different secrets for each cluster. Talk to Ian and Billy about this.  
- Add these env variable to Vatult

Dod:

The pre-deletion check secret for each cluster is available in dev, test, and prod. They are backed up in Vault

**Comment by funtigr** [comment]
Ian says that the Clusters Access Tokens from the Old Registry App are up-to-date so we can use them now.
Also he says we can use the same Tokens for Test and Dev.
As I see from the code of Pre-Deletion Script it uses the access tokens from the Env Variables which are defined in the Deployment YAML (it points to the OpenShift secret "platsrv-registry-mongo-creds"). So provisioner is not in the chain of pre-deletion check. It queries the cluster themselves.
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/40f31422-60ca-42bd-8821-85d52b668210)https://console.apps.silver.devops.gov.bc.ca/k8s/ns/101ed4-prod/secrets/pre-deletion-service-account/
But just to clarify I asked Ian and here is his response:
"The Dev version of the registry is configured to use the Dev version of the provisioner (in eb6118-dev), the Test version of the registry is configured to use the Test version of the provisioner (eb6118-test), and Prod to Prod."
"You can see the registry configuration for the provisioner in the 'platsrv-registry-api' Deployment. In the Test registry, it's like this:

            - name: NATS_HOST
              value: 'nats://nats.eb6118-test.svc'
In Dev, it's

            - name: NATS_HOST
              value: 'nats://nats.eb6118-dev.svc' "

The new Secrets are added to Vault.
