### ISSUE TITLE
[New UI] Rows per page feature adjustments

### ISSUE THREAD

**Issue by mtspn** [bcgov/platform-services-registry#897]
**Description**
Since we are moving to a new design the task description changes.

We need to implement the '**Rows per page**' feature.
The case previously described by Matt must be taken into account:
**Given** User changes the default '**Rows per page**' to a non-default value (e.g. 50)
**And** User goes to the second (or any non-first) page
**When** User clicks into a Product
**And** returns back to the Products List page
**Then** the user should be returned to the same page with the same set of '**Rows per page**'

**Definition of done**
If this feature suggestion is adopted: 

- [ ] The number of rows selected is retained when switching pages

**Comment by funtigr** [comment]
Also please fix the problem with excessive space under the rows in Requests List page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--604a2c231989b0482744be4423d4fe4ff460a667/image.png)

**Comment by funtigr** [comment]
If a user is on the last page of pagination and tries to change the number of rows to less, he is sent to the middle of pagination (if there are 50 products it sends to 25th).
If the user changes number of rows to more, no products are shown and the numbers in the "Showing" string become confusing ("Showing 201 to 50 of 50 results" after change from 10 to 50 on the page from 41-50).

Before changing number of rows:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNExqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd0734a1a0fb4e147748eef993d808c3346f988a/image.png)

After changing to less:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHJqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e2d41e287100848da33e2ee61d870186c35d3f1/image.png)

After changing to more:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUhqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4aaddd1377ab44acf5fcb3bee96029620746d33d/image.png)

**Comment by junminahn** [comment]
Good catch! I have fix the issue and deployed on dev site now.

**Comment by funtigr** [comment]
Now changing the "Rows per page" on the final page of pagination works well. It redirects to the first page of pagination with the new filter set.
