### ISSUE TITLE
Link to create public cloud project for empty list component 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#899]
**Issue**
Link from a button create in empty list component for public cloud projects leads to privet  cloud create page

**Definition of done**
Link from a button create in empty list component for public cloud projects leads to public cloud create page

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/899?planning-poker) with Zenhub @alexandralloyd @funtigr @Kolezhanchik @okanji

**Comment by funtigr** [comment]
The link in the empty list now leads to Create page of a Public Cloud product:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/ba1e558b-0f05-4d0a-be31-8c954bb6e5de)
