### ISSUE TITLE
Create product details page for private cloud products

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#902]
The private cloud products page has been redesigned, these pages need to be implemented:

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/c1e40b45-f9a9-4bc0-b7f8-decbf333ad8d)

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/6e952a9f-9d20-42b2-8c72-4d09e0481e7d)

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/a7ee19ce-6f8e-4890-8d9a-07ea9d2bcc16)

Dod:
The above is implemented

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/902?planning-poker) with Zenhub @alexandralloyd @funtigr @okanji

**Comment by okanji** [comment]
Not doing as we do not need this UI.
