### ISSUE TITLE
Indicate if a user does have existing projects in the registry 

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#904]
If a user does not yet have an existing project in the registry, they need to go through the onboarding process before they can provision a project.

Currently, we need to search for the user in the registry search bar to see if they have any projects but this is cumbersome. A better way to do this would be to show some sort of a status next to a user in the request row if they do not have an existing project (like an x).

For example, there could be an x next to the user in this row under active requests if they do not have an existing project.

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/5507247f-a047-46f2-861a-8571ef7433ae)

**Additionally**, we could modify the request flow to automatically prompt the user to go through the onboarding process if they have not already done so, and the onboarding admins could automatically be notified.

Dod:
The above is implemented in the UI for the registry 
When I look at a user's name in the registry, I want to know if they have other projects/products already. This should be visible for admins only.

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/904?planning-poker) with Zenhub @okanji @funtigr @alexandralloyd

**Comment by Iryna-Kaplun** [comment]
@gautammalhotra21 new ticket for Gautam
