### ISSUE TITLE
Enable delete for public cloud

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#906]
Public cloud will now include the ability to delete a project. Therefore, we need to add the delete functionality to the public cloud

Dod:
A similar UI is implemented for delete in public cloud as in private cloud
The API is able to handle a delete request for public cloud
nats message with request_type DELETE

**Comment by okanji** [comment]
Need to talk to Prabhu about this. Also, can we potentially MVP this? I.e go live with public cloud without the ability to delete public cloud projects, or is this something that needs to be available when we go live? (Will bring this up in sprint backlog meeting)

**Comment by funtigr** [comment]
Deletion works good. 
For deleting the Product callback from Public Cloud is needed. 
After deletion the Product is left in the DB collection but has Inactive status to be shown in Requests history for regular users.
