### ISSUE TITLE
Public cloud new designs - create projects and requests tables

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#908]
The table component for the public cloud UI needs to be created: 

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/9be555a4-9a87-4fe2-93bc-bab49d6c52fd)

Dod: This table is implemented

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/908?planning-poker) with Zenhub @alexandralloyd @funtigr @Kolezhanchik @okanji
