### ISSUE TITLE
Add N8N flow running once a day: Smoke test of Registry UI Happy Path.

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#909]
**Description:**
* Add a GitHub Action to trigger smoke test of Registry App Happy Path (Adding a project for now but more to come). 
* Add an N8N flow that will trigger that GitHub Action that will be triggered once a day. And maybe after something is deployed.

**Comment by mitovskaol** [comment]
@funtigr What is the business value of this work?

**Comment by funtigr** [comment]
In the current work process it is not needed anymore.

**Comment by funtigr** [comment]
It was supposed to be an educational task to master N8N and GitHub Actions.
