### ISSUE TITLE
The user should be able to transfer a project profile to another user

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#91]
## Story

As a user, I would like to transfer one of my project profiles to another user so that they can be the administrator of said project.

## Description

When a user creates a project profile it is associated with their credentials (used for authentication). As users switch jobs or roles they may need to transfer a project from themselves to another user. We can do this manually in the database with an SQL `UPDATE` query but it would be better for users to self serve.

Initial implementation can be as simple as sending a email with a link to the person accepting the project profile. Once they click the link they need to authenticate and at that point, the system transfers the project.

- or -

For a more advanced implementation, the user could start by selecting a project and then, see some additional functionality for that project profile that indicates "transfer to another user". If they select this they can either select, or start typing the name of the user to receive the project profile. Once they select the user they are asked to confirm the transfer, upon conformation the transfer takes place immediately.

## Done When

A user can logon to the system, select one of their project profiles, and transfer it to another user with an account in the platform services registry.

**Comment by yhfreeman** [comment]
Reopen this issue as it's still relevant. It will likely tie into the current ongoing feature of Registry web user authentication & authorization where some level of access under a given profile is given to:
- profile initial requester
- profile project owner and technical contact
- user under role ADMINISTRATOR
