### ISSUE TITLE
Create the accounting code component for public cloud.

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#912]
The provisioning form has been modified for public cloud. 

The Billing group field has been removed. We will be collecting the 'Account Coding' instead. The 'Account Coding' is 24 digits and in the format as shown in the text field.

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/a56f6c48-016e-48d0-9ccd-f76f453e290f)

Assumptions to be clarified (ask Gautham or Prabhu):
- The registry will not create an accounting code
- The registry will not show current accounting codes to the users
- It is possible to change the accounting code in an "edit request"
- The registry will not check to see if an accounting code is correct/ exists. The admin approving the request will check it manually to make sure it exists and is correct.
-  We are sending this accounting code in NATS message

Dod:
The above component is created and the accounting code is saved in the DB as part of the project.

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/912?planning-poker) with Zenhub @alexandralloyd @funtigr @Kolezhanchik @okanji @gautammalhotra21

**Comment by gautammalhotra21** [comment]
@okanji @Kolezhanchik [Figma Link](https://www.figma.com/file/llP34TwOrBUjUGey9PUu6c?node-id=1218:32600#484324119)

**Comment by funtigr** [comment]
Backend is not yet ready for testing. Also it somehow stops the Requests page from loading.

Frontend part works as expected except for a small bug described below:
- The code is divided into parts
- If you paste needed number of the alphanumeric symbols they get properly formatted
- If there are non-alphanumeric symbols they got removed automatically before adding spaces and the error is shown
- If the code is less than 24 symbols the error is shown
- If the code is more than 24 symbols it is trimmed and the error is shown
- If the code is in lowercase it becomes uppercase

![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/6774a406-5824-4a9a-b93d-01aeae4e31e0)
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/b760928c-9343-4c29-aa19-b530b970ad48)
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/5d85bcc9-0a72-4e6a-880c-a0891731088d)
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/0d0fff8d-ad7b-4851-8ffa-698e55b7b409)

**Small bug**
When I input 24 symbols and a non-alphanumeric symbols, for example: "Ygk90bb9b8hl88bpl907yup0;" or "Ygk90bb9b8hl88bpl907yup0;:" I get an error about zero code though the alphanumeric string gets formatted properly:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/d0a2e6b5-9033-4441-a6d0-b433a66d62ee)
