### ISSUE TITLE
Make dropdowns and textfields Plain Text when Product is in Pending or Provisioning/Processing state

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#913]
Now, when Product is in Pending or Provisioning/Processing state the dropdown and textfields look like interactable but they are not.

Definition of Done.
When Product is in Pending or Provisioning/Processing state show it's parameters in Plain Text form.

**Comment by funtigr** [comment]
The ticket is finished:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdk8zIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c6af59cd6e846a70ba07a0928e3cde4dd7e6bb37/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlczIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3e308c58eb52244bbbba91245bdcab8760b70df6/image.png)

The link to the Pull Request: https://github.com/bcgov/platform-services-registry-web/pull/78
