### ISSUE TITLE
The registry should have the concept of a group administrator

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#92]
## Story

As a group administrator for an organization (CITS, AG, JAG, etc) I would like to see all the projects belonging to my organization so that I can do reporting on said projects.

## Description

It would be useful to have the concept of a group admin who can see all projects belonging to an organization. This admin would have the ability to do reporting (read access) to all of those projects.

**NOTE**: I'd be hesitant to implement edit without some sort of audit trail so that we know who is going in and updating other peoples project profiles.

## Done When

A user can login to the registry with a specific roll associated to their account giving them the ability to see all the project profiles belonging to a particular organization.

**Comment by jleach** [comment]
I think this is implemented already. Please close if done.

**Comment by sbathgate** [comment]
This hasn't been fully implemented yet, but shouldn't be too difficult to make the required adjustments. Prior refactoring laid the ground work for this.
