### ISSUE TITLE
Re design accounting code to be more intuitive

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#923]
Currently, the accounting code is a 24 digit number that might not make sense to the end user. It is actually comprised of several "codes" that are likely to be more intuitive and recognizable to the end user.

Instead of having a single text input for the whole code, it should be split up into individual text boxes for each code that it is comprised of.

**Comment by gautammalhotra21** [comment]
@okanji  [Figma Link](https://www.figma.com/file/llP34TwOrBUjUGey9PUu6c?node-id=1218:32600#484324119)

**Comment by funtigr** [comment]
Found a couple of non-blocking issues:

1. In “Standard Object of Expense (STOB)” field the label says "Enter the responsibility centre here (e.g. 22222)”. The example input has 5 digits while it should be 4.
2. When you input something in the "Project Code" with fitting number of valid symbols and one special symbol the error says "There are 0 characters - code should be 7 characters" while there are 7 symbols in the text field e.g. "JHGJHGH," or "JHGJH;GH": [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamtpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8ac415cac7df03ec947c4a109cd16384e8d13efb/image.png)
