### ISSUE TITLE
Public cloud license plate should be a clickable link that would take you to your AWS namespace in the AWS console

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#928]
When a user clicks on the license plate in the products table, it should open up a new tab and take them to their AWS namespace.

Ideally the URL for this namespace will be "predictable" and can be constructed using data about the project that we already have in the registry. Contact Prabhu about setting this up

**Comment by Kolezhanchik** [comment]
Prabhu. provided with the same email for all of license plates for public cloud - https://login.nimbus.cloud.gov.bc.ca/api
