### ISSUE TITLE
The technical contact should include the identity provider in the ID.

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#94]
## Story

As the platform administrator (auth provider) I would like the technical and product GitHub ID to specify `@github` as part of the username so that it correlates to what is seen in KeyCloak (SSO).

## Description

We'll soon (probably day 1) have OIDC as the authentication mechanism for the OCP 4.x clusters (klab, clab, aro and silver). This means that the KeyCloak back-end will have the user registered as `uername@github` or `username@idir`. If we don't start sending this information prior to date one we won't know what provider is being used for a particular user. Also, it may be harder to adapt to offering IDIR in the future.

To make this work we could simply update the Web from having the field `GitHub ID` to being `IDIR or GitHub ID` and accepting them in the format `user@idir` or `user@github`. The API will also need to change the message sent to NATS from:
```json
   technicalContact: { githubId: 'jleach' } }
```
to 
```json
   technicalContact: { userId: 'jleach', provider: 'github' }
```

## Done When

The user can specify IDIR or GitHub as the ID when registering both the Technical Contact and Product Owner and that information is correctly stored in the database and sent to NATS.

**Comment by jleach** [comment]
@j-pye FYI. Issue created.

**Comment by jleach** [comment]
Ref. #96 relates to this.

**Comment by yhfreeman** [comment]
Reopen this issue as it's still relevant.

**Comment by j-pye** [comment]
@yhfreeman I thought this was already resolved? Both TC and PO have the IDP ? -- Maybe i'm misunderstanding the issue?

**Comment by yhfreeman** [comment]
You are correct @j-pye in a way that we do currently have the IDP indicated in the nats (bot) message. I was more examining the ticket against its "definition as done" where it says "...information is correctly stored in the database and sent to NATS.". Currently, the github provider is hard-coded within the Registry api not stored in the DB. Should we create another separate ticket since it seems to have caused confusion already? Thanks. cc @sbathgate

**Comment by j-pye** [comment]
I think it's fine to continue with this ticket @yhfreeman 
We may want to change the title or add a note to the body that this only applies to the DB/API components + Labels.
