### ISSUE TITLE
The platform admins should be able to message the owners of a namespace

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#95]
## Story

As a platform administrator (DXCAS) I would like an API that I can use to send messages to the owners of a namespace so that I can inform them of an issue.

## Details

The platform administrators would like to be able to send messages to users informing them of an issue in their namespace. This might be an issue with quotas, pods in a crash loop, or improperly configured deployments. What they are asking for is an simple messaging API that, for the initial release, just send an email to both the TC and PO.

Example
POST /api/v1/messaging

```json
  namespace: 'abc123-prod',
  message: 'Something is broken. Please fix.
```

## Done When

The SA can post a message to an API with JWT authentication and know that a message has been sent (best effort) to the owner of a namespace. They should be returned the message ID for reference.

**Comment by yhfreeman** [comment]
Hi @mitovskaol, as a PO could you confirm this feature is still relevant / wanted? If so, we can reopen it. Many thanks.

**Comment by mitovskaol** [comment]
@yhfreeman  Yes, this feature is still relevant but a low priority at the moment.

**Comment by yhfreeman** [comment]
Reopen this issue - see above^
