### ISSUE TITLE
Improve resource allocation efficiency with data-driven approach

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#954]
**Describe the issue**

Teams need a better understanding of how to create project quota change request according to our policy and best practice.

If this feature is implemented @jleach can help outline the policy and procedure to be communicated when teams create a quota edit request.

**Rational/Why**

We believe in a data-driven approach to resource allocation. Instead of teams guessing their project's needs for each environment, we aim to start with a smaller allocation and increase it based on actual usage. Currently, this process might not be well communicated, leading to teams asking for more resources than necessary. As a result, they might misuse resources when provided with a large quota, leading to suboptimal application design. We want to avoid such scenarios and ensure resource efficiency.

**Additional Context** 

n/a

**Dependencies**

n/a

**Tests**

**Definition of done/Acceptance Criteria**

We need to clearly communicate our policy and process to allocating resources.

**Comment by Bauger-BC** [comment]
Include text input or document input on quota request page.
