### ISSUE TITLE
email notifications for public-cloud users

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#960]
no notifications for public cloud  PO/TL

need to notify PO/TL about product status 

Wording can be used from private public email templates

**Definition of done/Acceptance Criteria**
- public cloud product PO/TL get emails: request received, request approved for create and edit requests

**Comment by funtigr** [comment]
Now we have the OpenShift mentioned in the very bottom of the "Provisioning Request Received":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUFxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ecb9211ed9f593e3061f205ebf9c6195753cfb4a/image.png)
