### ISSUE TITLE
Bugs and improvements in Public Cloud MVP

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#961]
**List of bugs**
- [x]  No Filters on the Public Cloud Product page -> Decided to push MVP without them
- [x]  After creating Edit request the Budget is not shown in the Product waiting for approval -> fixed, waiting for push
- [x]  After creating Edit request the old Account Coding is shown instead of a requested one -> fixed by Zhanna is in the PR with e-mails for Public Cloud
- [x]  After Edit request approval the Account Coding is not changed -> fixed by Zhanna is in the PR with e-mails for Public Cloud
- [x]  When Edit request is created there is no ability to Approve the Request as it is approved automatically and goes straight to the Processing stage -> Working as expected
- [x]  Namespace links in the Request -> Removed for now, waiting for the push

New Requirements from Olena:
- [x]  Rewrite the landing page to include the info about the public cloud onboarding requirements => add public cloud onboarding requirements to submit request for public cloud
- [x]  On the provisioning request page replace Platform Services Team with Cloud Pathfinder and their email cloud.pathfinder@gov.bc.ca
- [x]  Remove the common components section from the provisioning request page
- [x]  next to the Budget fields, add CAD to make it clear that the dollar amounts 
- [x]  Make the **provider** plain text in an existing public cloud project as it is not editable. Currently it is disabled but there is still the dropdown UI: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFVwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58c76cf549a82cee16dadef4950949fc8c1dc06d/image.png), lets make it plain text

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/961?planning-poker) with Zenhub @Kolezhanchik @okanji @funtigr

**Comment by Kolezhanchik** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBNZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50f93c933a4cdf73f9c22e3589c6c130c85a4e2e/image.png)

**Comment by funtigr** [comment]
1. Filters are now available for Public Cloud and work as expected
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjgvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe82c0c589e679dd10c065fb9f4e93d4de9e94e8/image.png)

2. The Budget is shown in the Edit Request and reflects the edit changes
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc28vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--082c37cc6348db8f3aab68e5448469e733d2882a/image.png)

3. The Account Coding in the Edit Request is showing the new edited value
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3MvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1f455652722a47485433033825ca65527e02e15a/image.png)

4. The Account Coding changes are now applied after Edit Request is Provisioned:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmxFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2631ab75ccf40ffc3c2eea049aa768cd6fdc9dc5/image.png)

5. The Edit Request is approved automatically - it is made like this by design.

6. Namespace links are removed from the Public Cloud Request page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb05FIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d9e6bf08928582d490bd6040462b09b297e50e29/image.png)

7. Public Cloud info is not added to the Login page for now:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2hFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bbb4f16d0f35b78ceb5f42d87bdbd893d31855be/image.png)

8. The Request page for Public Cloud now has the text and contacts for Public Cloud:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDlHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--01ad548a8f5d648c31dbb4ab46dd2a2de3af944f/image.png)

9. Common Components are removed from the Public Cloud Request page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWRHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b550e52f60d6f9b27d5777ec1d2f1af4b6e76a83/image.png)

10. The Budget field is now showing CAD both in Edit mode and in Plain Text mode:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdU5EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6f4bc46bdb0e01f87593e0839815c123d739f5a2/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3cvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--25bba13d94ba499d4330f058b6a14753974180fc/image.png)
 
11. Provider field is shown in Plain Text in the Provisioned Product:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWhHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--41721efe9453e72794bb0793b0e5873ea364f521/image.png)
