### ISSUE TITLE
Remove openshift namespaces from public cloud request page, show budget at public cloud request page

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#962]
**Describe the issue**
openshift namespaces are shown at public cloud request page while  budget isn't

**Rational/Why**
openshift namespaces are not relevant to public cloud

**Definition of done/Acceptance Criteria**
- openshift namespaces removed
- budget shown

**Comment by funtigr** [comment]
Now we don't have links to non-existing (in Public Cloud case) namespaces on Public Cloud Request Page.
And we have the Budget shown on Public Cloud Request Page.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVVqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9a9c378e37b06e4ea1e63028f39e3657d9593aab/image.png)
