### ISSUE TITLE
Public cloud enterprise support

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#963]
Add "Enterprise Support" to the public cloud provisioning form.

Definition of done: 

- [x] A check box for prod, test, tools and dev
- [x] The values for enterprise support is passed to the public cloud provisioner via the nats message
- [x] Update tests

**Comment by funtigr** [comment]
Last directive from Olena was to comment this code out for some time.
Now the client will have extended support for Prod by default and will not have ability to order extended support for other environments.

**Comment by Kolezhanchik** [comment]
closed Aug 24 2023, we made a design to postpone enterprise support for public cld product https://github.com/bcgov/platform-services-registry-api/pull/67
