### ISSUE TITLE
Email notifications for public and private cloud product PO/TL as to list of contacts changing 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#964]
**Describe the issue**
product PO/TL don't get notifications regarding contact list changing (private cloud PO/TL get notification about contact list changing in a case of quota change, but not only contact list changing) 

**Rational/Why**
PO?TL should be notified if contact list was changed 

**Definition of done/Acceptance Criteria**
- public cloud product TP/TL get notification in case list of product contacts was changed 
-  private cloud product TP/TL get notification in case list of product contacts was changed

**Comment by funtigr** [comment]
When I change one user to another I see the requested changes in the Current section and vice versa.
In the screenshot is the email that was received after changing platofrm.services account to artem.kravchenko account:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclZ5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--89f1cba89a291a352ea4110414ba933646094504/image.png)
