### ISSUE TITLE
to convert admin emails list for private and public cloud to environmental variable and to save it on openshift

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#966]
**Describe the issue**
a list of admin emails for public and private clouds are hardcoded and used in all namespaces and local development. the real admin email list should be used only in production namespace 

**Rational/Why**
Not to spam admin emails from test and local running apps

**Additional Context** 
to use separate branch to deploy to dev namespace 
for testing

**Definition of done/Acceptance Criteria**
- list of real admins emails is used only in production for public and private cloud

**Comment by funtigr** [comment]
An admin letter/email comes to the contact mentioned in the environment variable on Create Request:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2h6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ca4f14e0a6c8a71cce55831642605a42cf8b6ea8/image.png)

The Create Request for Public Cloud triggers the email:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanAwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--77d61afb210667c62c20e46df1b836c7dc7fcd5e/image.png)

The Create Request for Private Cloud triggers the email:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1YxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--090ec195ffac3388545574ad328811d0d98f0536/image.png)

The Quota Change (Edit) Request for Private Cloud triggers the email:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaE4xIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--34909893349d6090f9c4964afd89a795eab6193b/image.png)

The Delete Request for Private Cloud triggers the email:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFYxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a19520cbc0f88b598d4407255c5368cfb40787a7/image.png)
