### ISSUE TITLE
Complete sections 4 - 10 of Udemy Figma course

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#967]
**Describe the issue**
Taking a Udemy course on Figma essentials. This is ticket is for the next 2.5  hrs of coursework plus the associated assignments.

**Additional context**
Taking this for professional development.

**How does this benefit the users of our platform?**
Helps me be more efficient when using Figma.

**Definition of done**

- [ ] Sections 4-10  of the course is complete

**Comment by Iryna-Kaplun** [comment]
Moved to the Platform Experience board
