### ISSUE TITLE
Complete sections 21-23 of Udemy course

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#970]
**Describe the issue**
Taking a Udemy course on Figma essentials. This is ticket is for the next 2 hrs of coursework plus the associated assignments.

**Additional context**
Taking this for professional development.

**How does this benefit the users of our platform?**
Helps me be more efficient when using Figma.

**Definition of done**

- [ ] Sections 21-23 of the course is complete

**Comment by Iryna-Kaplun** [comment]
Moved to the Platform Experience board
