### ISSUE TITLE
Finish Udemy course (sections 24-29)

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#971]
**Describe the issue**
Taking a Udemy course on Figma essentials. This is ticket is for the last 2.5 hrs of coursework plus the associated assignments.

**Additional context**
Taking this for professional development.

**How does this benefit the users of our platform?**
Helps me be more efficient when using Figma.

**Definition of done**

- [ ] Sections 24 - 29 of the course is complete

**Comment by Iryna-Kaplun** [comment]
Moved to the Platform Experience board.

**Comment by Iryna-Kaplun** [comment]
Moved to the Platform Experience board.
