### ISSUE TITLE
Update all users documents with upn and idir

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#972]
We will now be capturing a users IDIR and UPN and passing that to the provisioner. We have implemented the front and backend changes but now need to update the existing users in our database.

Write a script that will fetch the IDIR and UPN for each users and update each user document in our production database

Dod:

- [ ] The script is created
- [ ] User documents are updated

**Comment by funtigr** [comment]
The script was run on prod and updated all the users that had upn or/and idir with corresponding fields.
