### ISSUE TITLE
Link RC API with word analysis program

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#974]
**Describe the issue**
Connect API to the word frequency analysis program to RC (see #959)

**Additional context**
Connecting via API would be idea, as it would allow for dynamic analysis (ie I wouldn't have to download CSV files every time I want to analyze something). However, if figuring out the authentication takes too much time I will just rely on the CSV file method. 

**How does this benefit the users of our platform?**
Allows for user feedback without surveying/interviewing users.

**Definition of done**
- Connection is successful

**Comment by Iryna-Kaplun** [comment]
Moved to the Platform Experience board
