### ISSUE TITLE
Update TL user journey

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#978]
**Describe the issue**
Connected to #975. Persona needs to be updated in order to accurately show where our users current pain points are.

**Additional context**
From [this journey](https://bcgov-my.sharepoint.com/personal/justin_hewitt_gov_bc_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjustin%5Fhewitt%5Fgov%5Fbc%5Fca%2FDocuments%2FDevOps%20SD%20and%20Bjorn%2FBjorn%20Resources%2FBjorns%20Experience%20DevOps%20Journey%20Map%2DsmallResolution%2Epng&parent=%2Fpersonal%2Fjustin%5Fhewitt%5Fgov%5Fbc%5Fca%2FDocuments%2FDevOps%20SD%20and%20Bjorn%2FBjorn%20Resources&ga=1) and [this journey](https://app.mural.co/t/platformservices5977/m/platformservices5977/1638556584173/2f768eb31d886d147eaf1f25fb317f3aa0bd024c?sender=ubf58a7267c86aa8dcd571926)

**How does this benefit the users of our platform?**
Helps us map their pain points.

**Definition of done**

- [ ] Mural is complete

**Comment by Iryna-Kaplun** [comment]
Moved to the Platform Experience board
