### ISSUE TITLE
Implement a CSV download for Public Cloud [New UI]

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#983]
Implement a CSV download for Public Cloud in new UI.

all of fields are checked for private cloud by default, for public cloud there should be provider instead of cluster
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1hyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--75224ea72de877b64466785ea63c29d659463801/image.png)

in general the functionality is the same as for private cloud 
https://github.com/bcgov/platform-services-registry-web/blob/main/src/components/DownloadCsv.js

DoD:
 - [ ]  public cloud user can download products in .csv format filtered and sorted list 
 - [ ]  functionality is tested and pushed to prod

**Comment by Iryna-Kaplun** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/983?planning-poker) with Zenhub @alexandralloyd

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/983?planning-poker) with Zenhub @funtigr @Kolezhanchik @okanji
