### ISSUE TITLE
Unable to Approve or Reject a Product on Dev and Test

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#986]
Unable to Approve or Reject a Product on Dev and Test
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGcvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6e293cadff8fc20fa6af7fd7f40b735c09032fdb/image.png)

**Comment by okanji** [comment]
Fixed
