### ISSUE TITLE
Double choice of Ministry and Cluster in the burger menu on a smaller screen after Hot fix

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#987]
After last Hot Fix with disappearing button a new bug appeared.

If the browser is shown on a smaller more narrow screen our buttons hide in a burger menu. If I click on that menu I see two buttons for both Ministry and Cluster. 

On Public Cloud Page I can even choose two different Ministries and the filtering by both will be made which obviously gives zero results:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1ZOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--22233b146e7538595855a70c92f423a408bf5cda/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcE5OIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fcd62e36ef2d43d5493ee43e870955ff2385dbd3/image.png)

Additionally, we should make the UI better by adding margins

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/987?planning-poker) with Zenhub @alexandralloyd @funtigr @Kolezhanchik @okanji

**Comment by funtigr** [comment]
Now we have single instance of dropdowns for Ministry and Cluster on narrow screens:
Private Cloud page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazl0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--05a5afeff79b0469cd3fcfbac0968c9dfc993d7f/image.png)
Public Cloud page:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFJ0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1ffd55d59ac6020e5221d6672f94e3098eb1fb73/image.png)
