### ISSUE TITLE
The name of a public cloud project should not have specific special charecters

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#991]
The name field for public cloud projects should not have the following special characters: https://docs.aws.amazon.com/mediaconnect/latest/ug/tagging-restrictions.html 

Otherwise, the provisioning will fail.

Dod: 
The form validation prevents submission of a name with the special characters and lets the user know what special characters are not allowed.

**Comment by funtigr** [comment]
Special characters are now not allowed in the name of the Public Cloud product:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTJTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--31d138ac072f68b47c4fb293b523a1b102e4bcd0/image.png)
