### ISSUE TITLE
Public Cloud Request shows successful submit but disappears when Budget has decimals in it

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#992]
If I make a Create Request in Public Cloud and use decimals in the Budget fields the Request is showing as successfully submitted and redirects me to the Requests page. But the Request itself is not made hence not showing up anywhere in the app.

change CAD to USD for budget, change color for "USD" to dark 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaENRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f93704d8708c78ea2e0e5c46865efe4b9dd0dd39/image.png)

**Comment by Kolezhanchik** [comment]
checked with Prabhu , budget for Public cloud could be Float

**Comment by funtigr** [comment]
Now we have an ability to add products with decimal numbers in the Budget fields:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTZTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9f3f1481fe48c8c1b0709539ad29d369bbd7b4a3/image.png)
